import type { Ui } from "../ui/ui";
import type { DatabaseServices } from "./database";

import { errorMessage, RuntimeError } from "../errors";
import { withQuietOutput } from "../ui/capture-output";
import { plural } from "../ui/format";
import { explain } from "./database";
import { computeMigrationState, readJournal } from "./migration-state";

export interface PreparedDatabase {
  /** Migrations applied by this run. */
  applied: number;
  /** Migration folders generated by this run. */
  generated: string[];
}

/**
 * The development bootstrap `vitnode dev` runs before anything serves a
 * request - the same three steps as `vitnode db:prepare`: generate a migration
 * for schema changes, apply what is pending, ensure initial data. All under
 * the migration lock, so two apps starting at once cannot race.
 *
 * Quieter than `db:prepare`: drizzle-kit runs in JSON mode, and only hands
 * the terminal over when it genuinely has to ask whether a change is a
 * rename. In a terminal nobody can answer, that generation is skipped with a
 * warning instead of hanging the dev server.
 */
export const prepareDevelopmentDatabase = async (
  ui: Ui,
  services: DatabaseServices,
): Promise<PreparedDatabase> => {
  const config = await services.drizzleConfig();
  const before = new Set(
    services.listMigrationFolders(config.migrationsFolder),
  );

  const planned = await ui.runTask("Checking database schema", async () => {
    await explain(services, ["up", "--output", "json"]);

    return explain(services, ["generate", "--explain", "--output", "json"]);
  });

  if (planned.status === "missing_hints") {
    if (ui.interactive) {
      ui.warning(
        "Schema changes need a decision - handing over to drizzle-kit:",
      );
      const { code } = await services.drizzleKit(["generate"], {
        capture: false,
      });
      if (code !== 0) {
        throw new RuntimeError(
          `drizzle-kit generate exited with code ${String(code)}.`,
        );
      }
    } else {
      ui.warning(
        "Schema changes need a rename decision - run vitnode db generate in a terminal. Continuing without a new migration.",
      );
    }
  } else if (planned.status === "ok" && (planned.statements?.length ?? 0) > 0) {
    await ui.runTask("Generating migration", async () =>
      explain(services, ["generate", "--output", "json"]),
    );
  }

  const generated = services
    .listMigrationFolders(config.migrationsFolder)
    .filter(folder => !before.has(folder));

  const task = ui.task("Connecting to the database");
  const handle = await services.open(config).catch((error: unknown) => {
    task.fail();
    throw error;
  });

  try {
    try {
      await handle.ping();
    } catch (error) {
      task.fail("Database unreachable");
      throw new RuntimeError("Could not connect to the database.", {
        cause: error,
        details: [errorMessage(error)],
        hint: "Is it running? In development, pnpm docker:dev starts one.",
      });
    }

    const local = await services.readLocalMigrations(config.migrationsFolder);
    const { pending } = computeMigrationState(
      local,
      await readJournal(handle.query, {
        schema: config.migrationsSchema,
        table: config.migrationsTable,
      }),
    );

    await withQuietOutput(ui.verbose, async () =>
      handle.apply(message => {
        ui.note(message);
      }),
    );
    task.succeed(
      "Database connected",
      pending.length === 0
        ? "up to date"
        : `${plural(pending.length, "migration")} applied`,
    );

    return { applied: pending.length, generated };
  } finally {
    await handle.close();
  }
};
