packages:
  - apps/*
  - packages/*
  - plugins/*
allowBuilds:
  '@swc/core': true
  esbuild: true
  sharp: true
  unrs-resolver: true
packageExtensions:
  '@tiptap/y-tiptap':
    dependencies:
      prosemirror-transform: 1.12.1
