import { defineContentType, field } from "@vitnode/core/content";

import { categoryContentType } from "./category";

/**
 * A tag keyed by `uuid` rather than `serial`: ids are generated by Postgres
 * (`gen_random_uuid()`), cross every JSON-facing API as lowercase strings, and
 * reveal nothing about how many tags exist or in which order they were made.
 *
 * Everything else about it is an ordinary localized content type - and its
 * relations show both directions of a mixed install: `category` points at the
 * *serial* category type, while `relatedTags` is a self-relation and so follows
 * the tag's own `uuid` strategy.
 */
export const tagContentType = defineContentType({
  id: "example.tag",
  tableName: "example_tags",
  idStrategy: "uuid",

  localization: { enabled: true, defaultLocale: "en", fallback: "default" },
  publication: { enabled: true },
  visibility: { enabled: true },
  duplication: { enabled: true },
  editorial: {
    enabled: true,
    revisions: { retention: 20 },
    preview: { enabled: true, expiresInMinutes: 30 },
  },

  fields: {
    name: field.text({
      localized: true,
      required: true,
      minLength: 1,
      maxLength: 100,
    }),
    slug: field.slug({ localized: true, source: "name" }),

    // A uuid record pointing at a serial one: the column is an `integer`,
    // because a foreign key always has the type of the key it points at.
    category: field.relation({
      nullable: true,
      onDelete: "set null",
      target: () => categoryContentType,
    }),

    relatedTags: field.relation({
      multiple: true,
      onDelete: "cascade",
      ordered: true,
      self: true,
    }),
  },

  publicApi: {
    enabled: true,
    path: "tags",
    fields: ["id", "name", "slug", "category", "relatedTags", "publishedAt"],
    filterableFields: ["relatedTags"],
    defaultOrderBy: "publishedAt",
  },

  admin: {
    titleField: "name",
    list: { columns: ["status", "updatedAt"] },
    form: { fields: ["name", "slug", "category", "relatedTags"] },
  },
});
