version: '3.8'

services:
  database:
    container_name: vitnode_postgres_dev
    image: postgres:17.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-root}
      POSTGRES_DB: ${POSTGRES_NAME-vitnode}
    volumes:
      - ./docker/dev:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - vitnode_dev

networks:
  vitnode_dev:
