/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.

import type * as apiPlugin0 from '@vitnode/blog/config.api'
import type * as apiPlugin1 from '@vitnode/example/config.api'

declare module '@vitnode/core/lib/fetcher/registry' {
  interface ApiPluginRegistry {
    '@vitnode/blog': typeof apiPlugin0
    '@vitnode/example': typeof apiPlugin1
  }
}

export type { ApiPluginRegistry } from '@vitnode/core/lib/fetcher/registry'
