/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the `vitnode:plugin-routes` Vite plugin on every
// `vite dev` and `vite build`, from one input: the plugins configured in
// `src/vitnode.config.ts`, and which of them export a `config.api` module.
//
// This is the only place an installed plugin's API is registered, and it is what
// `fetcher` resolves a call against. A plugin that augmented the registry from
// inside its own package would put its routes into the registry of every project
// that merely installed it, configured or not.
//
// Every import is `import type`, and each names one already-reduced type rather
// than a whole module namespace. A plugin's `config.api` reaches its Hono
// handlers, its database and its secrets; naming the type keeps all of that out
// of this graph, and out of the browser bundle.
//
// Same plugin configuration in, same bytes out: the entries are sorted by
// plugin id.

import type { VitNodeApiPlugin as ApiPlugin0 } from '@vitnode/blog/config.api'
import type { VitNodeApiPlugin as ApiPlugin1 } from '@vitnode/example/config.api'

declare module '@vitnode/core/lib/fetcher/registry' {
  interface ApiPluginRegistry {
    '@vitnode/blog': ApiPlugin0
    '@vitnode/example': ApiPlugin1
  }
}

export type { ApiPluginRegistry } from '@vitnode/core/lib/fetcher/registry'
