/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the `vitnode:plugin-routes` Vite plugin on every
// `vite dev` and `vite build`, from two inputs: `@vitnode/core`, whose own
// blocks every VitNode application gets, and the plugins configured in
// `src/vitnode.config.ts` that export a `blocks` module.
//
// Same plugin configuration in, same bytes out: the entries are sorted by
// plugin id.
//
// Evaluating this module registers the registry, so an application has to load
// it before rendering a `blocks` field. A block definition is metadata plus one
// public React component - there is no editor code in here, and no request is
// made to build it.

import type { BlockPluginSource } from '@vitnode/core/blocks'

import { buildBlockRegistry, setBlockRegistry } from '@vitnode/core/blocks'

import { blocks as blocks0 } from '@vitnode/core/blocks/built-in'
import { blocks as blocks1 } from '@vitnode/example/blocks'


export const pluginBlocks = [
  blocks0, // @vitnode/core
  blocks1, // @vitnode/example
] satisfies BlockPluginSource[]

export const blocksRegistry = buildBlockRegistry(pluginBlocks)

setBlockRegistry(blocksRegistry)
