/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the `vitnode:plugin-routes` Vite plugin on every
// `vite dev` and `vite build`, from two inputs: `@vitnode/core`, whose own
// blocks every VitNode application gets, and the plugins configured in
// `src/vitnode.config.ts` that export a `blocks` module.
//
// Same plugin configuration in, same bytes out: the entries are sorted by
// plugin id.
//
// `blocksRegistry` is the registry itself: import it and hand it to
// `<ContentZone registry={blocksRegistry} />`.
//
// Import this module ONLY from a route that renders blocks. Every plugin's
// block components are statically imported above, so anything that reaches
// this file eagerly carries all of them - which is why it must not be pulled
// in from a root module such as `router.tsx`.
//
// The API builds its own registry from the same plugins when it boots, so
// write-time validation never depends on this file being evaluated.
//
// A block definition is metadata plus one public React component. There is no
// editor code in here, and no request is made to build it.

import type { BlockPluginSource } from '@vitnode/core/widgets'

import { createBlockRegistry, setDefaultBlockRegistry } from '@vitnode/core/widgets'

import { blocks as blocks0 } from '@vitnode/core/widgets/built-in'
import { blocks as blocks1 } from '@vitnode/example/widgets'


export const pluginBlocks = [
  blocks0, // @vitnode/core
  blocks1, // @vitnode/example
] satisfies BlockPluginSource[]

export const blocksRegistry = createBlockRegistry(pluginBlocks)

setDefaultBlockRegistry(blocksRegistry)
