/* oxlint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the `vitnode:plugin-routes` Vite plugin on every
// `vite dev` and `vite build`: one import per configured plugin whose
// `content` module this build resolved, loaded and checked against the app's
// page routes. Pass it to `buildApiConfig({ contentModules })` so the API
// refuses public content URLs this build never saw.
//
// Same plugin configuration in, same bytes out: the entries are sorted by
// plugin id.

import * as contentModule0 from '@vitnode/blog/content'
import * as contentModule1 from '@vitnode/example/content'

export const contentModules: Readonly<Record<string, unknown>> = {
  '@vitnode/blog': contentModule0,
  '@vitnode/example': contentModule1,
}
