/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the `vitnode:plugin-routes` Vite plugin on every
// `vite dev` and `vite build`, from one input: the plugins configured in
// `src/vitnode.config.ts`, and which of them export an `admin/content` module.
//
// Same plugin configuration in, same bytes out: the entries are sorted by
// plugin id.

import type { ContentFrontendPluginSource } from '@vitnode/core/lib/plugin'

import { adminContent as adminContent0 } from '@vitnode/blog/admin/content'
import { adminContent as adminContent1 } from '@vitnode/example/admin/content'


export const pluginContentTypes = [
  adminContent0, // @vitnode/blog
  adminContent1, // @vitnode/example
] satisfies ContentFrontendPluginSource[]
