/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the `vitnode:plugin-routes` Vite plugin on every
// `vite dev` and `vite build`, from one input: the plugins configured in
// `src/vitnode.config.ts`, and which of them export an `admin/content` module.
//
// Same plugin configuration in, same bytes out: the entries are sorted by
// plugin id.

import type { ContentFrontendPluginSource } from '@vitnode/core/lib/plugin'

import { adminContent as adminContent0 } from '@vitnode/blog/admin/content'
import { adminContent as adminContent1 } from '@vitnode/example/admin/content'

/**
 * Every configured plugin's Content Engine frontend registration.
 *
 * A plugin appears here by exporting `admin/content`, and a plugin that does
 * not contributes no content types to the AdminCP. That is not an error - most
 * plugins register none - and it is decided at build time rather than
 * discovered in a browser: the specifiers below are literal, so a bundler
 * resolves them and nothing is reached through a computed string.
 *
 * This carries more than `admin-nav.gen.ts` and less than
 * `vitnode.config.ts`. Navigation needs ids, hrefs, permissions and icons; a
 * content *screen* needs those plus the components that replace a generated
 * input, a generated table cell and a generated form layout. Neither needs the
 * server config, which carries message loaders and API wiring a browser bundle
 * has no business holding.
 *
 * Nothing is copied and nothing is serialised: React components cannot cross a
 * JSON boundary, so the registrations stay compiled in each plugin's own
 * `dist` and arrive through a specifier a bundler resolved.
 *
 * The registry built from this is validated by `@vitnode/core` -
 * `buildContentFrontendRegistry` runs the same `validateContentTypes` the
 * API side runs, so two plugins claiming one `admin.path` fail loudly here
 * rather than giving one of them a screen and the other nothing.
 */
export const pluginContentTypes = [
  adminContent0, // @vitnode/blog
  adminContent1, // @vitnode/example
] satisfies ContentFrontendPluginSource[]
