/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the `vitnode:plugin-routes` Vite plugin on every
// `vite dev` and `vite build`, from one input: the plugins configured in
// `src/vitnode.config.ts`, and the `localeFiles` each one declares.
//
// Every specifier below is a literal, because that is the only kind a bundler
// can follow: `import(pkg + '/locales/' + locale + '.json')` resolves to
// nothing at build time, and a plugin's own locale barrel imports `./en.json`
// relative to the plugin's build output rather than to this app.
//
// Each loader stays a dynamic `import()`, so a language's JSON is a chunk of
// its own and none of it is in the initial bundle - the server loads the one
// locale a request asked for.
//
// Same plugin configuration in, same bytes out: core first, then the plugins
// sorted by id, and each package's locales sorted by code.

import type { LocaleMessagesMap } from '@vitnode/core/lib/i18n/types'

export const packageMessages: Record<string, LocaleMessagesMap> = {
  '@vitnode/core': {
    en: async () => await import('@vitnode/core/locales/en.json'),
  },
  '@vitnode/blog': {
    en: async () => await import('@vitnode/blog/locales/en.json'),
  },
  '@vitnode/example': {
    en: async () => await import('@vitnode/example/locales/en.json'),
  },
}
