/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the `vitnode:plugin-routes` Vite plugin on every
// `vite dev` and `vite build`, from two inputs and nothing else: the plugins
// configured in `src/vitnode.config.ts`, and the route manifest each of those
// plugins ships. Nothing here is discovered at runtime - the browser is handed
// this module, never a filesystem.
//
// Same plugin configuration in, same bytes out: the entries are sorted by key.

import type {
  PluginRouteModuleRegistry,
  ResolvedPluginRouteModule,
} from '@vitnode/core/framework/plugin-routes'

/**
 * Every configured plugin's route modules, keyed by `<pluginId>:<routeId>`.
 *
 * The specifiers below are literal, which is the whole point of generating this
 * file: Vite resolves them at build time and Rollup gives each module its own
 * chunk, fetched when a loader is first called. No route component is in the
 * initial bundle, and none of them is reached through a computed string - the
 * browser never asks what is installed.
 *
 * `satisfies` rather than a type annotation, deliberately: it checks the shape
 * while keeping both the literal keys and each module's real export types, so a
 * consumer's `await load()` is typed by the module it loaded.
 */
export const pluginRouteModules = {
  '@vitnode/example:example-page': () => import('@vitnode/example/routes/example-page'),
} satisfies PluginRouteModuleRegistry

/** Every key in {@link pluginRouteModules}, as a union. */
export type PluginRouteKey = keyof typeof pluginRouteModules

/**
 * The same route modules as plain data, in the same order.
 *
 * An object literal carries nothing beyond its keys, so the plugin id, the route
 * id and the specifier are repeated here for whatever builds the router: it can
 * walk this array, join each entry to its plugin's own route manifest by
 * `pluginId` and `routeId`, and look the loader up by `key`.
 */
export const pluginRouteEntries = [
  {
    entry: 'routes/example-page',
    key: '@vitnode/example:example-page',
    pluginId: '@vitnode/example',
    routeId: 'example-page',
    specifier: '@vitnode/example/routes/example-page',
  },
] as const satisfies readonly ResolvedPluginRouteModule[]
