/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the `vitnode:plugin-routes` Vite plugin on every
// `vite dev` and `vite build`, from the plugins configured in
// `src/vitnode.config.ts` and the route manifest each of those plugins ships.
//
// This is the *what*: which routes exist, and at which canonical VitNode path.
// Its sibling `plugin-routes.gen.ts` is the *how*: one lazy import per route
// module. Neither knows what a router is.
//
// Same plugin configuration in, same bytes out: the routes are sorted by path.

import type { PluginRoute } from '@vitnode/core/routing'

/**
 * Every route this app's configured plugins contribute, already validated.
 *
 * `buildPluginRouteManifest` produced this list while the app was being built,
 * which is the whole reason it is a literal here: a path that cannot be parsed,
 * an entry that cannot be imported and two plugins claiming one URL have all
 * already failed the build by the time this file exists. Nothing reads it to
 * find out whether the routes are valid - only to find out what they are.
 *
 * Deliberately not `as const`: a route's `segments` is a mutable array on
 * `PluginRoute`, and a frozen tuple would not satisfy it. `satisfies` alone
 * still checks every field and still narrows `area` and `kind` to their unions.
 */
export const pluginRouteManifest = [
  {
    area: 'admin',
    entry: 'routes/admin-example-page',
    id: '@vitnode/example:admin-overview',
    kind: 'page',
    namespaces: ['@vitnode/example.admin.overview'],
    parentId: null,
    path: '/admin/example',
    pluginId: '@vitnode/example',
    requires: null,
    routeId: 'admin-overview',
    searchEntry: null,
    segments: [{ kind: 'static', value: 'admin' }, { kind: 'static', value: 'example' }],
  },
  {
    area: 'main',
    entry: 'routes/example-page',
    id: '@vitnode/example:example-page',
    kind: 'page',
    namespaces: [],
    parentId: null,
    path: '/example',
    pluginId: '@vitnode/example',
    requires: null,
    routeId: 'example-page',
    searchEntry: null,
    segments: [{ kind: 'static', value: 'example' }],
  },
  {
    area: 'main',
    entry: 'routes/browse-page',
    id: '@vitnode/example:browse',
    kind: 'page',
    namespaces: ['@vitnode/example.browse'],
    parentId: null,
    path: '/example/browse',
    pluginId: '@vitnode/example',
    requires: null,
    routeId: 'browse',
    searchEntry: 'routes/browse-page.search',
    segments: [{ kind: 'static', value: 'example' }, { kind: 'static', value: 'browse' }],
  },
  {
    area: 'main',
    entry: 'routes/guide-layout',
    id: '@vitnode/example:guide',
    kind: 'layout',
    namespaces: ['@vitnode/example.guide'],
    parentId: null,
    path: '/example/guide',
    pluginId: '@vitnode/example',
    requires: null,
    routeId: 'guide',
    searchEntry: null,
    segments: [{ kind: 'static', value: 'example' }, { kind: 'static', value: 'guide' }],
  },
  {
    area: 'main',
    entry: 'routes/guide-index-page',
    id: '@vitnode/example:guide-index',
    kind: 'page',
    namespaces: [],
    parentId: '@vitnode/example:guide',
    path: '/example/guide',
    pluginId: '@vitnode/example',
    requires: null,
    routeId: 'guide-index',
    searchEntry: null,
    segments: [{ kind: 'static', value: 'example' }, { kind: 'static', value: 'guide' }],
  },
  {
    area: 'main',
    entry: 'routes/guide-topic-page',
    id: '@vitnode/example:guide-topic',
    kind: 'page',
    namespaces: [],
    parentId: '@vitnode/example:guide',
    path: '/example/guide/:topic',
    pluginId: '@vitnode/example',
    requires: null,
    routeId: 'guide-topic',
    searchEntry: null,
    segments: [{ kind: 'static', value: 'example' }, { kind: 'static', value: 'guide' }, { kind: 'param', name: 'topic' }],
  },
] satisfies readonly PluginRoute[]
