/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the `vitnode:plugin-routes` Vite plugin on every
// `vite dev` and `vite build`, from two inputs: `@vitnode/core`, which every
// VitNode application gets, and the plugins configured in
// `src/vitnode.config.ts`. Each source that exports a `routes` module is
// imported below, statically, because a route tree is small browser-safe data -
// a path, a shell, a message list, and one `lazy(() => import(...))` per page.
//
// No page or layout module is named here. Each one is reached only through the
// literal `import()` inside its own source's `lazy()` call, which Vite follows
// at build time and Rollup gives a chunk of its own - so no page is in the
// initial bundle and none is reached through a computed string.
//
// Same configuration in, same bytes out: the sources are sorted by id.

import type { PluginRouteDeclarationSource } from '@vitnode/core/routing'

import { routes as pluginRoutes0 } from '@vitnode/core/routes'
import { routes as pluginRoutes1 } from '@vitnode/example/routes'


export const pluginRouteSources = [
  {
    pluginId: '@vitnode/core',
    routes: pluginRoutes0,
  },
  {
    pluginId: '@vitnode/example',
    routes: pluginRoutes1,
  },
] as const satisfies readonly PluginRouteDeclarationSource[]
