/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as MainRouteImport } from './routes/_main'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DocsSearchRouteImport } from './routes/docs.search'
import { Route as DocsDocsIndexRouteImport } from './routes/_docs/docs.index'
import { Route as DocsDocsSplatRouteImport } from './routes/_docs/docs.$'
import { Route as AdminAdminCoreIndexRouteImport } from './routes/_admin/admin.core.index'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSearchRoute = DocsSearchRouteImport.update({
  id: '/docs/search',
  path: '/docs/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocsIndexRoute = DocsDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDocsSplatRoute = DocsDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => DocsRoute,
} as any)
const AdminAdminCoreIndexRoute = AdminAdminCoreIndexRouteImport.update({
  id: '/admin/core/',
  path: '/admin/core/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/search': typeof DocsSearchRoute
  '/docs/$': typeof DocsDocsSplatRoute
  '/docs/': typeof DocsDocsIndexRoute
  '/admin/core/': typeof AdminAdminCoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/search': typeof DocsSearchRoute
  '/docs/$': typeof DocsDocsSplatRoute
  '/docs': typeof DocsDocsIndexRoute
  '/admin/core': typeof AdminAdminCoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_docs': typeof DocsRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/search': typeof DocsSearchRoute
  '/_main/': typeof MainIndexRoute
  '/_docs/docs/$': typeof DocsDocsSplatRoute
  '/_docs/docs/': typeof DocsDocsIndexRoute
  '/_admin/admin/core/': typeof AdminAdminCoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/api/$'
    | '/docs/search'
    | '/docs/$'
    | '/docs/'
    | '/admin/core/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/api/$'
    | '/docs/search'
    | '/docs/$'
    | '/docs'
    | '/admin/core'
  id:
    | '__root__'
    | '/_admin'
    | '/_docs'
    | '/_main'
    | '/llms-full.txt'
    | '/api/$'
    | '/docs/search'
    | '/_main/'
    | '/_docs/docs/$'
    | '/_docs/docs/'
    | '/_admin/admin/core/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DocsSearchRoute: typeof DocsSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/search': {
      id: '/docs/search'
      path: '/docs/search'
      fullPath: '/docs/search'
      preLoaderRoute: typeof DocsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/docs/': {
      id: '/_docs/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsDocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/docs/$': {
      id: '/_docs/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsDocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_admin/admin/core/': {
      id: '/_admin/admin/core/'
      path: '/admin/core'
      fullPath: '/admin/core/'
      preLoaderRoute: typeof AdminAdminCoreIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminCoreIndexRoute: typeof AdminAdminCoreIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminCoreIndexRoute: AdminAdminCoreIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DocsRouteChildren {
  DocsDocsSplatRoute: typeof DocsDocsSplatRoute
  DocsDocsIndexRoute: typeof DocsDocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDocsSplatRoute: DocsDocsSplatRoute,
  DocsDocsIndexRoute: DocsDocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  MainRoute: MainRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  ApiSplatRoute: ApiSplatRoute,
  DocsSearchRoute: DocsSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
