import { getTableName } from "drizzle-orm";
import { getTableConfig } from "drizzle-orm/pg-core";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { EXAMPLE_MIGRATIONS } from "@/const";

import { example_articles } from "./articles";
import { example_categories } from "./categories";

const articles = getTableConfig(example_articles);
const categories = getTableConfig(example_categories);

const indexNames = (config: typeof articles) =>
  config.indexes.map(item => item.config.name);

// Drizzle types an index name as optional; the engine always sets one.
const byName = (a: string | undefined, b: string | undefined) =>
  (a ?? "").localeCompare(b ?? "");

const uniqueIndexNames = (config: typeof articles) =>
  config.indexes
    .filter(item => item.config.unique)
    .map(item => item.config.name);

/**
 * The committed migrations, concatenated in apply order. Read as text on
 * purpose: this is the artefact a fresh database actually runs, so asserting on
 * the Drizzle objects alone would not prove the DDL landed.
 */
const migration = EXAMPLE_MIGRATIONS.map(file =>
  readFileSync(
    resolve(
      dirname(fileURLToPath(import.meta.url)),
      "../../../../apps/docs/migrations",
      file,
    ),
    "utf8",
  ),
).join("\n");

describe("example_articles", () => {
  it("is a real table with the expected name", () => {
    expect(getTableName(example_articles)).toBe("example_articles");
  });

  it("enables row level security", () => {
    expect(articles.enableRLS).toBe(true);
  });

  it("exercises every field kind", () => {
    const types = Object.fromEntries(
      articles.columns.map(column => [column.name, column.getSQLType()]),
    );

    expect(types).toMatchObject({
      author: "integer", // user
      category: "integer", // relation
      code: "varchar(100)", // text, unique
      excerpt: "text", // textarea
      featured: "boolean",
      slug: "varchar(160)", // slug
      title: "varchar(200)", // text
      views: "integer", // number
    });
  });

  it("makes the slug column NOT NULL with no default", () => {
    const slug = articles.columns.find(column => column.name === "slug");

    // A row nobody can address by URL is not worth allowing, and there is no
    // sensible default URL to fall back on.
    expect(slug?.notNull).toBe(true);
    expect(slug?.default).toBeUndefined();
  });

  it("generates the publication columns instead of declaring them", () => {
    const columns = Object.fromEntries(
      articles.columns.map(column => [column.name, column]),
    );

    expect(columns.status.getSQLType()).toBe("varchar(32)");
    expect(columns.status.notNull).toBe(true);
    expect(columns.status.default).toBe("draft");

    // "First published at", not "is published" - `unpublish` leaves it set.
    expect(columns.publishedAt.getSQLType()).toBe("timestamp");
    expect(columns.publishedAt.notNull).toBe(false);
    expect(columns.publishedAt.default).toBeUndefined();
  });

  it("gives the unique text field and the slug a unique index", () => {
    // The slug needs no `unique: true` - a URL segment is unique by definition.
    expect([...uniqueIndexNames(articles)].sort(byName)).toEqual([
      "example_articles_code_key",
      "example_articles_slug_key",
    ]);
  });

  it("indexes the foreign keys, the timestamps, the declared composite and publication", () => {
    expect([...indexNames(articles)].sort(byName)).toEqual([
      "example_articles_author_idx",
      "example_articles_category_idx",
      "example_articles_code_key",
      "example_articles_created_at_idx",
      "example_articles_slug_key",
      "example_articles_status_created_at_idx",
      // Generated by `publication`: serves the published predicate and the
      // default "newest published first" ordering in one.
      "example_articles_status_published_at_idx",
      "example_articles_updated_at_idx",
    ]);
  });

  it("points its references at the right tables", () => {
    const references = articles.foreignKeys.map(key => {
      const reference = key.reference();

      return {
        column: reference.columns[0].name,
        onDelete: key.onDelete,
        table: getTableName(reference.foreignTable),
      };
    });

    expect(references).toContainEqual({
      column: "author",
      onDelete: "set null",
      table: "core_users",
    });
    expect(references).toContainEqual({
      column: "category",
      onDelete: "restrict",
      table: "example_categories",
    });
  });
});

describe("example_categories", () => {
  it("is a real table with row level security", () => {
    expect(getTableName(example_categories)).toBe("example_categories");
    expect(categories.enableRLS).toBe(true);
  });

  it("has no unique indexes of its own", () => {
    expect(uniqueIndexNames(categories)).toEqual([]);
  });
});

describe("the generated migration", () => {
  it("creates both tables with row level security", () => {
    expect(migration).toContain('CREATE TABLE "example_articles"');
    expect(migration).toContain('CREATE TABLE "example_categories"');
    expect(migration).toContain(
      'ALTER TABLE "example_articles" ENABLE ROW LEVEL SECURITY',
    );
  });

  it("creates the unique index for `field.text({ unique: true })`", () => {
    expect(migration).toContain(
      'CREATE UNIQUE INDEX "example_articles_code_key" ON "example_articles" USING btree ("code")',
    );
  });

  it("creates exactly one index per resolved definition entry", () => {
    const created = [
      ...migration.matchAll(/CREATE (?:UNIQUE )?INDEX "([^"]+)"/g),
    ]
      .map(match => match[1])
      .filter(name => name.startsWith("example_"));

    expect([...created].sort(byName)).toEqual(
      [...indexNames(articles), ...indexNames(categories)].sort(byName),
    );
  });

  it("names the composite index in snake_case", () => {
    expect(migration).toContain('"example_articles_status_created_at_idx"');
  });

  describe("the slug column", () => {
    it("arrives nullable, so an existing table can be backfilled", () => {
      // `ADD COLUMN ... NOT NULL` with no default fails outright on a populated
      // table. The generated one-liner has to be split by hand.
      expect(migration).toContain(
        'ALTER TABLE "example_articles" ADD COLUMN "slug" varchar(160);',
      );
      expect(migration).not.toContain(
        'ADD COLUMN "slug" varchar(160) NOT NULL',
      );
    });

    it("backfills from the title before tightening the column", () => {
      const backfill = migration.indexOf('SET "slug" = NULLIF');
      const notNull = migration.indexOf('ALTER COLUMN "slug" SET NOT NULL');
      const unique = migration.indexOf('"example_articles_slug_key"');

      expect(backfill).toBeGreaterThan(-1);
      expect(notNull).toBeGreaterThan(backfill);
      expect(unique).toBeGreaterThan(backfill);
    });

    it("disambiguates with the row id rather than a placeholder", () => {
      // No "untitled-1" and no random suffix: every row keeps whatever its
      // title gave it, and only the collisions gain the id.
      expect(migration).toContain(`a."id"`);
      expect(migration).not.toMatch(/random\(|gen_random_uuid\(/);
    });

    it("truncates the base before appending the id", () => {
      // A title can already fill `varchar(160)`, so appending `-<id>` to the
      // whole thing would overflow the column and fail the migration on exactly
      // the rows the duplicate pass exists to rescue.
      expect(migration).toContain(
        `left(coalesce(a."slug", ''), 160 - 1 - length(a."id"::text))`,
      );
    });
  });

  it("narrows the status column and normalises the values it dropped", () => {
    expect(migration).toContain(
      `ALTER TABLE "example_articles" ALTER COLUMN "status" SET DATA TYPE varchar(32)`,
    );
    // `archived` is not a generated status; those rows have to go somewhere.
    expect(migration).toContain(
      `UPDATE "example_articles" SET "status" = 'draft' WHERE "status" NOT IN ('draft', 'published')`,
    );
  });

  it("wires the foreign keys with the declared onDelete behaviour", () => {
    expect(migration).toContain(
      'REFERENCES "public"."core_users"("id") ON DELETE set null',
    );
    expect(migration).toContain(
      'REFERENCES "public"."example_categories"("id") ON DELETE restrict',
    );
  });
});
