/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by `vitnode build` and `vitnode dev` from one input: this
// plugin's own `src/config.api.ts`.
//
// It is what lets the plugin's own pages call `fetcher({ plugin: <this id> })`
// before any application has installed it. An application registers the plugins
// it configured from its generated `src/api-registry.gen.ts`, and this file is
// kept out of the published package so that a plugin a project merely installed
// cannot put its routes into that project's registry.

import type { VitNodeApiPlugin } from '../src/config.api'

declare module '@vitnode/core/lib/fetcher/registry' {
  interface ApiPluginRegistry {
    '@vitnode/blog': VitNodeApiPlugin
  }
}

export type { ApiPluginRegistry } from '@vitnode/core/lib/fetcher/registry'
