import { pathToFileURL } from "node:url";

/**
 * How a build re-reads a module Node has already imported.
 *
 * Node's ESM loader caches by URL, permanently and with no eviction API. There
 * is no `delete require.cache` for it and no supported way to drop one entry, so
 * the only way to get the current bytes of a file that has already been imported
 * is to ask for a *different URL* that resolves to the same file - which a query
 * string does.
 *
 * That matters here because the dev server had a watcher that worked and a
 * regeneration that could not: edit a plugin's route manifest, the watcher
 * fires, the pass runs, and `import()` of the same URL hands back the module
 * Node parsed when the server started. The generated files were then rewritten
 * from stale declarations - or, more often, not rewritten at all, because the
 * bytes had not changed.
 *
 * ## Why a fingerprint and not a counter or a clock
 *
 * `?v=${Date.now()}` would also bust the cache, and it is the wrong answer three
 * times over:
 *
 * 1. **It leaks.** Every pass over every manifest mints a URL Node will hold for
 *    the life of the process, whether the file changed or not. A dev session
 *    that regenerates a few hundred times accumulates a few hundred copies of
 *    every plugin's manifest, each with its own module record.
 * 2. **It is not reproducible.** Two builds of the same tree ask for different
 *    URLs, which makes "same configuration, same bytes" a property of when the
 *    build ran.
 * 3. **It hides the question.** A version read *off the file* is a statement
 *    about the file; a clock is a statement about nothing.
 *
 * A fingerprint keeps the property that matters - it changes when the file
 * changes - and adds the two a clock cannot: an untouched manifest keeps its
 * existing cache entry across regenerations rather than leaking a new one, and
 * the URL is a function of the tree rather than of the moment.
 *
 * None of this reaches the generated output. The generated bytes are a function
 * of the declarations alone, so the browser never sees a version, a query string
 * or a timestamp.
 */

/** The fields of a `Stats` this needs, so a caller may pass a `Stats` or a test may not. */
export interface ModuleFileVersionSource {
  mtimeMs: number;
  size: number;
}

/**
 * A file's identity, as far as "has this changed" goes.
 *
 * Size *and* mtime, because mtime alone is only as fine-grained as the
 * filesystem underneath. APFS and ext4 report sub-millisecond, but a Docker bind
 * mount can round to the second, and two rebuilds inside one second is an
 * ordinary thing for a watcher to cause. Two versions of a manifest that share a
 * timestamp *and* a byte length would still collide; that is a much narrower
 * hole than the one this closes, and shutting it completely would mean hashing
 * every manifest on every pass.
 *
 * Pure, and deliberately so: the same stats always produce the same tag, which
 * is the property that separates this from a clock and the one the test asserts.
 */
export const moduleFileVersion = ({
  mtimeMs,
  size,
}: ModuleFileVersionSource): string => `${size}-${mtimeMs}`;

/**
 * A file's URL, carrying a version Node's module cache will treat as new when
 * the file changes and as familiar when it has not.
 *
 * `searchParams.set` rather than string concatenation, so a path that already
 * contains a `?` or a `#` - or one whose name needs percent-encoding - is
 * handled by the URL parser instead of by this function.
 */
export const versionedModuleUrl = (
  file: string,
  version: ModuleFileVersionSource,
): string => {
  const url = pathToFileURL(file);

  url.searchParams.set("v", moduleFileVersion(version));

  return url.href;
};
