import type { ResolvedContentRegistryModule } from "./types.js";

import { toSingleQuotedLiteral } from "../plugin-routes/resolve.js";

/** Where the generated file imports its type from. */
const TYPES_SPECIFIER = "@vitnode/core/lib/plugin";

/**
 * The generated file's header.
 *
 * `eslint-disable` and the "do not format" line are not decoration: the file is
 * rewritten on every build, so anything a linter or a formatter changes in it is
 * lost.
 */
const HEADER = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
// \`vite dev\` and \`vite build\`, from one input: the plugins configured in
// \`src/vitnode.config.ts\`, and which of them export an \`admin/content\` module.
//
// Same plugin configuration in, same bytes out: the entries are sorted by
// plugin id.

import type { ContentFrontendPluginSource } from '${TYPES_SPECIFIER}'
`;

/**
 * The doc comment on the export, written into the generated file.
 *
 * Long, and on purpose: this is the module somebody opens when a content type's
 * AdminCP screen is missing, and the answer - "that plugin does not export
 * `admin/content`" - is not guessable from an array of two entries.
 */
const BODY_DOC = `
/**
 * Every configured plugin's Content Engine frontend registration.
 *
 * A plugin appears here by exporting \`admin/content\`, and a plugin that does
 * not contributes no content types to the AdminCP. That is not an error - most
 * plugins register none - and it is decided at build time rather than
 * discovered in a browser: the specifiers below are literal, so a bundler
 * resolves them and nothing is reached through a computed string.
 *
 * This carries more than \`admin-nav.gen.ts\` and less than
 * \`vitnode.config.ts\`. Navigation needs ids, hrefs, permissions and icons; a
 * content *screen* needs those plus the components that replace a generated
 * input, a generated table cell and a generated form layout. Neither needs the
 * server config, which carries message loaders and API wiring a browser bundle
 * has no business holding.
 *
 * Nothing is copied and nothing is serialised: React components cannot cross a
 * JSON boundary, so the registrations stay compiled in each plugin's own
 * \`dist\` and arrive through a specifier a bundler resolved.
 *
 * The registry built from this is validated by \`@vitnode/core\` -
 * \`buildContentFrontendRegistry\` runs the same \`validateContentTypes\` the
 * API side runs, so two plugins claiming one \`admin.path\` fail loudly here
 * rather than giving one of them a screen and the other nothing.
 */
export const pluginContentTypes`;

const importLines = (modules: ResolvedContentRegistryModule[]): string =>
  modules
    .map(
      (module, index) =>
        `import { adminContent as adminContent${index} } from ${toSingleQuotedLiteral(module.specifier)}`,
    )
    .join("\n");

/**
 * The source of an app's Content Engine frontend registry.
 *
 * A string rather than a file, so the one part of this that has to be exactly
 * reproducible is a pure function of its input and can be asserted byte for
 * byte. Writing it - and deciding whether it changed - belongs to the build tool
 * that has a filesystem.
 *
 * Sorted by plugin id here rather than trusted to arrive that way, so "same
 * configuration, same bytes" is a property of this function rather than a
 * promise about how it is called. The aliases are positional for the same
 * reason: a plugin id is not an identifier, and deriving one would mean two
 * plugins whose ids differ only in punctuation colliding silently.
 */
export const generateContentRegistrySource = (
  modules: readonly ResolvedContentRegistryModule[],
): string => {
  const sorted = [...modules].sort((a, b) =>
    a.pluginId === b.pluginId ? 0 : a.pluginId < b.pluginId ? -1 : 1,
  );

  if (sorted.length === 0) {
    return `${HEADER}${BODY_DOC}: ContentFrontendPluginSource[] = []\n`;
  }

  const entries = sorted
    .map((module, index) => `  adminContent${index}, // ${module.pluginId}`)
    .join("\n");

  return `${HEADER}\n${importLines(sorted)}\n${BODY_DOC} = [\n${entries}\n] satisfies ContentFrontendPluginSource[]\n`;
};
