// @vitest-environment node
import { describe, expect, it } from "vitest";

import type { ResolvedPackageMessagesModule } from "./types.js";

import { CORE_LOCALE_FILES } from "./core.js";
import { generatePackageMessagesSource } from "./generate.js";

const blog: ResolvedPackageMessagesModule = {
  localeFiles: {
    en: "@acme/blog/locales/en.json",
    pl: "@acme/blog/locales/pl.json",
  },
  pluginId: "@acme/blog",
};

const docs: ResolvedPackageMessagesModule = {
  localeFiles: { en: "@acme/docs/i18n/en.json" },
  pluginId: "@acme/docs",
};

/** The generated object literal, without the header that describes it. */
const mapLiteral = (source: string): string =>
  source.slice(source.indexOf("packageMessages"));

/** The locale codes one package's entry declares, in the order written. */
const localesOf = (source: string, pluginId: string): string[] => {
  const at = source.indexOf(`'${pluginId}': {`);
  const block = source.slice(at, source.indexOf("\n  },", at));

  return [...block.matchAll(/\/([A-Za-z-]+)\.json'\)/g)].map(match => match[1]);
};

describe("generatePackageMessagesSource", () => {
  it("tells whoever opens it not to edit it", () => {
    const source = generatePackageMessagesSource([]);

    expect(source.startsWith("/* eslint-disable */")).toBe(true);
    expect(source).toContain("generated by VitNode");
  });

  /**
   * The reason this file is generated at all: a bundler follows a literal and
   * nothing else, so every specifier has to be spelled out where it is written.
   */
  it("writes each locale file as a literal import specifier", () => {
    const source = generatePackageMessagesSource([blog]);

    expect(source).toContain(
      "en: async () => await import('@acme/blog/locales/en.json'),",
    );
    expect(source).toContain(
      "pl: async () => await import('@acme/blog/locales/pl.json'),",
    );
  });

  it("builds no specifier out of a variable", () => {
    const source = generatePackageMessagesSource([blog, docs]);

    for (const specifier of [...source.matchAll(/await import\((.*?)\)/g)]) {
      expect(specifier[1]).toMatch(/^'[^'+`${}]+\.json'$/);
    }
    // The literal itself, rather than the header - which says all of this in
    // prose and quotes the concatenation it exists to rule out.
    expect(mapLiteral(source)).not.toMatch(/[+`]/);
  });

  it("keeps every loader lazy, so no JSON reaches the entry chunk", () => {
    const source = generatePackageMessagesSource([blog]);

    expect(source).not.toMatch(/^import .*\.json/m);
    expect(source.match(/await import\(/g)).toHaveLength(
      Object.keys(CORE_LOCALE_FILES).length +
        Object.keys(blog.localeFiles).length,
    );
  });

  it("registers core whether or not anything else is configured", () => {
    for (const modules of [[], [blog]]) {
      const source = generatePackageMessagesSource(modules);

      expect(source).toContain("'@vitnode/core': {");
      expect(source).toContain(
        "en: async () => await import('@vitnode/core/locales/en.json'),",
      );
    }
  });

  it("emits only the plugins it was given", () => {
    const source = generatePackageMessagesSource([docs]);

    expect(source).toContain("'@acme/docs'");
    expect(source).not.toContain("@acme/blog");
  });

  it("declares the type the server config consumes", () => {
    const source = generatePackageMessagesSource([]);

    expect(source).toContain(
      "import type { LocaleMessagesMap } from '@vitnode/core/lib/i18n/types'",
    );
    expect(source).toContain(
      "export const packageMessages: Record<string, LocaleMessagesMap> = {",
    );
  });

  /**
   * Sorted here rather than trusted to arrive sorted, so the ordering is a
   * property of the function instead of a promise about how it is called.
   */
  it("is the same bytes whichever order the plugins arrive in", () => {
    expect(generatePackageMessagesSource([blog, docs])).toBe(
      generatePackageMessagesSource([docs, blog]),
    );
  });

  it("orders packages by id, with core first", () => {
    const source = generatePackageMessagesSource([docs, blog]);
    const at = (id: string) => source.indexOf(`'${id}'`);

    expect(at("@vitnode/core")).toBeLessThan(at("@acme/blog"));
    expect(at("@acme/blog")).toBeLessThan(at("@acme/docs"));
  });

  it("orders locales by code, whatever order they were declared in", () => {
    const source = generatePackageMessagesSource([
      {
        localeFiles: {
          pl: "@acme/blog/locales/pl.json",
          de: "@acme/blog/locales/de.json",
          en: "@acme/blog/locales/en.json",
        },
        pluginId: "@acme/blog",
      },
    ]);

    expect(localesOf(source, "@acme/blog")).toEqual(["de", "en", "pl"]);
  });

  it("does not mutate its argument", () => {
    const modules = [docs, blog];

    generatePackageMessagesSource(modules);

    expect(modules.map(module => module.pluginId)).toEqual([
      "@acme/docs",
      "@acme/blog",
    ]);
  });

  /** A locale code is not an identifier once it carries a region. */
  it("quotes a locale code that is not an identifier", () => {
    const source = generatePackageMessagesSource([
      {
        localeFiles: { "pt-BR": "@acme/blog/locales/pt-BR.json" },
        pluginId: "@acme/blog",
      },
    ]);

    expect(source).toContain(
      "'pt-BR': async () => await import('@acme/blog/locales/pt-BR.json'),",
    );
  });

  /**
   * The literal is the whole output, so evaluating it is the one assertion that
   * covers what the string assertions above each cover a piece of: it parses,
   * every key is where it was written, and every value is a function that has
   * not run.
   */
  it("writes an object literal that evaluates to the loaders it describes", () => {
    const source = generatePackageMessagesSource([blog, docs]);
    const literal: unknown = eval(
      `(${source.slice(source.indexOf("> = ") + 4)})`,
    );
    const loaded = literal as Record<string, Record<string, unknown>>;

    expect(Object.keys(loaded)).toEqual([
      "@vitnode/core",
      "@acme/blog",
      "@acme/docs",
    ]);
    expect(Object.keys(loaded["@acme/blog"])).toEqual(["en", "pl"]);
    expect(typeof loaded["@acme/blog"].en).toBe("function");
  });
});
