import type { ResolvedPackageMessagesModule } from "./types.js";

import { toSingleQuotedLiteral } from "../plugin-routes/resolve.js";
import { CORE_LOCALE_FILES, CORE_PLUGIN_ID } from "./core.js";

/** Where the generated file imports its type from. */
const TYPES_SPECIFIER = "@vitnode/core/lib/i18n/types";

const HEADER = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
// \`vite dev\` and \`vite build\`, from one input: the plugins configured in
// \`src/vitnode.config.ts\`, and the \`localeFiles\` each one declares.
//
// Every specifier below is a literal, because that is the only kind a bundler
// can follow: \`import(pkg + '/locales/' + locale + '.json')\` resolves to
// nothing at build time, and a plugin's own locale barrel imports \`./en.json\`
// relative to the plugin's build output rather than to this app.
//
// Each loader stays a dynamic \`import()\`, so a language's JSON is a chunk of
// its own and none of it is in the initial bundle - the server loads the one
// locale a request asked for.
//
// Same plugin configuration in, same bytes out: core first, then the plugins
// sorted by id, and each package's locales sorted by code.

import type { LocaleMessagesMap } from '${TYPES_SPECIFIER}'

export const packageMessages: Record<string, LocaleMessagesMap> = `;

/** Locale codes are quoted only when they are not identifiers (`pt-BR`). */
const IDENTIFIER_PATTERN = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

const localeKey = (code: string): string =>
  IDENTIFIER_PATTERN.test(code) ? code : toSingleQuotedLiteral(code);

const entryFor = ({
  localeFiles,
  pluginId,
}: ResolvedPackageMessagesModule): string => {
  const loaders = Object.keys(localeFiles)
    .sort((a, b) => (a === b ? 0 : a < b ? -1 : 1))
    .map(
      code =>
        `    ${localeKey(code)}: async () => await import(${toSingleQuotedLiteral(localeFiles[code])}),`,
    )
    .join("\n");

  return `  ${toSingleQuotedLiteral(pluginId)}: {\n${loaders}\n  },`;
};

/**
 * The source of an app's package translation registry.
 *
 * A string rather than a file, so the one part of this that has to be exactly
 * reproducible is a pure function of its input and can be asserted byte for
 * byte. Writing it - and deciding whether it changed - belongs to the build tool
 * that has a filesystem.
 *
 * Core's entry is prepended here rather than passed in, because core is not a
 * configured plugin: an app that installs nothing still renders core's own UI,
 * and its translations must not depend on a plugin list. Object key order is not
 * what decides the merge - `buildBundledMessagesSources` reads core first and
 * then walks the configured plugins in order - so this ordering exists purely so
 * that the same configuration writes the same bytes.
 */
export const generatePackageMessagesSource = (
  modules: readonly ResolvedPackageMessagesModule[],
): string => {
  const sorted = [...modules].sort((a, b) =>
    a.pluginId === b.pluginId ? 0 : a.pluginId < b.pluginId ? -1 : 1,
  );

  const entries = [
    { localeFiles: CORE_LOCALE_FILES, pluginId: CORE_PLUGIN_ID },
    ...sorted,
  ]
    .map(entryFor)
    .join("\n");

  return `${HEADER}{\n${entries}\n}\n`;
};
