import type { ResolvedApiPluginModule } from "./types.js";

import { toSingleQuotedLiteral } from "../plugin-routes/resolve.js";

export const API_REGISTRY_SPECIFIER = "@vitnode/core/lib/fetcher/registry";

/** The one type every plugin's `config.api.ts` exports for this file to read. */
export const API_PLUGIN_TYPE = "VitNodeApiPlugin";

const HEADER = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
// \`vite dev\` and \`vite build\`, from one input: the plugins configured in
// \`src/vitnode.config.ts\`, and which of them export a \`config.api\` module.
//
// This is the only place an installed plugin's API is registered, and it is what
// \`fetcher\` resolves a call against. A plugin that augmented the registry from
// inside its own package would put its routes into the registry of every project
// that merely installed it, configured or not.
//
// Every import is \`import type\`, and each names one already-reduced type rather
// than a whole module namespace. A plugin's \`config.api\` reaches its Hono
// handlers, its database and its secrets; naming the type keeps all of that out
// of this graph, and out of the browser bundle.
//
// Same plugin configuration in, same bytes out: the entries are sorted by
// plugin id.
`;

const alias = (index: number): string => `ApiPlugin${index}`;

const importLines = (modules: readonly ResolvedApiPluginModule[]): string =>
  modules
    .map(
      (module, index) =>
        `import type { ${API_PLUGIN_TYPE} as ${alias(index)} } from ${toSingleQuotedLiteral(module.specifier)}`,
    )
    .join("\n");

const entryLines = (modules: readonly ResolvedApiPluginModule[]): string =>
  modules
    .map(
      (module, index) =>
        `    ${toSingleQuotedLiteral(module.pluginId)}: ${alias(index)}`,
    )
    .join("\n");

export const generateApiRegistrySource = (
  modules: readonly ResolvedApiPluginModule[],
): string => {
  const sorted = [...modules].sort((a, b) =>
    a.pluginId === b.pluginId ? 0 : a.pluginId < b.pluginId ? -1 : 1,
  );

  const imports = sorted.length === 0 ? "" : `${importLines(sorted)}\n\n`;
  const entries = sorted.length === 0 ? "" : `${entryLines(sorted)}\n`;

  return `${HEADER}
${imports}declare module ${toSingleQuotedLiteral(API_REGISTRY_SPECIFIER)} {
  interface ApiPluginRegistry {
${entries}  }
}

export type { ApiPluginRegistry } from ${toSingleQuotedLiteral(API_REGISTRY_SPECIFIER)}
`;
};

/**
 * Where `vitnode build` writes a plugin's own registration, relative to its root.
 *
 * A declaration file rather than a `.ts` one: TypeScript emits no output for a
 * `.d.ts` input, so the augmentation type-checks the plugin's own pages without
 * reaching `dist` - and a plugin a project merely installed cannot put its
 * routes into that project's registry.
 */
export const PLUGIN_API_REGISTRY_PATH = "types/api-registry.gen.d.ts";

/** What that file imports, relative to itself. */
export const PLUGIN_API_CONFIG_SPECIFIER = "../src/config.api";

const PLUGIN_HEADER = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by \`vitnode build\` and \`vitnode dev\` from one input: this
// plugin's own \`src/config.api.ts\`.
//
// It is what lets the plugin's own pages call \`fetcher({ plugin: <this id> })\`
// before any application has installed it. An application registers the plugins
// it configured from its generated \`src/api-registry.gen.ts\`, and this file is
// kept out of the published package so that a plugin a project merely installed
// cannot put its routes into that project's registry.
`;

/**
 * A plugin's registration of itself, for its own type-checking only.
 *
 * The same shape {@link generateApiRegistrySource} writes for an application,
 * with one entry and a relative specifier, so a plugin's pages and an app's
 * pages resolve a `fetcher` call against the same declaration.
 */
export const generatePluginApiRegistrySource = (pluginId: string): string =>
  `${PLUGIN_HEADER}
import type { ${API_PLUGIN_TYPE} } from ${toSingleQuotedLiteral(PLUGIN_API_CONFIG_SPECIFIER)}

declare module ${toSingleQuotedLiteral(API_REGISTRY_SPECIFIER)} {
  interface ApiPluginRegistry {
    ${toSingleQuotedLiteral(pluginId)}: ${API_PLUGIN_TYPE}
  }
}

export type { ApiPluginRegistry } from ${toSingleQuotedLiteral(API_REGISTRY_SPECIFIER)}
`;
