import type { ResolvedApiPluginModule } from "./types.js";

import { toSingleQuotedLiteral } from "../plugin-routes/resolve.js";

export const API_REGISTRY_SPECIFIER = "@vitnode/core/lib/fetcher/registry";

const HEADER = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
`;

const importLines = (modules: readonly ResolvedApiPluginModule[]): string =>
  modules
    .map(
      (module, index) =>
        `import type * as apiPlugin${index} from ${toSingleQuotedLiteral(module.specifier)}`,
    )
    .join("\n");

const entryLines = (modules: readonly ResolvedApiPluginModule[]): string =>
  modules
    .map(
      (module, index) =>
        `    ${toSingleQuotedLiteral(module.pluginId)}: typeof apiPlugin${index}`,
    )
    .join("\n");

export const generateApiRegistrySource = (
  modules: readonly ResolvedApiPluginModule[],
): string => {
  const sorted = [...modules].sort((a, b) =>
    a.pluginId === b.pluginId ? 0 : a.pluginId < b.pluginId ? -1 : 1,
  );

  const imports = sorted.length === 0 ? "" : `${importLines(sorted)}\n\n`;
  const entries = sorted.length === 0 ? "" : `${entryLines(sorted)}\n`;

  return `${HEADER}
${imports}declare module ${toSingleQuotedLiteral(API_REGISTRY_SPECIFIER)} {
  interface ApiPluginRegistry {
${entries}  }
}

export type { ApiPluginRegistry } from ${toSingleQuotedLiteral(API_REGISTRY_SPECIFIER)}
`;
};
