import { toSingleQuotedLiteral } from "../plugin-routes/resolve.js";

export interface ResolvedContentModule {
  pluginId: string;
  specifier: string;
}

const HEADER = `/* oxlint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
// \`vite dev\` and \`vite build\`: one import per configured plugin whose
// \`content\` module this build resolved, loaded and checked against the app's
// page routes. Pass it to \`buildApiConfig({ contentModules })\` so the API
// refuses public content URLs this build never saw.
//
// Same plugin configuration in, same bytes out: the entries are sorted by
// plugin id.
`;

const alias = (index: number): string => `contentModule${index}`;

export const generateContentModulesSource = (
  modules: readonly ResolvedContentModule[],
): string => {
  const sorted = [...modules].sort((a, b) =>
    a.pluginId === b.pluginId ? 0 : a.pluginId < b.pluginId ? -1 : 1,
  );

  const imports = sorted
    .map(
      (module, index) =>
        `import * as ${alias(index)} from ${toSingleQuotedLiteral(module.specifier)}\n`,
    )
    .join("");
  const entries = sorted
    .map(
      (module, index) =>
        `  ${toSingleQuotedLiteral(module.pluginId)}: ${alias(index)},\n`,
    )
    .join("");

  return `${HEADER}
${imports}${imports === "" ? "" : "\n"}export const contentModules: Readonly<Record<string, unknown>> = {
${entries}}
`;
};
