import adminContentCreateDark from '#/site/home/assets/admin-content-create-dark.png'
import adminContentCreateLight from '#/site/home/assets/admin-content-create-light.png'
import adminDashboardDark from '#/site/home/assets/admin-dashboard-dark.png'
import adminDashboardLight from '#/site/home/assets/admin-dashboard-light.png'
import adminIntegrationsDark from '#/site/home/assets/admin-integrations-dark.png'
import adminIntegrationsLight from '#/site/home/assets/admin-integrations-light.png'
import adminRolesDark from '#/site/home/assets/admin-roles-dark.png'
import adminRolesLight from '#/site/home/assets/admin-roles-light.png'
import publicLoginDark from '#/site/home/assets/public-login-dark.png'
import publicLoginLight from '#/site/home/assets/public-login-light.png'

export interface Screen {
  alt: string
  dark: string
  light: string
  title: string
  url: string
}

export const SCREEN_SIZE = { height: 866, width: 1600 }

export const SCREENS = {
  contentEditor: {
    alt: 'The Create Article screen generated by the Content Engine, with title, friendly URL and rich text fields that each have a language selector, plus cover image and settings panels.',
    dark: adminContentCreateDark,
    light: adminContentCreateLight,
    title: 'Content editor',
    url: 'yourcommunity.com/admin/content/blog/articles/create',
  },
  dashboard: {
    alt: 'The AdminCP dashboard with a sidebar listing Core, Blog and Example plugin sections, a private notes widget and a send-notification widget.',
    dark: adminDashboardDark,
    light: adminDashboardLight,
    title: 'Dashboard',
    url: 'yourcommunity.com/admin',
  },
  integrations: {
    alt: 'The Integrations screen showing status cards for AI, WebSocket, Redis, email, storage, cron jobs, content preview and queue tasks.',
    dark: adminIntegrationsDark,
    light: adminIntegrationsLight,
    title: 'Integrations',
    url: 'yourcommunity.com/admin/core/system/integrations',
  },
  login: {
    alt: 'The public sign-in page with email and password fields and Discord, Google and Facebook buttons.',
    dark: publicLoginDark,
    light: publicLoginLight,
    title: 'Sign-in page',
    url: 'yourcommunity.com/login',
  },
  roles: {
    alt: 'The Roles screen listing Moderator, Administrator, Member and Guest roles with member counts and update dates.',
    dark: adminRolesDark,
    light: adminRolesLight,
    title: 'Roles',
    url: 'yourcommunity.com/admin/core/users/roles',
  },
} satisfies Record<string, Screen>

export type ScreenKey = keyof typeof SCREENS
