import browserCollections from 'collections/browser'

import type { DocsArticleMeta } from './article'

import { DocsArticle } from './article'
import { mdxComponents } from './mdx-components'

/**
 * The browser's half of the MDX split: a page's *path* in, its rendered page
 * out.
 *
 * `collections/browser` is `.source/browser.ts`, generated by
 * `fumadocs-mdx/vite`: a record of `() => import("…/dev/index.mdx")` thunks and
 * nothing else. Importing it costs the thunks, not the documents - every body is
 * its own chunk, fetched when a reader asks for that page.
 *
 * `createClientLoader` is Fumadocs' own API for this, and the reason nothing
 * here serializes a component. `preload(path)` starts the import (the route's
 * loader awaits it, so the first paint already has the body) and
 * `useContent(path, props)` renders whatever it resolved.
 *
 * The loaded module carries `toc` as well as the component, which is what makes
 * the table of contents a prop rather than loader data - see `./article`.
 *
 * `id` is not optional in practice, whatever its default says. TanStack Start's
 * code splitter can duplicate this module into more than one chunk - a route's
 * `component` and its `notFoundComponent` are split separately - and two client
 * loaders with no shared id keep two caches, so a body preloaded by the loader
 * would be fetched a second time by the component. The id makes them one.
 */
export const docsClientLoader = browserCollections.docs.createClientLoader({
  id: 'vitnode-docs',
  component: ({ default: MDX, toc }, props: DocsArticleMeta) => (
    <DocsArticle {...props} toc={toc}>
      <MDX components={mdxComponents} />
    </DocsArticle>
  ),
})
