import type { Metadata } from "next/dist/types";

import { setRequestLocale } from "next-intl/server";
import type React from "react";
import { I18nProvider } from "@/components/i18n-provider";
import type { VitNodeConfig } from "@/vitnode.config";

import { RootProvider } from "./provider";

export interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{
    locale: string;
  }>;
}

export const generateMetadataRootLayout = ({
  metadata: { title, shortTitle },
}: VitNodeConfig): Metadata => {
  return {
    title: {
      default: title,
      template: `%s - ${shortTitle ?? title}`,
    },
    description: "Generated by create next app",
  };
};

export const RootLayout = async ({
  children,
  params,
  config,
}: RootLayoutProps & {
  config: VitNodeConfig;
}) => {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <I18nProvider namespaces={[]}>
      <RootProvider debug={config.debug} theme={config.theme}>
        {children}
      </RootProvider>
    </I18nProvider>
  );
};
