import type { VitNodeConfig } from '@/vitnode.config';
import type { Metadata } from 'next/dist/types';

import { I18nProvider } from '@/components/i18n-provider';
import { setRequestLocale } from 'next-intl/server';
import React from 'react';

import { RootProvider } from './provider';

export interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{
    locale: string;
  }>;
}

export const generateMetadataRootLayout = ({
  metadata: { title, shortTitle },
}: VitNodeConfig): Metadata => {
  return {
    title: {
      default: title,
      template: `%s - ${shortTitle ?? title}`,
    },
    description: 'Generated by create next app',
  };
};

export const RootLayout = async ({
  children,
  className,
  params,
  head,
  config,
}: RootLayoutProps & {
  className?: string;
  config: VitNodeConfig;
  head?: React.ReactNode;
}) => {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      {head && <head>{head}</head>}
      <body className={className}>
        <I18nProvider namespaces={[]}>
          <RootProvider debug={config.debug} theme={config.theme}>
            {children}
          </RootProvider>
        </I18nProvider>
      </body>
    </html>
  );
};
