import type { ResolvedBlocksModule } from "./types.js";

import { toSingleQuotedLiteral } from "../plugin-routes/resolve.js";

const TYPES_SPECIFIER = "@vitnode/core/blocks";

const RUNTIME_SPECIFIER = "@vitnode/core/blocks";

const HEADER = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
// \`vite dev\` and \`vite build\`, from two inputs: \`@vitnode/core\`, whose own
// blocks every VitNode application gets, and the plugins configured in
// \`src/vitnode.config.ts\` that export a \`blocks\` module.
//
// Same plugin configuration in, same bytes out: the entries are sorted by
// plugin id.
//
// \`blocksRegistry\` is the registry itself: import it and hand it to
// \`<ContentRenderer registry={blocksRegistry} />\`. Evaluating this module also
// installs it as this process's default, which is what lets a renderer without
// a \`registry\` prop - and a content type's write validation - find one.
//
// A block definition is metadata plus one public React component. There is no
// editor code in here, and no request is made to build it.

import type { BlockPluginSource } from '${TYPES_SPECIFIER}'

import { createBlockRegistry, setDefaultBlockRegistry } from '${RUNTIME_SPECIFIER}'
`;

const BODY_DOC = `

export const pluginBlocks`;

const REGISTRATION = `
export const blocksRegistry = createBlockRegistry(pluginBlocks)

setDefaultBlockRegistry(blocksRegistry)
`;

const importLines = (modules: ResolvedBlocksModule[]): string =>
  modules
    .map(
      (module, index) =>
        `import { blocks as blocks${index} } from ${toSingleQuotedLiteral(module.specifier)}`,
    )
    .join("\n");

export const generateBlocksRegistrySource = (
  modules: readonly ResolvedBlocksModule[],
): string => {
  const sorted = [...modules].sort((a, b) =>
    a.pluginId === b.pluginId ? 0 : a.pluginId < b.pluginId ? -1 : 1,
  );

  if (sorted.length === 0) {
    return `${HEADER}${BODY_DOC}: BlockPluginSource[] = []\n${REGISTRATION}`;
  }

  const entries = sorted
    .map((module, index) => `  blocks${index}, // ${module.pluginId}`)
    .join("\n");

  return `${HEADER}\n${importLines(sorted)}\n${BODY_DOC} = [\n${entries}\n] satisfies BlockPluginSource[]\n${REGISTRATION}`;
};
