// @vitest-environment node
import { describe, expect, it } from "vitest";

import type { ResolvedBlocksModule } from "./types";

import { generateBlocksRegistrySource } from "./generate";

const core: ResolvedBlocksModule = {
  pluginId: "@vitnode/core",
  specifier: "@vitnode/core/blocks/built-in",
};

const blog: ResolvedBlocksModule = {
  pluginId: "@vitnode/blog",
  specifier: "@vitnode/blog/blocks",
};

describe("generateBlocksRegistrySource", () => {
  it("registers an empty registry when nothing ships blocks", () => {
    const source = generateBlocksRegistrySource([]);

    expect(source).toContain(
      "export const pluginBlocks: BlockPluginSource[] = []",
    );
    expect(source).toContain("setDefaultBlockRegistry(blocksRegistry)");
    expect(source).not.toContain("import { blocks as");
  });

  it("imports each module once, aliased positionally", () => {
    const source = generateBlocksRegistrySource([core, blog]);

    expect(source).toContain(
      "import { blocks as blocks0 } from '@vitnode/blog/blocks'",
    );
    expect(source).toContain(
      "import { blocks as blocks1 } from '@vitnode/core/blocks/built-in'",
    );
  });

  it("produces the same bytes whatever order it is handed", () => {
    expect(generateBlocksRegistrySource([core, blog])).toBe(
      generateBlocksRegistrySource([blog, core]),
    );
  });

  it("names the plugin each entry came from", () => {
    const source = generateBlocksRegistrySource([core, blog]);

    expect(source).toContain("  blocks0, // @vitnode/blog");
    expect(source).toContain("  blocks1, // @vitnode/core");
  });

  it("marks itself generated so nobody edits or formats it", () => {
    expect(generateBlocksRegistrySource([core])).toMatch(
      /^\/\* eslint-disable \*\/\n\n\/\/ This file is generated by VitNode\./,
    );
  });
});
