import { defineConfig } from "oxlint";
import { fileURLToPath } from "node:url";

const resolvePlugin = specifier =>
  fileURLToPath(import.meta.resolve(specifier));

export const ignorePatterns = [
  "dist",
  "oxfmt.config.ts",
  "oxfmt.config.mts",
  "node_modules",
  "oxlint.config.ts",
  "postcss.config.mjs",
  ".turbo",
  "global.d.ts",
  "tsup.config.ts",
  "*.test.tsx",
  "drizzle.config.ts",
  "cli.mjs",
  "**/*.gen.ts",
  "**/*.gen.d.ts",
];

export default defineConfig({
  plugins: ["typescript", "unicorn"],
  jsPlugins: [resolvePlugin("eslint-plugin-perfectionist")],
  categories: {
    correctness: "off",
  },
  env: {
    builtin: true,
  },
  rules: {
    "constructor-super": "error",
    "for-direction": "error",
    "getter-return": "error",
    "no-async-promise-executor": "error",
    "no-case-declarations": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-const-assign": "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-dupe-class-members": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": "error",
    "no-empty-character-class": "error",
    "no-empty-pattern": "error",
    "no-empty-static-block": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "error",
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-import-assign": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-misleading-character-class": "error",
    "no-new-native-nonconstructor": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-obj-calls": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-self-assign": "error",
    "no-setter-return": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-this-before-super": "error",
    "no-unassigned-vars": "error",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "error",
    "no-unused-labels": "error",
    "no-unused-private-class-members": "error",
    "no-unused-vars": [
      "warn",
      {
        ignoreRestSiblings: false,
        caughtErrorsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        argsIgnorePattern: "^_",
      },
    ],
    "no-useless-backreference": "error",
    "no-useless-catch": "error",
    "no-useless-escape": "error",
    "no-with": "error",
    "preserve-caught-error": "error",
    "require-yield": "error",
    "use-isnan": "error",
    "valid-typeof": "error",
    "no-array-constructor": "error",
    "no-unused-expressions": "error",
    "perfectionist/sort-variable-declarations": [
      "error",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-intersection-types": [
      "warn",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-import-attributes": [
      "error",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-export-attributes": [
      "error",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-heritage-clauses": [
      "error",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-array-includes": [
      "warn",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-named-imports": [
      "warn",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-named-exports": [
      "warn",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-object-types": [
      "warn",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-union-types": [
      "warn",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-switch-case": [
      "warn",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-decorators": [
      "warn",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-interfaces": [
      "warn",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-jsx-props": [
      "warn",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-classes": [
      "warn",
      {
        groups: [
          "constructor",
          "static-block",
          "index-signature",
          "static-property",
          ["protected-property", "protected-accessor-property"],
          ["private-property", "private-accessor-property"],
          ["property", "accessor-property"],
          "static-method",
          "protected-method",
          "private-method",
          "method",
          ["get-method", "set-method"],
          "unknown",
        ],
      },
    ],
    "perfectionist/sort-exports": [
      "warn",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-enums": [
      "warn",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-sets": [
      "error",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "perfectionist/sort-maps": [
      "error",
      {
        type: "natural",
        order: "asc",
      },
    ],
    "no-console": "error",
    "no-restricted-imports": [
      "error",
      {
        name: "drizzle-orm/mysql-core",
        message: "Please import from `drizzle-orm/pg-core` instead.",
      },
    ],
    "typescript/adjacent-overload-signatures": "error",
    "typescript/array-type": "error",
    "typescript/ban-tslint-comment": "error",
    "typescript/class-literal-property-style": "error",
    "typescript/consistent-generic-constructors": "error",
    "typescript/consistent-indexed-object-style": "error",
    "typescript/consistent-type-assertions": "error",
    "typescript/consistent-type-definitions": "error",
    "typescript/dot-notation": "error",
    "typescript/no-confusing-non-null-assertion": "error",
    "typescript/no-inferrable-types": "error",
    "typescript/non-nullable-type-assertion-style": "error",
    "typescript/prefer-find": "error",
    "typescript/prefer-for-of": "error",
    "typescript/prefer-function-type": "error",
    "typescript/prefer-includes": "error",
    "typescript/prefer-nullish-coalescing": "error",
    "typescript/prefer-regexp-exec": "error",
    "typescript/prefer-string-starts-ends-with": "error",
    "typescript/await-thenable": "error",
    "typescript/ban-ts-comment": [
      "error",
      {
        minimumDescriptionLength: 10,
      },
    ],
    "typescript/no-array-delete": "error",
    "typescript/no-base-to-string": "error",
    "typescript/no-deprecated": "error",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-duplicate-type-constituents": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-for-in-array": "error",
    "typescript/no-implied-eval": "error",
    "typescript/no-invalid-void-type": "error",
    "typescript/no-meaningless-void-operator": "error",
    "typescript/no-misused-new": "error",
    "typescript/no-mixed-enums": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-redundant-type-constituents": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-this-alias": "error",
    "typescript/no-unnecessary-boolean-literal-compare": "error",
    "typescript/no-unnecessary-template-expression": "error",
    "typescript/no-unnecessary-type-arguments": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unnecessary-type-conversion": "error",
    "typescript/no-unsafe-argument": "error",
    "typescript/no-unsafe-declaration-merging": "error",
    "typescript/no-unsafe-enum-comparison": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-unsafe-unary-minus": "error",
    "typescript/no-useless-default-assignment": "error",
    "typescript/no-wrapper-object-types": "error",
    "typescript/only-throw-error": "error",
    "typescript/prefer-as-const": "error",
    "typescript/prefer-literal-enum-member": "error",
    "typescript/prefer-namespace-keyword": "error",
    "typescript/prefer-promise-reject-errors": "error",
    "typescript/prefer-reduce-type-parameter": "error",
    "typescript/prefer-return-this-type": "error",
    "typescript/related-getter-setter-pairs": "error",
    "typescript/require-await": "error",
    "typescript/restrict-plus-operands": [
      "error",
      {
        allowAny: false,
        allowBoolean: false,
        allowNullish: false,
        allowNumberAndString: false,
        allowRegExp: false,
      },
    ],
    "typescript/return-await": ["error", "error-handling-correctness-only"],
    "typescript/triple-slash-reference": "error",
    "typescript/unified-signatures": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",
    "typescript/consistent-type-imports": "error",
    "typescript/prefer-readonly": "warn",
    "typescript/require-array-sort-compare": "error",
    "typescript/promise-function-async": "error",
    "typescript/consistent-type-exports": "error",
    "typescript/no-unnecessary-qualifier": "error",
    "typescript/no-useless-empty-export": "error",
    "typescript/method-signature-style": "warn",
    "perfectionist/sort-imports": [
      "warn",
      {
        type: "natural",
        order: "asc",
      },
    ],
  },
  overrides: [
    {
      files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
      rules: {
        "constructor-super": "off",
        "getter-return": "off",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-dupe-class-members": "off",
        "no-dupe-keys": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls": "off",
        "no-redeclare": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-unreachable": "off",
        "no-unsafe-negation": "off",
        "no-var": "error",
        "no-with": "off",
        "prefer-const": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
      },
    },
    {
      files: ["**/src/routes.ts", "**/src/routes.tsx"],
      rules: {
        "typescript/promise-function-async": "off",
      },
    },
  ],
});
