export {
  AREA_ALIGN_CLASSES,
  AREA_COLUMN_CLASSES,
  AREA_GRID_CLASS,
  AREA_JUSTIFY_CLASSES,
  areaChildren,
  areaLayoutClassNames,
  areaLayoutStyle,
  areaLayoutWithDefaults,
  areaLikeId,
  areaMarginStyle,
  areaSpacing,
  contentNodeBlocks,
  contentNodeId,
  contentNodeKey,
  createAreaInstance,
  DEFAULT_AREA_LAYOUT,
  isAreaAlign,
  isAreaColumns,
  isAreaJustify,
  isAreaLayout,
  isAreaLike,
  isAreaSpacing,
  isBlockAreaInstance,
  isContentNode,
  isLegacyAreaSpacing,
  isStoredAreaSpacing,
} from "./area";
export type { AreaSpacingStyle } from "./area";
export {
  assertBlockFields,
  BLOCK_FIELD_KINDS,
  blockFieldKindRefusal,
  isBlockFieldKind,
} from "./capabilities";
export type { BlockFieldKind } from "./capabilities";
export {
  AREA_ALIGNS,
  AREA_CHILDREN_DEFAULT_MAX,
  AREA_COLUMNS,
  AREA_DEFAULT_ALIGN,
  AREA_DEFAULT_COLUMNS,
  AREA_DEFAULT_GAP,
  AREA_DEFAULT_JUSTIFY,
  AREA_DEFAULT_MARGIN,
  AREA_JUSTIFIES,
  AREA_LEGACY_SPACING,
  AREA_LEGACY_SPACINGS,
  AREA_SPACING_MAX,
  AREA_SPACING_MIN,
  BLOCK_ID_MAX_LENGTH,
  BLOCK_INSTANCE_ID_MAX_LENGTH,
  BLOCK_INSTANCE_ID_PATTERN,
  BLOCK_NAME_PATTERN,
  BLOCK_NAMESPACE_PATTERN,
  BLOCK_NAMESPACE_SEPARATOR,
  BLOCK_VARIANT_ID_MAX_LENGTH,
  BLOCK_VARIANT_PATTERN,
  BLOCK_WILDCARD,
  CONTENT_AREA_KIND,
  CONTENT_BLOCKS_ABSOLUTE_MAX,
  CONTENT_BLOCKS_DEFAULT_MAX,
  CONTENT_ZONE_ALLOWED_ATTRIBUTE,
  CONTENT_ZONE_ATTRIBUTE,
  CONTENT_ZONE_ID_MAX_LENGTH,
  CONTENT_ZONE_ID_PATTERN,
  CONTENT_ZONE_SEPARATOR,
} from "./const";
export { defineBlock, defineBlock as defineWidget } from "./define";
export type {
  DefineBlockArgs,
  DefineBlockArgs as DefineWidgetArgs,
} from "./define";
export {
  BLOCK_REGISTRY_MISSING,
  BlockError,
  BlockRegistryMissingError,
} from "./errors";
export {
  createBlockInstance,
  createBlockInstanceId,
  createBlockInstance as createWidgetInstance,
  createBlockInstanceId as createWidgetInstanceId,
  isBlockInstance,
  isBlockInstanceId,
  isBlockInstance as isWidgetInstance,
  isBlockInstanceId as isWidgetInstanceId,
} from "./instance";
export {
  assertBlockName,
  assertBlockNamespace,
  assertBlockName as assertWidgetName,
  assertBlockNamespace as assertWidgetNamespace,
  blockNamespaceForPlugin,
  parseBlockId,
  parseBlockId as parseWidgetId,
  qualifiedBlockId,
  qualifiedBlockId as qualifiedWidgetId,
  blockNamespaceForPlugin as widgetNamespaceForPlugin,
} from "./namespace";
export type {
  ParsedBlockId,
  ParsedBlockId as ParsedWidgetId,
} from "./namespace";
export {
  allowedBlocks,
  allowedBlocks as allowedWidgets,
  createBlockRegistry,
  createBlockRegistry as createWidgetRegistry,
  getDefaultBlockRegistry,
  getDefaultBlockRegistry as getDefaultWidgetRegistry,
  isBlockAllowed,
  isBlockAllowed as isWidgetAllowed,
  resolveBlockRegistry,
  resolveBlockRegistry as resolveWidgetRegistry,
  setDefaultBlockRegistry,
  setDefaultBlockRegistry as setDefaultWidgetRegistry,
} from "./registry";
export {
  blockDataIssues,
  blockDataSchema,
  buildBlockDataSchema,
  buildBlockDataSchema as buildWidgetDataSchema,
  parseBlockData,
  parseBlockData as parseWidgetData,
  safeParseBlockData,
  safeParseBlockData as safeParseWidgetData,
  blockDataIssues as widgetDataIssues,
  blockDataSchema as widgetDataSchema,
} from "./schema";
export {
  blockDataShapeIssue,
  blockDataShapeIssue as widgetDataShapeIssue,
} from "./shape";
export type {
  AnyBlockDefinition,
  AnyBlockInstance,
  AnyBlockVariantDefinition,
  AnyBlockDefinition as AnyWidgetDefinition,
  AnyBlockInstance as AnyWidgetInstance,
  AnyBlockVariantDefinition as AnyWidgetVariantDefinition,
  AreaLegacySpacing,
  AreaStoredSpacing,
  BlockAllowedEntry,
  BlockAllowedSpec,
  BlockAreaAlign,
  BlockAreaColumns,
  BlockAreaInstance,
  BlockAreaJustify,
  BlockAreaLayout,
  BlockAreaStoredLayout,
  BlockComponent,
  BlockComponentProps,
  BlockData,
  BlockDefinition,
  BlockFieldMap,
  BlockInstance,
  BlockPluginSource,
  BlockRegistry,
  BlockRenderFallback,
  BlockRenderFallbackProps,
  BlockRenderFallbackReason,
  BlockUnknownData,
  BlockValidationMode,
  BlockVariantDefinition,
  ContentNode,
  ContentZoneDefinition,
  ParsedContentZoneId,
  RegisteredBlock,
  RegisteredBlock as RegisteredWidget,
  BlockAllowedEntry as WidgetAllowedEntry,
  BlockAllowedSpec as WidgetAllowedSpec,
  BlockComponent as WidgetComponent,
  BlockComponentProps as WidgetComponentProps,
  BlockData as WidgetData,
  BlockDefinition as WidgetDefinition,
  BlockFieldMap as WidgetFieldMap,
  BlockInstance as WidgetInstance,
  BlockPluginSource as WidgetPluginSource,
  BlockRegistry as WidgetRegistry,
  BlockRenderFallback as WidgetRenderFallback,
  BlockRenderFallbackProps as WidgetRenderFallbackProps,
  BlockRenderFallbackReason as WidgetRenderFallbackReason,
  BlockUnknownData as WidgetUnknownData,
  BlockValidationMode as WidgetValidationMode,
  BlockVariantDefinition as WidgetVariantDefinition,
} from "./types";
export {
  parseBlockInstances,
  parseContentNodes,
  parseBlockInstances as parseWidgetInstances,
  zodBlockInstances,
  zodContentNode,
  zodContentNodes,
  zodBlockInstances as zodWidgetInstances,
} from "./validate";
export type {
  BlockEnvelope,
  BlockInstanceIssue,
  BlockInstancesResult,
  ContentNodePath,
  BlockEnvelope as WidgetEnvelope,
  BlockInstanceIssue as WidgetInstanceIssue,
  BlockInstancesResult as WidgetInstancesResult,
} from "./validate";
export {
  blockVariantLabel,
  blockVariants,
  findBlockVariant,
  findBlockVariant as findWidgetVariant,
  hasBlockVariants,
  hasBlockVariants as hasWidgetVariants,
  resolveBlockVariant,
  resolveBlockVariant as resolveWidgetVariant,
  blockVariantLabel as widgetVariantLabel,
  blockVariants as widgetVariants,
} from "./variant";
export type {
  BlockVariantResolution,
  BlockVariantResolution as WidgetVariantResolution,
} from "./variant";
export {
  assertContentZoneId,
  contentZoneAttributes,
  formatBlockAllowed,
  formatBlockAllowed as formatWidgetAllowed,
  isContentZoneId,
  parseContentZoneId,
} from "./zone-meta";
