export {
  AREA_ALIGN_CLASSES,
  AREA_COLUMN_CLASSES,
  AREA_GAP_CLASSES,
  AREA_GRID_CLASS,
  AREA_JUSTIFY_CLASSES,
  areaChildren,
  areaLayoutClassNames,
  areaLayoutWithDefaults,
  areaLikeId,
  contentNodeBlocks,
  contentNodeId,
  contentNodeKey,
  createAreaInstance,
  DEFAULT_AREA_LAYOUT,
  isAreaAlign,
  isAreaColumns,
  isAreaGap,
  isAreaJustify,
  isAreaLayout,
  isAreaLike,
  isBlockAreaInstance,
  isContentNode,
} from "./area";
export {
  assertBlockFields,
  BLOCK_FIELD_KINDS,
  blockFieldKindRefusal,
  isBlockFieldKind,
} from "./capabilities";
export type { BlockFieldKind } from "./capabilities";
export {
  AREA_ALIGNS,
  AREA_CHILDREN_DEFAULT_MAX,
  AREA_COLUMNS,
  AREA_DEFAULT_ALIGN,
  AREA_DEFAULT_COLUMNS,
  AREA_DEFAULT_GAP,
  AREA_DEFAULT_JUSTIFY,
  AREA_GAPS,
  AREA_JUSTIFIES,
  BLOCK_ID_MAX_LENGTH,
  BLOCK_INSTANCE_ID_MAX_LENGTH,
  BLOCK_INSTANCE_ID_PATTERN,
  BLOCK_NAME_PATTERN,
  BLOCK_NAMESPACE_PATTERN,
  BLOCK_NAMESPACE_SEPARATOR,
  BLOCK_VARIANT_ID_MAX_LENGTH,
  BLOCK_VARIANT_PATTERN,
  BLOCK_WILDCARD,
  CONTENT_AREA_KIND,
  CONTENT_BLOCKS_ABSOLUTE_MAX,
  CONTENT_BLOCKS_DEFAULT_MAX,
  CONTENT_ZONE_ALLOWED_ATTRIBUTE,
  CONTENT_ZONE_ATTRIBUTE,
  CONTENT_ZONE_ID_MAX_LENGTH,
  CONTENT_ZONE_ID_PATTERN,
  CONTENT_ZONE_SEPARATOR,
} from "./const";
export { defineBlock, defineBlock as defineWidget } from "./define";
export type {
  DefineBlockArgs,
  DefineBlockArgs as DefineWidgetArgs,
} from "./define";
export {
  BLOCK_REGISTRY_MISSING,
  BlockError,
  BlockRegistryMissingError,
} from "./errors";
export {
  createBlockInstance,
  createBlockInstance as createWidgetInstance,
  createBlockInstanceId,
  createBlockInstanceId as createWidgetInstanceId,
  isBlockInstance,
  isBlockInstance as isWidgetInstance,
  isBlockInstanceId,
  isBlockInstanceId as isWidgetInstanceId,
} from "./instance";
export {
  assertBlockName,
  assertBlockName as assertWidgetName,
  assertBlockNamespace,
  assertBlockNamespace as assertWidgetNamespace,
  blockNamespaceForPlugin,
  blockNamespaceForPlugin as widgetNamespaceForPlugin,
  parseBlockId,
  parseBlockId as parseWidgetId,
  qualifiedBlockId,
  qualifiedBlockId as qualifiedWidgetId,
} from "./namespace";
export type {
  ParsedBlockId,
  ParsedBlockId as ParsedWidgetId,
} from "./namespace";
export {
  allowedBlocks,
  allowedBlocks as allowedWidgets,
  createBlockRegistry,
  createBlockRegistry as createWidgetRegistry,
  getDefaultBlockRegistry,
  getDefaultBlockRegistry as getDefaultWidgetRegistry,
  isBlockAllowed,
  isBlockAllowed as isWidgetAllowed,
  resolveBlockRegistry,
  resolveBlockRegistry as resolveWidgetRegistry,
  setDefaultBlockRegistry,
  setDefaultBlockRegistry as setDefaultWidgetRegistry,
} from "./registry";
export {
  blockDataIssues,
  blockDataIssues as widgetDataIssues,
  blockDataSchema,
  blockDataSchema as widgetDataSchema,
  buildBlockDataSchema,
  buildBlockDataSchema as buildWidgetDataSchema,
  parseBlockData,
  parseBlockData as parseWidgetData,
  safeParseBlockData,
  safeParseBlockData as safeParseWidgetData,
} from "./schema";
export {
  blockDataShapeIssue,
  blockDataShapeIssue as widgetDataShapeIssue,
} from "./shape";
export type {
  AnyBlockDefinition,
  AnyBlockDefinition as AnyWidgetDefinition,
  AnyBlockInstance,
  AnyBlockInstance as AnyWidgetInstance,
  AnyBlockVariantDefinition,
  AnyBlockVariantDefinition as AnyWidgetVariantDefinition,
  BlockAllowedEntry,
  BlockAllowedEntry as WidgetAllowedEntry,
  BlockAllowedSpec,
  BlockAllowedSpec as WidgetAllowedSpec,
  BlockAreaAlign,
  BlockAreaColumns,
  BlockAreaGap,
  BlockAreaInstance,
  BlockAreaJustify,
  BlockAreaLayout,
  BlockComponent,
  BlockComponent as WidgetComponent,
  BlockComponentProps,
  BlockComponentProps as WidgetComponentProps,
  BlockData,
  BlockData as WidgetData,
  BlockDefinition,
  BlockDefinition as WidgetDefinition,
  BlockFieldMap,
  BlockFieldMap as WidgetFieldMap,
  BlockInstance,
  BlockInstance as WidgetInstance,
  BlockPluginSource,
  BlockPluginSource as WidgetPluginSource,
  BlockRegistry,
  BlockRegistry as WidgetRegistry,
  BlockRenderFallback,
  BlockRenderFallback as WidgetRenderFallback,
  BlockRenderFallbackProps,
  BlockRenderFallbackProps as WidgetRenderFallbackProps,
  BlockRenderFallbackReason,
  BlockRenderFallbackReason as WidgetRenderFallbackReason,
  BlockUnknownData,
  BlockUnknownData as WidgetUnknownData,
  BlockValidationMode,
  BlockValidationMode as WidgetValidationMode,
  BlockVariantDefinition,
  BlockVariantDefinition as WidgetVariantDefinition,
  ContentNode,
  ContentZoneDefinition,
  ParsedContentZoneId,
  RegisteredBlock,
  RegisteredBlock as RegisteredWidget,
} from "./types";
export {
  parseBlockInstances,
  parseBlockInstances as parseWidgetInstances,
  parseContentNodes,
  zodBlockInstances,
  zodBlockInstances as zodWidgetInstances,
  zodContentNode,
  zodContentNodes,
} from "./validate";
export type {
  BlockEnvelope,
  BlockEnvelope as WidgetEnvelope,
  BlockInstanceIssue,
  BlockInstanceIssue as WidgetInstanceIssue,
  BlockInstancesResult,
  BlockInstancesResult as WidgetInstancesResult,
  ContentNodePath,
} from "./validate";
export {
  blockVariantLabel,
  blockVariantLabel as widgetVariantLabel,
  blockVariants,
  blockVariants as widgetVariants,
  findBlockVariant,
  findBlockVariant as findWidgetVariant,
  hasBlockVariants,
  hasBlockVariants as hasWidgetVariants,
  resolveBlockVariant,
  resolveBlockVariant as resolveWidgetVariant,
} from "./variant";
export type {
  BlockVariantResolution,
  BlockVariantResolution as WidgetVariantResolution,
} from "./variant";
export {
  assertContentZoneId,
  contentZoneAttributes,
  formatBlockAllowed,
  formatBlockAllowed as formatWidgetAllowed,
  isContentZoneId,
  parseContentZoneId,
} from "./zone-meta";
