/**
 * Columns the Content Engine always adds. They can never be declared as
 * content fields - `defineContentType` rejects them.
 */
export const CONTENT_SYSTEM_FIELDS = ["id", "createdAt", "updatedAt"] as const;

/**
 * Columns generated by `publication: { enabled: true }`.
 *
 * Reserved *only* when publication is enabled. Plenty of Stage 1 content types
 * declare their own `status` enum - that stays legal, and opting into
 * publication is what turns the name into an error.
 */
export const CONTENT_PUBLICATION_FIELDS = ["status", "publishedAt"] as const;

export const CONTENT_PUBLICATION_STATUSES = ["draft", "published"] as const;

const publicationStatuses: ReadonlySet<string> = new Set(
  CONTENT_PUBLICATION_STATUSES,
);

/**
 * Whether a value is one of the two generated publication statuses.
 *
 * The generated Zod schemas already narrow this on the HTTP path, so this is
 * defence in depth for the direct-service path: a cast, a plain-JavaScript
 * caller or an object built at runtime can put anything in `filters.status`,
 * and that value must never reach Drizzle.
 *
 * Takes `unknown` and returns a predicate derived from the constant rather than
 * from `ContentPublicationStatus`, so this module stays free of type imports
 * from `types.ts` - which imports from here.
 */
export const isContentPublicationStatus = (
  value: unknown,
): value is (typeof CONTENT_PUBLICATION_STATUSES)[number] =>
  typeof value === "string" && publicationStatuses.has(value);

/** `varchar` length of the generated `status` column. */
export const CONTENT_PUBLICATION_STATUS_LENGTH = 32;

/**
 * Field kinds a generated equality filter understands.
 *
 * `textarea` and `dateTime` are absent on purpose: equality against a body of
 * prose, or against one exact timestamp, is never what anyone means.
 *
 * One list, three consumers - the filter schema, the query builder and the
 * public service types all derive from it, so they cannot drift apart.
 */
export const CONTENT_FILTERABLE_FIELD_KINDS = [
  "boolean",
  "enum",
  "number",
  "relation",
  "slug",
  "text",
  "user",
] as const;

const filterableFieldKinds: ReadonlySet<string> = new Set(
  CONTENT_FILTERABLE_FIELD_KINDS,
);

/**
 * Whether a field of this kind may back a generated equality filter.
 *
 * Takes a plain `string` rather than `ContentFieldKind` so this module stays
 * free of type imports from `types.ts`, which imports from here.
 */
export const isFilterableFieldKind = (kind: string): boolean =>
  filterableFieldKinds.has(kind);

/**
 * Query-string keys owned by pagination and ordering. A filter may not use one
 * of these names or it would silently shadow the pagination contract.
 */
export const RESERVED_FILTER_KEYS = [
  "cursor",
  "first",
  "last",
  "order",
  "orderBy",
  "search",
] as const;

/** `plugin.entity`, e.g. `example.article`. */
export const CONTENT_ID_PATTERN = /^[a-z0-9]+(?:\.[a-z0-9-]+)+$/;

/** Postgres identifier: snake_case, starts with a letter. */
export const CONTENT_TABLE_NAME_PATTERN = /^[a-z][a-z0-9_]*$/;

/** camelCase, matching `casing: "camelCase"` on the Drizzle client. */
export const CONTENT_FIELD_NAME_PATTERN = /^[a-z][a-zA-Z0-9]*$/;

/** Explicit index names follow the same snake_case rule as table names. */
export const CONTENT_INDEX_NAME_PATTERN = CONTENT_TABLE_NAME_PATTERN;

/** Postgres silently truncates identifiers past this length. */
export const CONTENT_IDENTIFIER_MAX_LENGTH = 63;

export const CONTENT_TEXT_DEFAULT_LENGTH = 255;
export const CONTENT_ENUM_DEFAULT_LENGTH = 64;

/**
 * `varchar` length of a slug column, and the length {@link slugify} truncates
 * to. Shorter than a text field on purpose: a slug is a URL segment, and 160
 * characters is already far past what anyone types or shares.
 */
export const CONTENT_SLUG_DEFAULT_LENGTH = 160;

export const CONTENT_DEFAULT_PAGE_SIZE = 25;
export const CONTENT_OPTIONS_LIMIT = 25;

/**
 * Every content type gets the first four staff permissions. `can_publish` is
 * generated only for content types with `publication: { enabled: true }`.
 */
export const CONTENT_PERMISSIONS = {
  create: "can_create",
  delete: "can_delete",
  edit: "can_edit",
  publish: "can_publish",
  view: "can_view",
} as const;
