import type {
  ContentAdminConfig,
  ContentFieldDescriptor,
  ContentFieldMap,
  ContentFieldsConstraint,
  ContentIndexInput,
  ContentPublicApiConfig,
  ContentPublicationConfig,
  ContentPublicExposableField,
  ContentTypeDefinition,
  ResolvedContentAdminConfig,
  ResolvedContentPublicApiConfig,
} from "./types";

import {
  CONTENT_ENUM_DEFAULT_LENGTH,
  CONTENT_FIELD_NAME_PATTERN,
  CONTENT_FILTERABLE_FIELD_KINDS,
  CONTENT_ID_PATTERN,
  CONTENT_IDENTIFIER_MAX_LENGTH,
  CONTENT_PUBLIC_ALWAYS_ORDERABLE,
  CONTENT_PUBLIC_EXPOSABLE_COLUMNS,
  CONTENT_PUBLIC_EXPOSABLE_KINDS,
  CONTENT_PUBLIC_PATH_MAX_LENGTH,
  CONTENT_PUBLIC_PATH_PATTERN,
  CONTENT_PUBLIC_RESERVED_PATHS,
  CONTENT_PUBLICATION_FIELDS,
  CONTENT_SYSTEM_FIELDS,
  CONTENT_TABLE_NAME_PATTERN,
  isFilterableFieldKind,
} from "./const";
import { ContentEngineError } from "./errors";
import { resolveContentIndexes } from "./indexes";
import { buildContentSchemas } from "./schemas";

/** Kinds the default `searchableFields` picks up, and `titleField` falls back to. */
const SEARCHABLE_KINDS = new Set<ContentFieldDescriptor["kind"]>([
  "text",
  "textarea",
]);

/**
 * Kinds an explicit `searchableFields` may name. A slug is searchable when you
 * ask for it, but never by default - matching a URL segment against what
 * someone typed into a search box is a deliberate choice, not a freebie.
 */
const EXPLICIT_SEARCHABLE_KINDS = new Set<ContentFieldDescriptor["kind"]>([
  ...SEARCHABLE_KINDS,
  "slug",
]);

/** A slug can only be derived from a field that holds a single line of text. */
const SLUG_SOURCE_KINDS = new Set<ContentFieldDescriptor["kind"]>(["text"]);

const systemFields: readonly string[] = CONTENT_SYSTEM_FIELDS;
const publicationFields: readonly string[] = CONTENT_PUBLICATION_FIELDS;

const slugifyModule = (value: string): string =>
  value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");

/** A field with no default that is neither required nor nullable is unwritable. */
const hasWritableFallback = (fieldValue: ContentFieldDescriptor): boolean => {
  if (fieldValue.kind === "dateTime") return fieldValue.defaultNow;
  if (fieldValue.kind === "relation" || fieldValue.kind === "user") {
    return false;
  }
  // A sourced slug has no column default and is not required, but it is always
  // writable: the service derives it from the source field.
  if (fieldValue.kind === "slug") return fieldValue.source !== undefined;

  return fieldValue.defaultValue !== undefined;
};

const assertFieldName = (
  id: string,
  name: string,
  publication: boolean,
): void => {
  if (systemFields.includes(name)) {
    throw new ContentEngineError(
      `"${name}" is a reserved system column and cannot be declared as a field.`,
      { contentTypeId: id },
    );
  }

  if (publication && publicationFields.includes(name)) {
    throw new ContentEngineError(
      `"${name}" is generated by \`publication\` and cannot also be declared as a field. Rename the field, or drop \`publication\` and manage the lifecycle yourself.`,
      { contentTypeId: id },
    );
  }

  if (!CONTENT_FIELD_NAME_PATTERN.test(name)) {
    throw new ContentEngineError(
      `Field "${name}" must be camelCase and start with a lowercase letter.`,
      { contentTypeId: id },
    );
  }
};

const FIELD_KINDS = new Set<string>([
  "boolean",
  "dateTime",
  "enum",
  "number",
  "relation",
  "slug",
  "text",
  "textarea",
  "user",
]);

/** Guards the widening of `ContentFieldsConstraint` to `ContentFieldMap`. */
const assertFieldKind = (
  id: string,
  name: string,
  fieldValue: ContentFieldDescriptor,
): void => {
  if (!FIELD_KINDS.has(fieldValue?.kind)) {
    throw new ContentEngineError(
      `Field "${name}" is not a field descriptor. Build it with \`field.text()\`, \`field.enum()\`, and so on.`,
      { contentTypeId: id },
    );
  }
};

const assertField = (
  id: string,
  name: string,
  fieldValue: ContentFieldDescriptor,
): void => {
  if (!fieldValue.required && !fieldValue.nullable) {
    if (!hasWritableFallback(fieldValue)) {
      throw new ContentEngineError(
        `Field "${name}" is neither required nor nullable, so it needs a default value - otherwise a row could never be inserted.`,
        { contentTypeId: id },
      );
    }
  }

  if (fieldValue.kind === "relation" || fieldValue.kind === "user") {
    // Postgres would accept the definition and then fail at delete time, when
    // it tries to write NULL into a NOT NULL column.
    if (fieldValue.onDelete === "set null" && !fieldValue.nullable) {
      throw new ContentEngineError(
        `Field "${name}" is \`onDelete: "set null"\` but not nullable, so deleting the referenced row would violate NOT NULL. Add \`nullable: true\`, or switch to \`onDelete: "restrict"\` or \`"cascade"\`.`,
        { contentTypeId: id },
      );
    }
  }

  if (fieldValue.kind === "text" || fieldValue.kind === "textarea") {
    const { maxLength, minLength } = fieldValue;
    if (maxLength !== undefined && maxLength <= 0) {
      throw new ContentEngineError(
        `Field "${name}" has a maxLength of ${maxLength}; it must be positive.`,
        { contentTypeId: id },
      );
    }
    if (
      minLength !== undefined &&
      maxLength !== undefined &&
      minLength > maxLength
    ) {
      throw new ContentEngineError(
        `Field "${name}" has minLength ${minLength} greater than maxLength ${maxLength}.`,
        { contentTypeId: id },
      );
    }
  }

  if (fieldValue.kind === "slug") {
    const { maxLength } = fieldValue;
    if (maxLength !== undefined && maxLength <= 0) {
      throw new ContentEngineError(
        `Field "${name}" has a maxLength of ${maxLength}; it must be positive.`,
        { contentTypeId: id },
      );
    }
  }

  if (fieldValue.kind === "number") {
    const { max, min } = fieldValue;
    if (min !== undefined && max !== undefined && min > max) {
      throw new ContentEngineError(
        `Field "${name}" has min ${min} greater than max ${max}.`,
        { contentTypeId: id },
      );
    }
  }

  if (fieldValue.kind === "enum") {
    const { defaultValue, length = CONTENT_ENUM_DEFAULT_LENGTH } = fieldValue;
    const values: readonly string[] = fieldValue.values;

    if (values.length === 0) {
      throw new ContentEngineError(
        `Field "${name}" needs at least one value.`,
        {
          contentTypeId: id,
        },
      );
    }
    if (new Set(values).size !== values.length) {
      throw new ContentEngineError(
        `Field "${name}" has duplicate enum values.`,
        { contentTypeId: id },
      );
    }
    const tooLong = values.find(value => value.length > length);
    if (tooLong !== undefined) {
      throw new ContentEngineError(
        `Field "${name}" value "${tooLong}" is longer than the column length ${length}. Raise \`length\` on the field.`,
        { contentTypeId: id },
      );
    }
    if (defaultValue !== undefined && !values.includes(defaultValue)) {
      throw new ContentEngineError(
        `Field "${name}" has default "${defaultValue}", which is not one of its values.`,
        { contentTypeId: id },
      );
    }
  }
};

/**
 * Checks every `field.slug({ source })` against the field map.
 *
 * Runs after the per-field pass, because a source is a reference to a *sibling*
 * field and nothing can see the whole map until then.
 */
const assertSlugSources = (id: string, fields: ContentFieldMap): void => {
  for (const [name, fieldValue] of Object.entries(fields)) {
    if (fieldValue.kind !== "slug" || fieldValue.source === undefined) continue;

    const source = fields[fieldValue.source];
    if (!source) {
      throw new ContentEngineError(
        `Slug field "${name}" is sourced from "${fieldValue.source}", which is not a field on this content type.`,
        { contentTypeId: id },
      );
    }

    if (!SLUG_SOURCE_KINDS.has(source.kind)) {
      throw new ContentEngineError(
        `Slug field "${name}" is sourced from "${fieldValue.source}", which is a "${source.kind}" field. A slug can only be derived from a text field.`,
        { contentTypeId: id },
      );
    }
  }
};

const assertKnownColumns = (
  id: string,
  label: string,
  names: readonly string[],
  known: ReadonlySet<string>,
): void => {
  const unknown = names.find(name => !known.has(name));
  if (unknown !== undefined) {
    throw new ContentEngineError(
      `${label} references unknown field "${unknown}".`,
      { contentTypeId: id },
    );
  }
};

const resolveAdmin = <TFields>(
  id: string,
  fields: ContentFieldMap,
  admin: ContentAdminConfig<TFields>,
  publication: boolean,
): ResolvedContentAdminConfig => {
  const fieldNames = Object.keys(fields);
  const generatedColumns = publication
    ? [...systemFields, ...publicationFields]
    : systemFields;
  const knownColumns = new Set([...fieldNames, ...generatedColumns]);

  const searchableFields = (
    admin.list?.searchableFields?.map(String) ??
    fieldNames.filter(name => SEARCHABLE_KINDS.has(fields[name].kind))
  ).map(String);
  assertKnownColumns(
    id,
    "admin.list.searchableFields",
    searchableFields,
    new Set(fieldNames),
  );
  const notSearchable = searchableFields.find(
    name => !EXPLICIT_SEARCHABLE_KINDS.has(fields[name].kind),
  );
  if (notSearchable !== undefined) {
    throw new ContentEngineError(
      `admin.list.searchableFields includes "${notSearchable}", which is not a text, textarea or slug field.`,
      { contentTypeId: id },
    );
  }

  const orderableFields = (admin.list?.orderableFields ?? []).map(String);
  assertKnownColumns(
    id,
    "admin.list.orderableFields",
    orderableFields,
    new Set(fieldNames),
  );

  // A published/draft badge is the first thing anyone looks for, so it leads
  // the default column list.
  const defaultColumns = publication
    ? ["status", ...fieldNames, "updatedAt"]
    : [...fieldNames, "updatedAt"];
  const columns = (admin.list?.columns?.map(String) ?? defaultColumns).map(
    String,
  );
  assertKnownColumns(id, "admin.list.columns", columns, knownColumns);

  const formFields = (admin.form?.fields?.map(String) ?? fieldNames).map(
    String,
  );
  assertKnownColumns(id, "admin.form.fields", formFields, new Set(fieldNames));

  const defaultOrderBy = String(admin.list?.defaultOrderBy ?? "updatedAt");
  if (
    !generatedColumns.includes(defaultOrderBy) &&
    !orderableFields.includes(defaultOrderBy)
  ) {
    throw new ContentEngineError(
      `admin.list.defaultOrderBy is "${defaultOrderBy}", which is not in admin.list.orderableFields.`,
      { contentTypeId: id },
    );
  }

  const titleField =
    admin.titleField === undefined
      ? (fieldNames.find(name => SEARCHABLE_KINDS.has(fields[name].kind)) ??
        null)
      : String(admin.titleField);
  if (titleField !== null && !fieldNames.includes(titleField)) {
    throw new ContentEngineError(
      `admin.titleField references unknown field "${titleField}".`,
      { contentTypeId: id },
    );
  }

  return {
    form: { fields: formFields },
    label: admin.label,
    list: {
      columns,
      defaultOrder: admin.list?.defaultOrder ?? "desc",
      defaultOrderBy,
      orderableFields,
      searchableFields,
    },
    navigation: { enabled: admin.navigation?.enabled ?? true },
    titleField,
  };
};

const publicExposableKinds: ReadonlySet<string> = new Set(
  CONTENT_PUBLIC_EXPOSABLE_KINDS,
);
const publicExposableColumns: readonly string[] =
  CONTENT_PUBLIC_EXPOSABLE_COLUMNS;
const publicReservedPaths: readonly string[] = CONTENT_PUBLIC_RESERVED_PATHS;

const assertPublicPath = (id: string, path: string): void => {
  if (!CONTENT_PUBLIC_PATH_PATTERN.test(path)) {
    throw new ContentEngineError(
      `publicApi.path "${path}" must be one lowercase URL segment: a letter, then letters, digits or dashes. No slashes, no dots, no leading or trailing separator.`,
      { contentTypeId: id },
    );
  }

  if (path.length > CONTENT_PUBLIC_PATH_MAX_LENGTH) {
    throw new ContentEngineError(
      `publicApi.path "${path}" is longer than ${CONTENT_PUBLIC_PATH_MAX_LENGTH} characters.`,
      { contentTypeId: id },
    );
  }

  if (publicReservedPaths.includes(path)) {
    throw new ContentEngineError(
      `publicApi.path "${path}" is reserved. The admin gate matches any request path containing "/admin/", so a public route under that name would demand a staff session.`,
      { contentTypeId: id },
    );
  }
};

/**
 * Checks and fills in `publicApi`.
 *
 * Every rule here exists to make one guarantee cheap: if a field is not in
 * `fields`, nothing public can read it, order by it, search it or filter on it.
 * So the subset checks are not tidiness - they are what stops a filter or a
 * sort being used to probe a column the response leaves out.
 */
const resolvePublicApi = <TField extends string>(
  id: string,
  fields: ContentFieldMap,
  publicApi: ContentPublicApiConfig<TField> | undefined,
  publication: boolean,
): ResolvedContentPublicApiConfig => {
  if (!publicApi?.enabled) {
    return {
      defaultOrder: "desc",
      defaultOrderBy: CONTENT_PUBLIC_ALWAYS_ORDERABLE,
      enabled: false,
      fields: [],
      filterableFields: [],
      orderableFields: [],
      path: "",
      searchableFields: [],
      slugField: "",
    };
  }

  if (!publication) {
    throw new ContentEngineError(
      "publicApi needs `publication: { enabled: true }`. A public API without a draft state would put every row on the internet the moment it is created.",
      { contentTypeId: id },
    );
  }

  assertPublicPath(id, publicApi.path);

  const exposed = publicApi.fields.map(String);
  if (exposed.length === 0) {
    throw new ContentEngineError(
      "publicApi.fields is empty. There is no wildcard - list the fields you mean to publish.",
      { contentTypeId: id },
    );
  }

  const duplicate = exposed.find(
    (name, position) => exposed.indexOf(name) !== position,
  );
  if (duplicate !== undefined) {
    throw new ContentEngineError(
      `publicApi.fields lists "${duplicate}" twice.`,
      { contentTypeId: id },
    );
  }

  for (const name of exposed) {
    if (publicExposableColumns.includes(name)) continue;

    const fieldValue = fields[name];
    if (!fieldValue) {
      if (publicationFields.includes(name)) {
        throw new ContentEngineError(
          `publicApi.fields includes "${name}", which cannot be exposed. Every row the public API returns is published, so it would be a constant.`,
          { contentTypeId: id },
        );
      }

      throw new ContentEngineError(
        `publicApi.fields references unknown field "${name}".`,
        { contentTypeId: id },
      );
    }

    if (fieldValue.kind === "user") {
      throw new ContentEngineError(
        `publicApi.fields includes the user field "${name}". User fields are not exposable: publishing a person by listing one word is exactly the accident this rule prevents. Write your own route with the shape you mean.`,
        { contentTypeId: id },
      );
    }

    if (!publicExposableKinds.has(fieldValue.kind)) {
      throw new ContentEngineError(
        `publicApi.fields includes "${name}" of kind "${fieldValue.kind}", which cannot be exposed publicly.`,
        { contentTypeId: id },
      );
    }
  }

  const exposedSet = new Set(exposed);
  const assertExposed = (label: string, names: readonly string[]): void => {
    const missing = names.find(name => !exposedSet.has(name));
    if (missing !== undefined) {
      throw new ContentEngineError(
        `${label} includes "${missing}", which is not in publicApi.fields. A private field must not be reachable through a filter, a sort or a search either.`,
        { contentTypeId: id },
      );
    }
  };

  const searchableFields = (publicApi.searchableFields ?? []).map(String);
  assertExposed("publicApi.searchableFields", searchableFields);
  const notSearchable = searchableFields.find(
    name => !EXPLICIT_SEARCHABLE_KINDS.has(fields[name]?.kind),
  );
  if (notSearchable !== undefined) {
    throw new ContentEngineError(
      `publicApi.searchableFields includes "${notSearchable}", which is not a text, textarea or slug field.`,
      { contentTypeId: id },
    );
  }

  const filterableFields = (publicApi.filterableFields ?? []).map(String);
  assertExposed("publicApi.filterableFields", filterableFields);
  const notFilterable = filterableFields.find(
    name => !isFilterableFieldKind(fields[name]?.kind ?? ""),
  );
  if (notFilterable !== undefined) {
    throw new ContentEngineError(
      `publicApi.filterableFields includes "${notFilterable}", which is not an equality-filterable field. Filterable kinds: ${CONTENT_FILTERABLE_FIELD_KINDS.join(", ")}.`,
      { contentTypeId: id },
    );
  }

  const declaredOrderable = (publicApi.orderableFields ?? []).map(String);
  assertExposed("publicApi.orderableFields", declaredOrderable);
  const orderableFields = [
    ...new Set([...declaredOrderable, CONTENT_PUBLIC_ALWAYS_ORDERABLE]),
  ];

  const defaultOrderBy =
    publicApi.defaultOrderBy ?? CONTENT_PUBLIC_ALWAYS_ORDERABLE;
  if (!orderableFields.includes(defaultOrderBy)) {
    throw new ContentEngineError(
      `publicApi.defaultOrderBy is "${defaultOrderBy}", which is not in publicApi.orderableFields.`,
      { contentTypeId: id },
    );
  }

  const slugFields = exposed.filter(name => fields[name]?.kind === "slug");
  if (slugFields.length !== 1) {
    throw new ContentEngineError(
      slugFields.length === 0
        ? "publicApi.fields must expose exactly one slug field - it is what the public detail route resolves by. Add `field.slug({ source: ... })` and list it."
        : `publicApi.fields exposes ${slugFields.length} slug fields (${slugFields.join(", ")}). Expose exactly one, so the detail route has a single identifier.`,
      { contentTypeId: id },
    );
  }

  return {
    defaultOrder: publicApi.defaultOrder ?? "desc",
    defaultOrderBy,
    enabled: true,
    fields: exposed,
    filterableFields,
    orderableFields,
    path: publicApi.path,
    searchableFields,
    slugField: slugFields[0],
  };
};

/**
 * Declares a content type. The result is plain data - zod and objects only -
 * so the same definition can be imported by `buildPlugin` (client) and by
 * `createContentModel` in `src/database/*.ts` (server) without dragging Drizzle
 * into a client bundle.
 */
export const defineContentType = <
  TId extends string,
  TFields extends ContentFieldsConstraint<TPublication>,
  TPublication extends boolean = false,
  TPublicField extends ContentPublicExposableField<TFields> = never,
  TPublicEnabled extends boolean = false,
>({
  admin,
  fields,
  id,
  indexes = [],
  publicApi,
  publication,
  tableName,
}: {
  admin: ContentAdminConfig<TFields, TPublication>;
  fields: TFields;
  id: TId;
  indexes?: ContentIndexInput<TFields, TPublication>[];
  /**
   * Opts into a generated read-only public API. Needs `publication` and exactly
   * one exposed slug field. Omit it and nothing public is generated.
   */
  publicApi?:
    ContentPublicApiConfig<TPublicField> | { enabled: TPublicEnabled };
  /** Opts into the draft/published lifecycle. Omit to stay on Stage 1 behaviour. */
  publication?: ContentPublicationConfig | { enabled: TPublication };
  tableName: string;
}): ContentTypeDefinition<
  TId,
  TFields,
  TPublication,
  TPublicField,
  TPublicEnabled
> => {
  if (!CONTENT_ID_PATTERN.test(id)) {
    throw new ContentEngineError(
      `Content type id "${id}" must look like "plugin.entity" (lowercase, dot separated).`,
    );
  }

  if (!CONTENT_TABLE_NAME_PATTERN.test(tableName)) {
    throw new ContentEngineError(
      `Table name "${tableName}" must be snake_case and start with a letter.`,
      { contentTypeId: id },
    );
  }

  if (tableName.length > CONTENT_IDENTIFIER_MAX_LENGTH) {
    throw new ContentEngineError(
      `Table name "${tableName}" is longer than the Postgres identifier limit of ${CONTENT_IDENTIFIER_MAX_LENGTH} characters.`,
      { contentTypeId: id },
    );
  }

  // `ContentFieldsConstraint` only pins `kind` (see its doc comment), so widen
  // to the real descriptor union here. This is the only unchecked widening in
  // the engine, and `assertFieldKind` below makes it true at runtime for
  // anything that skipped the `field.*` builders.
  const fieldMap = fields as unknown as ContentFieldMap;
  const fieldNames = Object.keys(fieldMap);
  if (fieldNames.length === 0) {
    throw new ContentEngineError("A content type needs at least one field.", {
      contentTypeId: id,
    });
  }

  const publicationEnabled = publication?.enabled === true;

  for (const name of fieldNames) {
    assertFieldName(id, name, publicationEnabled);
    assertFieldKind(id, name, fieldMap[name]);
    assertField(id, name, fieldMap[name]);
  }

  assertSlugSources(id, fieldMap);

  const knownColumns = new Set([
    ...fieldNames,
    ...systemFields,
    ...(publicationEnabled ? publicationFields : []),
  ]);
  const resolvedIndexes = resolveContentIndexes({
    contentTypeId: id,
    declared: indexes.map(index => {
      const on = index.on.map(String);
      assertKnownColumns(id, "indexes", on, knownColumns);

      return { ...index, on };
    }),
    fields: fieldMap,
    publication: publicationEnabled,
    tableName,
  });

  const resolvedAdmin = resolveAdmin(id, fieldMap, admin, publicationEnabled);
  const permissionModule =
    admin.permissionModule ?? slugifyModule(admin.label.plural);

  if (!CONTENT_TABLE_NAME_PATTERN.test(permissionModule)) {
    throw new ContentEngineError(
      `Could not derive a permission module name from label.plural "${admin.label.plural}". Set \`admin.permissionModule\` explicitly.`,
      { contentTypeId: id },
    );
  }

  const resolvedPublicApi = resolvePublicApi(
    id,
    fieldMap,
    // The `{ enabled: TPublicEnabled }` arm of the parameter exists only so an
    // `enabled: false` literal still typechecks; `resolvePublicApi` returns the
    // disabled config for anything that is not `enabled: true`.
    publicApi as ContentPublicApiConfig<TPublicField> | undefined,
    publicationEnabled,
  );

  return {
    admin: resolvedAdmin,
    fields,
    id,
    indexes: resolvedIndexes,
    permissionModule,
    publication: {
      enabled: publicationEnabled as TPublication,
    },
    publicApi: resolvedPublicApi as ResolvedContentPublicApiConfig<
      TPublicField,
      TPublicEnabled
    >,
    schemas: buildContentSchemas<
      ContentTypeDefinition<
        TId,
        TFields,
        TPublication,
        TPublicField,
        TPublicEnabled
      >
    >({
      admin: resolvedAdmin,
      fields: fieldMap,
      publicApi: resolvedPublicApi,
      publication: publicationEnabled,
    }),
    tableName,
  };
};
