import type {
  AnyContentTypeDefinition,
  ContentAdminActionConfig,
  ContentAdminConfig,
  ContentAdminFormMode,
  ContentDeliveryConfig,
  ContentDeliveryDescriptionField,
  ContentDeliveryEnabled,
  ContentDeliveryNoIndexField,
  ContentDeliveryTitleField,
  ContentEditorialConfig,
  ContentEditorialEnabled,
  ContentFieldDescriptor,
  ContentFieldMap,
  ContentFieldsConstraint,
  ContentIndexInput,
  ContentLocalizationConfig,
  ContentLocalizationEnabled,
  ContentPreviewEnabled,
  ContentPublicApiConfig,
  ContentPublicationConfig,
  ContentPublicExposableField,
  ContentSchedulingEnabled,
  ContentSearchConfig,
  ContentSearchDescriptionField,
  ContentSearchEnabled,
  ContentSearchTextField,
  ContentSearchTitleField,
  ContentTypeDefinition,
  ResolvedContentAdminConfig,
  ResolvedContentDeliveryConfig,
  ResolvedContentEditorialConfig,
  ResolvedContentLocalizationConfig,
  ResolvedContentPublicApiConfig,
  ResolvedContentSearchConfig,
} from "./types";

import {
  assertContentRelationTargets,
  resolveContentAdvanced,
} from "./advanced";
import {
  CONTENT_ADMIN_FORM_MODES,
  CONTENT_EDITORIAL_FIELDS,
  CONTENT_ENUM_DEFAULT_LENGTH,
  CONTENT_FIELD_NAME_PATTERN,
  CONTENT_FILTERABLE_FIELD_KINDS,
  CONTENT_ID_PATTERN,
  CONTENT_IDENTIFIER_MAX_LENGTH,
  CONTENT_PREVIEW_DEFAULT_TTL_MINUTES,
  CONTENT_PREVIEW_MAX_TTL_MINUTES,
  CONTENT_PREVIEW_MIN_TTL_MINUTES,
  CONTENT_PREVIEW_PATH_MAX_LENGTH,
  CONTENT_PREVIEW_TOKEN_PLACEHOLDER,
  CONTENT_PUBLIC_ALWAYS_ORDERABLE,
  CONTENT_PUBLIC_EXPOSABLE_COLUMNS,
  CONTENT_PUBLIC_EXPOSABLE_KINDS,
  CONTENT_PUBLIC_PATH_MAX_LENGTH,
  CONTENT_PUBLIC_PATH_PATTERN,
  CONTENT_PUBLIC_RESERVED_PATHS,
  CONTENT_PUBLICATION_FIELDS,
  CONTENT_REVISION_DEFAULT_RETENTION,
  CONTENT_REVISION_MAX_RETENTION,
  CONTENT_REVISION_MIN_RETENTION,
  CONTENT_SEARCH_DESCRIPTION_KINDS,
  CONTENT_SEARCH_ITEM_TYPE_MAX_LENGTH,
  CONTENT_SEARCH_LOCALE_PLACEHOLDER,
  CONTENT_SEARCH_PATH_MAX_LENGTH,
  CONTENT_SEARCH_SLUG_PLACEHOLDER,
  CONTENT_SEARCH_TEXT_KINDS,
  CONTENT_SEARCH_TITLE_KINDS,
  CONTENT_SYSTEM_FIELDS,
  CONTENT_TABLE_NAME_PATTERN,
  isFilterableFieldKind,
} from "./const";
import { resolveContentDelivery } from "./delivery";
import { ContentEngineError } from "./errors";
import { resolveContentIndexes } from "./indexes";
import {
  partitionContentFields,
  resolveContentLocalization,
} from "./localization";
import {
  contentStorageColumns,
  isContentRelationCollection,
  splitContentFieldPath,
} from "./paths";
import { buildContentSchemas } from "./schemas";

/** Kinds the default `searchableFields` picks up, and `titleField` falls back to. */
const SEARCHABLE_KINDS = new Set<ContentFieldDescriptor["kind"]>([
  "text",
  "textarea",
]);

/**
 * Kinds an explicit `searchableFields` may name. A slug is searchable when you
 * ask for it, but never by default - matching a URL segment against what
 * someone typed into a search box is a deliberate choice, not a freebie.
 */
const EXPLICIT_SEARCHABLE_KINDS = new Set<ContentFieldDescriptor["kind"]>([
  ...SEARCHABLE_KINDS,
  "slug",
]);

/** A slug can only be derived from a field that holds a single line of text. */
const SLUG_SOURCE_KINDS = new Set<ContentFieldDescriptor["kind"]>(["text"]);

const systemFields: readonly string[] = CONTENT_SYSTEM_FIELDS;
const publicationFields: readonly string[] = CONTENT_PUBLICATION_FIELDS;
const editorialFields: readonly string[] = CONTENT_EDITORIAL_FIELDS;

const slugifyModule = (value: string): string =>
  value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");

/** A field with no default that is neither required nor nullable is unwritable. */
const hasWritableFallback = (fieldValue: ContentFieldDescriptor): boolean => {
  if (fieldValue.kind === "dateTime") return fieldValue.defaultNow;
  // A group is writable because its leaves are - `resolveContentAdvanced`
  // proves each of them is nullable or defaulted when the group is optional.
  // A collection is writable because the empty set is its default.
  if (fieldValue.kind === "group" || fieldValue.kind === "repeatable") {
    return true;
  }
  if (fieldValue.kind === "relation") return fieldValue.multiple;
  if (fieldValue.kind === "user") return false;
  // A sourced slug has no column default and is not required, but it is always
  // writable: the service derives it from the source field.
  if (fieldValue.kind === "slug") return fieldValue.source !== undefined;

  return fieldValue.defaultValue !== undefined;
};

const assertFieldName = (
  id: string,
  name: string,
  publication: boolean,
  editorial: boolean,
): void => {
  if (systemFields.includes(name)) {
    throw new ContentEngineError(
      `"${name}" is a reserved system column and cannot be declared as a field.`,
      { contentTypeId: id },
    );
  }

  if (publication && publicationFields.includes(name)) {
    throw new ContentEngineError(
      `"${name}" is generated by \`publication\` and cannot also be declared as a field. Rename the field, or drop \`publication\` and manage the lifecycle yourself.`,
      { contentTypeId: id },
    );
  }

  if (editorial && editorialFields.includes(name)) {
    throw new ContentEngineError(
      `"${name}" is generated by \`editorial\` and cannot also be declared as a field. Rename the field, or drop \`editorial\` and manage versioning yourself.`,
      { contentTypeId: id },
    );
  }

  if (!CONTENT_FIELD_NAME_PATTERN.test(name)) {
    throw new ContentEngineError(
      `Field "${name}" must be camelCase and start with a lowercase letter.`,
      { contentTypeId: id },
    );
  }
};

const FIELD_KINDS = new Set<string>([
  "boolean",
  "dateTime",
  "enum",
  "group",
  "number",
  "relation",
  "repeatable",
  "slug",
  "text",
  "textarea",
  "user",
]);

/** Guards the widening of `ContentFieldsConstraint` to `ContentFieldMap`. */
const assertFieldKind = (
  id: string,
  name: string,
  fieldValue: ContentFieldDescriptor,
): void => {
  if (!FIELD_KINDS.has(fieldValue?.kind)) {
    throw new ContentEngineError(
      `Field "${name}" is not a field descriptor. Build it with \`field.text()\`, \`field.enum()\`, and so on.`,
      { contentTypeId: id },
    );
  }
};

const assertField = (
  id: string,
  name: string,
  fieldValue: ContentFieldDescriptor,
): void => {
  if (!fieldValue.required && !fieldValue.nullable) {
    if (!hasWritableFallback(fieldValue)) {
      throw new ContentEngineError(
        `Field "${name}" is neither required nor nullable, so it needs a default value - otherwise a row could never be inserted.`,
        { contentTypeId: id },
      );
    }
  }

  // A to-many relation is checked by `resolveContentAdvanced` instead: it is
  // never nullable by construction, and `"set null"` means something different
  // for a junction row than for a column - so the message has to be different
  // too, and there is only one place it can be.
  if (
    (fieldValue.kind === "relation" && !fieldValue.multiple) ||
    fieldValue.kind === "user"
  ) {
    // Postgres would accept the definition and then fail at delete time, when
    // it tries to write NULL into a NOT NULL column.
    if (fieldValue.onDelete === "set null" && !fieldValue.nullable) {
      throw new ContentEngineError(
        `Field "${name}" is \`onDelete: "set null"\` but not nullable, so deleting the referenced row would violate NOT NULL. Add \`nullable: true\`, or switch to \`onDelete: "restrict"\` or \`"cascade"\`.`,
        { contentTypeId: id },
      );
    }
  }

  if (fieldValue.kind === "text" || fieldValue.kind === "textarea") {
    const { maxLength, minLength } = fieldValue;
    if (maxLength !== undefined && maxLength <= 0) {
      throw new ContentEngineError(
        `Field "${name}" has a maxLength of ${maxLength}; it must be positive.`,
        { contentTypeId: id },
      );
    }
    if (
      minLength !== undefined &&
      maxLength !== undefined &&
      minLength > maxLength
    ) {
      throw new ContentEngineError(
        `Field "${name}" has minLength ${minLength} greater than maxLength ${maxLength}.`,
        { contentTypeId: id },
      );
    }
  }

  if (fieldValue.kind === "slug") {
    const { maxLength } = fieldValue;
    if (maxLength !== undefined && maxLength <= 0) {
      throw new ContentEngineError(
        `Field "${name}" has a maxLength of ${maxLength}; it must be positive.`,
        { contentTypeId: id },
      );
    }
  }

  if (fieldValue.kind === "number") {
    const { max, min } = fieldValue;
    if (min !== undefined && max !== undefined && min > max) {
      throw new ContentEngineError(
        `Field "${name}" has min ${min} greater than max ${max}.`,
        { contentTypeId: id },
      );
    }
  }

  if (fieldValue.kind === "enum") {
    const { defaultValue, length = CONTENT_ENUM_DEFAULT_LENGTH } = fieldValue;
    const values: readonly string[] = fieldValue.values;

    if (values.length === 0) {
      throw new ContentEngineError(
        `Field "${name}" needs at least one value.`,
        {
          contentTypeId: id,
        },
      );
    }
    if (new Set(values).size !== values.length) {
      throw new ContentEngineError(
        `Field "${name}" has duplicate enum values.`,
        { contentTypeId: id },
      );
    }
    const tooLong = values.find(value => value.length > length);
    if (tooLong !== undefined) {
      throw new ContentEngineError(
        `Field "${name}" value "${tooLong}" is longer than the column length ${length}. Raise \`length\` on the field.`,
        { contentTypeId: id },
      );
    }
    if (defaultValue !== undefined && !values.includes(defaultValue)) {
      throw new ContentEngineError(
        `Field "${name}" has default "${defaultValue}", which is not one of its values.`,
        { contentTypeId: id },
      );
    }
  }
};

/**
 * Checks every `field.slug({ source })` against the field map.
 *
 * Runs after the per-field pass, because a source is a reference to a *sibling*
 * field and nothing can see the whole map until then.
 */
const assertSlugSources = (id: string, fields: ContentFieldMap): void => {
  for (const [name, fieldValue] of Object.entries(fields)) {
    if (fieldValue.kind !== "slug" || fieldValue.source === undefined) continue;

    const source = fields[fieldValue.source];
    if (!source) {
      throw new ContentEngineError(
        `Slug field "${name}" is sourced from "${fieldValue.source}", which is not a field on this content type.`,
        { contentTypeId: id },
      );
    }

    if (!SLUG_SOURCE_KINDS.has(source.kind)) {
      throw new ContentEngineError(
        `Slug field "${name}" is sourced from "${fieldValue.source}", which is a "${source.kind}" field. A slug can only be derived from a text field.`,
        { contentTypeId: id },
      );
    }
  }
};

const assertKnownColumns = (
  id: string,
  label: string,
  names: readonly string[],
  known: ReadonlySet<string>,
): void => {
  const unknown = names.find(name => !known.has(name));
  if (unknown !== undefined) {
    throw new ContentEngineError(
      `${label} references unknown field "${unknown}".`,
      { contentTypeId: id },
    );
  }
};

/**
 * Every admin surface addresses a column on the base table, so it is stated in
 * terms of the *shared* fields only. A localized field named here would be a
 * DataTable column, a sort or a search over something the base table does not
 * have - see `ContentAddressableColumn`, which rejects it at compile time too.
 */
const assertNotLocalized = (
  id: string,
  label: string,
  names: readonly string[],
  localizedFields: ContentFieldMap,
): void => {
  const localized = names.find(name => localizedFields[name] !== undefined);
  if (localized !== undefined) {
    throw new ContentEngineError(
      `${label} names the localized field "${localized}", which is not a column on the base table. Localized values get their own AdminCP surface in Stage 5B.`,
      { contentTypeId: id },
    );
  }
};

/**
 * Checks that every column an index names is one it can actually be built on.
 *
 * A repeatable leaf and a to-many relation are refused **loudly** rather than
 * silently dropped: `{ on: ["faq.answer"] }` looks like it works, and an index
 * that was quietly not created is a performance bug nobody can see. Both live on
 * their own generated tables, which already carry the indexes they need.
 */
const assertIndexable = (
  id: string,
  names: readonly string[],
  fields: ContentFieldMap,
  localizedFields: ContentFieldMap,
): void => {
  for (const name of names) {
    const path = splitContentFieldPath(name);
    const owner = path ? path[0] : name;
    const fieldValue = fields[owner];

    if (localizedFields[owner] !== undefined) {
      throw new ContentEngineError(
        path
          ? `indexes names "${name}", a leaf of the localized group "${owner}". Its column is on the translation table, where the unique scope is per language - see \`localization.translationIndexes\`.`
          : `indexes names the localized field "${owner}", which is not a column on the base table. Localized values get their own AdminCP surface in Stage 5B.`,
        { contentTypeId: id },
      );
    }

    if (!fieldValue) continue;

    if (fieldValue.kind === "repeatable") {
      throw new ContentEngineError(
        `indexes names "${name}", which belongs to the repeatable "${owner}". Repeatable leaves are columns on a generated child table, not on the base table, so an index here would have nothing to cover. The child table already carries \`(itemId, position)\`.`,
        { contentTypeId: id },
      );
    }

    if (isContentRelationCollection(fieldValue)) {
      throw new ContentEngineError(
        `indexes names the to-many relation "${owner}", which is not a column: its values live in a generated junction table, which already carries its own primary key and reverse index.`,
        { contentTypeId: id },
      );
    }

    if (fieldValue.kind === "group" && !path) {
      throw new ContentEngineError(
        `indexes names the group "${owner}", which is several columns rather than one. Name the leaves you mean, e.g. \`{ on: ["${owner}.${Object.keys((fieldValue as { fields: ContentFieldMap }).fields)[0]}"] }\`.`,
        { contentTypeId: id },
      );
    }
  }
};

/**
 * Kinds that are not one column on the base table, so they cannot be a list
 * cell, an `orderBy` or a `titleField`.
 *
 * A group is several columns under generated names; a repeatable and a to-many
 * relation are on other tables entirely. All three still belong on the *form* -
 * that is what `admin.form.fields` is for, and it is checked against the wider
 * set.
 */
const NON_COLUMN_KINDS = new Set<ContentFieldDescriptor["kind"]>([
  "group",
  "repeatable",
]);

const isAdminColumnField = (fieldValue: ContentFieldDescriptor): boolean =>
  !NON_COLUMN_KINDS.has(fieldValue.kind) &&
  !isContentRelationCollection(fieldValue);

const adminFormModes: readonly string[] = CONTENT_ADMIN_FORM_MODES;

/**
 * `admin.create.mode` / `admin.edit.mode`, defaulted and checked.
 *
 * Defaults to `dialog`, which is what keeps every content type written before
 * page mode existed behaving exactly as it did. The runtime check is here for a
 * JavaScript caller and for a value that widened somewhere upstream - the type
 * already refuses anything outside the union.
 */
const resolveFormMode = (
  id: string,
  label: string,
  action: ContentAdminActionConfig | undefined,
): ContentAdminFormMode => {
  const mode = action?.mode ?? "dialog";

  if (!adminFormModes.includes(mode)) {
    throw new ContentEngineError(
      `${label} is "${mode}". Expected one of ${adminFormModes.map(value => `"${value}"`).join(", ")}.`,
      { contentTypeId: id },
    );
  }

  return mode;
};

const resolveAdmin = <TFields>(
  id: string,
  fields: ContentFieldMap,
  localizedFields: ContentFieldMap,
  admin: ContentAdminConfig<TFields>,
  publication: boolean,
  editorial: boolean,
): ResolvedContentAdminConfig => {
  const fieldNames = Object.keys(fields);
  // The subset a DataTable cell, an `orderBy` and a toast title may name.
  const columnFieldNames = fieldNames.filter(name =>
    isAdminColumnField(fields[name]),
  );
  const assertColumnField = (label: string, names: readonly string[]): void => {
    const advanced = names.find(
      name => fields[name] !== undefined && !isAdminColumnField(fields[name]),
    );
    if (advanced === undefined) return;

    throw new ContentEngineError(
      `${label} names "${advanced}", a "${fields[advanced].kind}" field. It is not one column on the base table, so it cannot be shown as a cell, ordered by, or used as a title. List it in \`admin.form.fields\` instead${fields[advanced].kind === "group" ? `, or name one of its leaves` : ""}.`,
      { contentTypeId: id },
    );
  };

  for (const [label, names] of [
    ["admin.form.fields", admin.form?.fields],
    ["admin.list.columns", admin.list?.columns],
    ["admin.list.orderableFields", admin.list?.orderableFields],
    ["admin.list.searchableFields", admin.list?.searchableFields],
    [
      "admin.titleField",
      admin.titleField === undefined ? undefined : [admin.titleField],
    ],
    [
      "admin.list.defaultOrderBy",
      admin.list?.defaultOrderBy === undefined
        ? undefined
        : [admin.list.defaultOrderBy],
    ],
  ] as const) {
    if (!names) continue;
    assertNotLocalized(id, label, names.map(String), localizedFields);
    // Every surface here addresses a *column* - except the form, which is the
    // one that renders a group as a section and a collection as an editor.
    if (label === "admin.form.fields") continue;

    assertColumnField(label, names.map(String));
  }

  const generatedColumns = [
    ...systemFields,
    ...(publication ? publicationFields : []),
    ...(editorial ? editorialFields : []),
  ];
  const knownColumns = new Set([...columnFieldNames, ...generatedColumns]);

  const searchableFields = (
    admin.list?.searchableFields?.map(String) ??
    columnFieldNames.filter(name => SEARCHABLE_KINDS.has(fields[name].kind))
  ).map(String);
  assertKnownColumns(
    id,
    "admin.list.searchableFields",
    searchableFields,
    new Set(columnFieldNames),
  );
  const notSearchable = searchableFields.find(
    name => !EXPLICIT_SEARCHABLE_KINDS.has(fields[name].kind),
  );
  if (notSearchable !== undefined) {
    throw new ContentEngineError(
      `admin.list.searchableFields includes "${notSearchable}", which is not a text, textarea or slug field.`,
      { contentTypeId: id },
    );
  }

  const orderableFields = (admin.list?.orderableFields ?? []).map(String);
  assertKnownColumns(
    id,
    "admin.list.orderableFields",
    orderableFields,
    new Set(columnFieldNames),
  );

  // A published/draft badge is the first thing anyone looks for, so it leads
  // the default column list. Advanced fields are absent by default: a to-many
  // relation and a repeatable are each an extra query, and defaulting them into
  // the list would issue one per row.
  const defaultColumns = publication
    ? ["status", ...columnFieldNames, "updatedAt"]
    : [...columnFieldNames, "updatedAt"];
  const columns = (admin.list?.columns?.map(String) ?? defaultColumns).map(
    String,
  );
  assertKnownColumns(id, "admin.list.columns", columns, knownColumns);

  const formFields = (admin.form?.fields?.map(String) ?? fieldNames).map(
    String,
  );
  assertKnownColumns(id, "admin.form.fields", formFields, new Set(fieldNames));

  const defaultOrderBy = String(admin.list?.defaultOrderBy ?? "updatedAt");
  if (
    !generatedColumns.includes(defaultOrderBy) &&
    !orderableFields.includes(defaultOrderBy)
  ) {
    throw new ContentEngineError(
      `admin.list.defaultOrderBy is "${defaultOrderBy}", which is not in admin.list.orderableFields.`,
      { contentTypeId: id },
    );
  }

  const titleField =
    admin.titleField === undefined
      ? (columnFieldNames.find(name =>
          SEARCHABLE_KINDS.has(fields[name].kind),
        ) ?? null)
      : // `null` is a decision, not an omission: it says this content type has
        // no shared title rather than "pick one for me".
        admin.titleField === null
        ? null
        : String(admin.titleField);
  if (titleField !== null && !columnFieldNames.includes(titleField)) {
    throw new ContentEngineError(
      `admin.titleField references unknown field "${titleField}".`,
      { contentTypeId: id },
    );
  }

  return {
    create: { mode: resolveFormMode(id, "admin.create.mode", admin.create) },
    edit: { mode: resolveFormMode(id, "admin.edit.mode", admin.edit) },
    form: { fields: formFields },
    label: admin.label,
    list: {
      columns,
      defaultOrder: admin.list?.defaultOrder ?? "desc",
      defaultOrderBy,
      orderableFields,
      searchableFields,
    },
    navigation: { enabled: admin.navigation?.enabled ?? true },
    titleField,
  };
};

const publicExposableKinds: ReadonlySet<string> = new Set(
  CONTENT_PUBLIC_EXPOSABLE_KINDS,
);
const publicExposableColumns: readonly string[] =
  CONTENT_PUBLIC_EXPOSABLE_COLUMNS;
const publicReservedPaths: readonly string[] = CONTENT_PUBLIC_RESERVED_PATHS;

const assertPublicPath = (id: string, path: string): void => {
  if (!CONTENT_PUBLIC_PATH_PATTERN.test(path)) {
    throw new ContentEngineError(
      `publicApi.path "${path}" must be one lowercase URL segment: a letter, then letters, digits or dashes. No slashes, no dots, no leading or trailing separator.`,
      { contentTypeId: id },
    );
  }

  if (path.length > CONTENT_PUBLIC_PATH_MAX_LENGTH) {
    throw new ContentEngineError(
      `publicApi.path "${path}" is longer than ${CONTENT_PUBLIC_PATH_MAX_LENGTH} characters.`,
      { contentTypeId: id },
    );
  }

  if (publicReservedPaths.includes(path)) {
    throw new ContentEngineError(
      `publicApi.path "${path}" is reserved. The admin gate matches any request path containing "/admin/", so a public route under that name would demand a staff session.`,
      { contentTypeId: id },
    );
  }
};

/**
 * Resolves a name or a canonical path to the descriptor it addresses.
 *
 * One function, so every allowlist in this file - public fields, searchable,
 * filterable, orderable, and the three search slots - asks the same question and
 * gets the same answer. `container` says where the value lives, which is what
 * separates "a column on the row" from "a column on a child row": the second can
 * be indexed for search but never filtered, ordered or searched by a list query.
 */
const resolveFieldTarget = (
  fields: ContentFieldMap,
  name: string,
): null | {
  container: "group" | "repeatable" | "row";
  descriptor: ContentFieldDescriptor;
} => {
  const path = splitContentFieldPath(name);
  if (!path) {
    const fieldValue = fields[name];

    return fieldValue ? { container: "row", descriptor: fieldValue } : null;
  }

  const [owner, leaf] = path;
  const container = fields[owner];
  if (container?.kind !== "group" && container?.kind !== "repeatable") {
    return null;
  }

  const leafValue = (container as { fields: ContentFieldMap }).fields[leaf];

  return leafValue
    ? { container: container.kind, descriptor: leafValue }
    : null;
};

/**
 * Checks one exposed **leaf path**, e.g. `"seo.title"` or `"faq.question"`.
 *
 * The container has to be a group or a repeatable, and the leaf has to be one it
 * declares: a path that resolves to nothing would be a key the response promises
 * and never carries, which a generated OpenAPI schema turns into a lie rather
 * than an error.
 */
const assertPublicLeafPath = (
  id: string,
  fields: ContentFieldMap,
  name: string,
  [owner, leaf]: [string, string],
): void => {
  const container = fields[owner];
  if (!container) {
    throw new ContentEngineError(
      `publicApi.fields includes "${name}", but this content type declares no field called "${owner}".`,
      { contentTypeId: id },
    );
  }

  if (container.kind !== "group" && container.kind !== "repeatable") {
    throw new ContentEngineError(
      `publicApi.fields includes "${name}", but "${owner}" is a "${container.kind}" field rather than a group or a repeatable. Only those have leaves.`,
      { contentTypeId: id },
    );
  }

  const inner = (container as { fields: ContentFieldMap }).fields;
  const leafValue = inner[leaf];
  if (!leafValue) {
    throw new ContentEngineError(
      `publicApi.fields includes "${name}", but "${owner}" declares no leaf called "${leaf}". It has: ${Object.keys(inner).join(", ")}.`,
      { contentTypeId: id },
    );
  }

  if (!publicExposableKinds.has(leafValue.kind)) {
    throw new ContentEngineError(
      `publicApi.fields includes "${name}" of kind "${leafValue.kind}", which cannot be exposed publicly.`,
      { contentTypeId: id },
    );
  }
};

/**
 * Checks and fills in `publicApi`.
 *
 * Every rule here exists to make one guarantee cheap: if a field is not in
 * `fields`, nothing public can read it, order by it, search it or filter on it.
 * So the subset checks are not tidiness - they are what stops a filter or a
 * sort being used to probe a column the response leaves out.
 */
const resolvePublicApi = <TField extends string>(
  id: string,
  fields: ContentFieldMap,
  publicApi: ContentPublicApiConfig<TField> | undefined,
  publication: boolean,
  localizedFields: ContentFieldMap,
): ResolvedContentPublicApiConfig => {
  if (!publicApi?.enabled) {
    return {
      defaultOrder: "desc",
      defaultOrderBy: CONTENT_PUBLIC_ALWAYS_ORDERABLE,
      enabled: false,
      fields: [],
      filterableFields: [],
      orderableFields: [],
      path: "",
      searchableFields: [],
      slugField: "",
    };
  }

  if (!publication) {
    throw new ContentEngineError(
      "publicApi needs `publication: { enabled: true }`. A public API without a draft state would put every row on the internet the moment it is created.",
      { contentTypeId: id },
    );
  }

  assertPublicPath(id, publicApi.path);

  const exposed = publicApi.fields.map(String);
  if (exposed.length === 0) {
    throw new ContentEngineError(
      "publicApi.fields is empty. There is no wildcard - list the fields you mean to publish.",
      { contentTypeId: id },
    );
  }

  const duplicate = exposed.find(
    (name, position) => exposed.indexOf(name) !== position,
  );
  if (duplicate !== undefined) {
    throw new ContentEngineError(
      `publicApi.fields lists "${duplicate}" twice.`,
      { contentTypeId: id },
    );
  }

  // The localized public response carries the language it was actually served
  // in, under `locale`. A declared field of that name would shadow it, and the
  // reader would have no way to tell a Polish article from an English one served
  // through the fallback - which is the one thing that response has to say.
  if (Object.keys(localizedFields).length > 0 && exposed.includes("locale")) {
    throw new ContentEngineError(
      'publicApi.fields includes "locale", which a localized content type reserves: every public localized response carries the language it resolved to under that name. Rename the field.',
      { contentTypeId: id },
    );
  }

  for (const name of exposed) {
    if (publicExposableColumns.includes(name)) continue;

    const path = splitContentFieldPath(name);
    if (path) {
      assertPublicLeafPath(id, fields, name, path);
      continue;
    }

    const fieldValue = fields[name];
    if (!fieldValue) {
      if (publicationFields.includes(name)) {
        throw new ContentEngineError(
          `publicApi.fields includes "${name}", which cannot be exposed. Every row the public API returns is published, so it would be a constant.`,
          { contentTypeId: id },
        );
      }

      throw new ContentEngineError(
        `publicApi.fields references unknown field "${name}".`,
        { contentTypeId: id },
      );
    }

    if (fieldValue.kind === "user") {
      throw new ContentEngineError(
        `publicApi.fields includes the user field "${name}". User fields are not exposable: publishing a person by listing one word is exactly the accident this rule prevents. Write your own route with the shape you mean.`,
        { contentTypeId: id },
      );
    }

    // A group or a repeatable is never exposed whole. Naming `seo` would
    // publish `seo.indexable` because somebody wanted `seo.title`, and a field
    // added to the group later would become public without anyone deciding it
    // should - which is precisely what an allowlist with no wildcard exists to
    // stop. Its leaves are named one at a time.
    if (fieldValue.kind === "group" || fieldValue.kind === "repeatable") {
      const leaves = Object.keys(
        (fieldValue as { fields: ContentFieldMap }).fields,
      );

      throw new ContentEngineError(
        `publicApi.fields includes the ${fieldValue.kind} "${name}". A ${fieldValue.kind} is exposed one leaf at a time, so a leaf added later stays private until somebody says otherwise: list ${leaves.map(leaf => `"${name}.${leaf}"`).join(", ")} - or only the ones you mean.`,
        { contentTypeId: id },
      );
    }

    if (!publicExposableKinds.has(fieldValue.kind)) {
      throw new ContentEngineError(
        `publicApi.fields includes "${name}" of kind "${fieldValue.kind}", which cannot be exposed publicly.`,
        { contentTypeId: id },
      );
    }
  }

  const exposedSet = new Set(exposed);
  const assertExposed = (label: string, names: readonly string[]): void => {
    const missing = names.find(name => !exposedSet.has(name));
    if (missing !== undefined) {
      throw new ContentEngineError(
        `${label} includes "${missing}", which is not in publicApi.fields. A private field must not be reachable through a filter, a sort or a search either.`,
        { contentTypeId: id },
      );
    }
  };

  const searchableFields = (publicApi.searchableFields ?? []).map(String);
  assertExposed("publicApi.searchableFields", searchableFields);
  const notSearchable = searchableFields.find(name => {
    const target = resolveFieldTarget(fields, name);

    return (
      target === null ||
      target.container === "repeatable" ||
      !EXPLICIT_SEARCHABLE_KINDS.has(target.descriptor.kind)
    );
  });
  if (notSearchable !== undefined) {
    throw new ContentEngineError(
      resolveFieldTarget(fields, notSearchable)?.container === "repeatable"
        ? `publicApi.searchableFields includes the repeatable leaf "${notSearchable}", which lives on a child table rather than on the row. A list search is a predicate on the row; index it with \`search.contentFields\` instead.`
        : `publicApi.searchableFields includes "${notSearchable}", which is not a text, textarea or slug field.`,
      { contentTypeId: id },
    );
  }

  const filterableFields = (publicApi.filterableFields ?? []).map(String);
  assertExposed("publicApi.filterableFields", filterableFields);
  const notFilterable = filterableFields.find(name => {
    const target = resolveFieldTarget(fields, name);
    if (target === null || target.container === "repeatable") return true;
    // A to-many relation filters through an indexed EXISTS over its junction
    // table rather than by equality, but it is still a `relation` kind - so the
    // ordinary kind check accepts it and the query builder branches on `multiple`.

    return !isFilterableFieldKind(target.descriptor.kind);
  });
  if (notFilterable !== undefined) {
    throw new ContentEngineError(
      resolveFieldTarget(fields, notFilterable)?.container === "repeatable"
        ? `publicApi.filterableFields includes the repeatable leaf "${notFilterable}", which lives on a child table. Filtering by one would ask "does any child match", which is a different question from equality - write your own route for it.`
        : `publicApi.filterableFields includes "${notFilterable}", which is not an equality-filterable field. Filterable kinds: ${CONTENT_FILTERABLE_FIELD_KINDS.join(", ")}.`,
      { contentTypeId: id },
    );
  }

  const declaredOrderable = (publicApi.orderableFields ?? []).map(String);
  assertExposed("publicApi.orderableFields", declaredOrderable);
  const notOrderable = declaredOrderable.find(name => {
    const target = resolveFieldTarget(fields, name);

    return (
      target !== null &&
      (target.container === "repeatable" ||
        isContentRelationCollection(target.descriptor))
    );
  });
  if (notOrderable !== undefined) {
    throw new ContentEngineError(
      `publicApi.orderableFields includes "${notOrderable}", which is not one column on the row: a repeatable leaf and a to-many relation are both sets, and a list cannot be ordered by a set.`,
      { contentTypeId: id },
    );
  }
  // A localized column is not on the base table, and ordering by one would not
  // just be awkward to generate - it would be wrong. The list a reader pages
  // through would reshuffle itself for every language, and a fallback set would
  // interleave two collations, so the same cursor would mean two different
  // positions. Order by something the record has one of.
  const localizedOrderable = declaredOrderable.find(name => {
    // A leaf of a localized group is on the translation table, so it is exactly
    // as unorderable as the localized field it belongs to.
    const path = splitContentFieldPath(name);

    return localizedFields[path ? path[0] : name] !== undefined;
  });
  if (localizedOrderable !== undefined) {
    throw new ContentEngineError(
      `publicApi.orderableFields includes the localized field "${localizedOrderable}". A public list is ordered by a column of the record, not of one of its translations - ordering by a localized field would reorder the list per language and make a cursor mean two different positions across a fallback.`,
      { contentTypeId: id },
    );
  }
  const orderableFields = [
    ...new Set([...declaredOrderable, CONTENT_PUBLIC_ALWAYS_ORDERABLE]),
  ];

  const defaultOrderBy =
    publicApi.defaultOrderBy ?? CONTENT_PUBLIC_ALWAYS_ORDERABLE;
  if (!orderableFields.includes(defaultOrderBy)) {
    throw new ContentEngineError(
      `publicApi.defaultOrderBy is "${defaultOrderBy}", which is not in publicApi.orderableFields.`,
      { contentTypeId: id },
    );
  }

  const slugFields = exposed.filter(name => fields[name]?.kind === "slug");
  if (slugFields.length !== 1) {
    throw new ContentEngineError(
      slugFields.length === 0
        ? "publicApi.fields must expose exactly one slug field - it is what the public detail route resolves by. Add `field.slug({ source: ... })` and list it."
        : `publicApi.fields exposes ${slugFields.length} slug fields (${slugFields.join(", ")}). Expose exactly one, so the detail route has a single identifier.`,
      { contentTypeId: id },
    );
  }

  return {
    defaultOrder: publicApi.defaultOrder ?? "desc",
    defaultOrderBy,
    enabled: true,
    fields: exposed,
    filterableFields,
    orderableFields,
    path: publicApi.path,
    searchableFields,
    slugField: slugFields[0],
  };
};

const searchTitleKinds: ReadonlySet<string> = new Set(
  CONTENT_SEARCH_TITLE_KINDS,
);
const searchDescriptionKinds: ReadonlySet<string> = new Set(
  CONTENT_SEARCH_DESCRIPTION_KINDS,
);
const searchTextKinds: ReadonlySet<string> = new Set(CONTENT_SEARCH_TEXT_KINDS);

const disabledSearch: ResolvedContentSearchConfig = {
  contentFields: [],
  descriptionField: null,
  enabled: false,
  pathTemplate: "",
  titleField: "",
};

/**
 * Checks one indexed field name.
 *
 * The public-exposure rule is the important one, and it is checked here as well
 * as in the types because a JavaScript caller or a widened value can reach this
 * function with anything at all.
 */
const assertSearchField = ({
  allowRepeatable = false,
  exposed,
  fields,
  id,
  kinds,
  label,
  name,
}: {
  /** Whether a leaf of a child table may fill this slot. Only the body may. */
  allowRepeatable?: boolean;
  exposed: ReadonlySet<string>;
  fields: ContentFieldMap;
  id: string;
  kinds: ReadonlySet<string>;
  label: string;
  name: string;
}): void => {
  const target = resolveFieldTarget(fields, name);
  if (!target) {
    throw new ContentEngineError(
      `${label} references unknown field "${name}".`,
      { contentTypeId: id },
    );
  }

  const fieldValue = target.descriptor;

  if (target.container === "repeatable" && !allowRepeatable) {
    throw new ContentEngineError(
      `${label} names the repeatable leaf "${name}", which is many values rather than one. A heading and a description each have to be a single value; use \`search.contentFields\` for prose that repeats.`,
      { contentTypeId: id },
    );
  }

  if (!kinds.has(fieldValue.kind)) {
    throw new ContentEngineError(
      `${label} names "${name}" of kind "${fieldValue.kind}". Expected one of: ${[...kinds].sort().join(", ")}.`,
      { contentTypeId: id },
    );
  }

  if (!exposed.has(name)) {
    throw new ContentEngineError(
      `${label} names "${name}", which is not in publicApi.fields. Every indexed field must be publicly exposed - otherwise a result snippet, a highlighted match, ranking or an exact-match probe would leak a private value.`,
      { contentTypeId: id },
    );
  }
};

const assertSearchPathTemplate = (
  id: string,
  template: string,
  localized: boolean,
): void => {
  if (!template.startsWith("/")) {
    throw new ContentEngineError(
      `search.pathTemplate "${template}" must start with "/". Search result URLs are relative to the site root.`,
      { contentTypeId: id },
    );
  }

  if (template.length > CONTENT_SEARCH_PATH_MAX_LENGTH) {
    throw new ContentEngineError(
      `search.pathTemplate "${template}" is longer than ${CONTENT_SEARCH_PATH_MAX_LENGTH} characters.`,
      { contentTypeId: id },
    );
  }

  const occurrences =
    template.split(CONTENT_SEARCH_SLUG_PLACEHOLDER).length - 1;
  if (occurrences !== 1) {
    throw new ContentEngineError(
      `search.pathTemplate "${template}" must contain exactly one "${CONTENT_SEARCH_SLUG_PLACEHOLDER}" placeholder, not ${occurrences}.`,
      { contentTypeId: id },
    );
  }

  // A localized content type is indexed once per language, and two languages
  // routinely answer to the same slug - so a template with no `{locale}` would
  // give every translation of a record the same link, and a hit would point at
  // whichever language the reader happened to be in.
  const locales = template.split(CONTENT_SEARCH_LOCALE_PLACEHOLDER).length - 1;
  if (localized && locales !== 1) {
    throw new ContentEngineError(
      `search.pathTemplate "${template}" must contain exactly one "${CONTENT_SEARCH_LOCALE_PLACEHOLDER}" placeholder on a localized content type, not ${locales}. One document per language means one URL per language.`,
      { contentTypeId: id },
    );
  }
  if (!localized && locales > 0) {
    throw new ContentEngineError(
      `search.pathTemplate "${template}" uses "${CONTENT_SEARCH_LOCALE_PLACEHOLDER}", but this content type is not localized - there is no language for it to substitute.`,
      { contentTypeId: id },
    );
  }

  // Everything else that looks like a placeholder is a typo, and substitution is
  // a single literal replace - so an unvalidated one would end up in the URL.
  const rest = template
    .replace(CONTENT_SEARCH_SLUG_PLACEHOLDER, "")
    .replace(CONTENT_SEARCH_LOCALE_PLACEHOLDER, "");
  if (rest.includes("{") || rest.includes("}")) {
    throw new ContentEngineError(
      `search.pathTemplate "${template}" uses a placeholder other than "${CONTENT_SEARCH_SLUG_PLACEHOLDER}"${localized ? ` and "${CONTENT_SEARCH_LOCALE_PLACEHOLDER}"` : ""}. No other placeholder is supported.`,
      { contentTypeId: id },
    );
  }

  // Substituted with a non-empty token rather than removed, so a template whose
  // segments are placeholders (`/{locale}/articles/{slug}`) is not mistaken for
  // one with an empty segment.
  const structural = template
    .split(CONTENT_SEARCH_SLUG_PLACEHOLDER)
    .join("x")
    .split(CONTENT_SEARCH_LOCALE_PLACEHOLDER)
    .join("x");

  if (
    structural.includes("//") ||
    template.includes("..") ||
    /\s/.test(template)
  ) {
    throw new ContentEngineError(
      `search.pathTemplate "${template}" must not contain an empty segment, "..", or whitespace.`,
      { contentTypeId: id },
    );
  }
};

/**
 * Checks and fills in `search`.
 *
 * Runs after `resolvePublicApi`, because every rule here is stated in terms of
 * the resolved public allowlist and its single exposed slug field.
 */
const resolveSearch = (
  id: string,
  fields: ContentFieldMap,
  search: ContentSearchConfig | undefined,
  publicApi: ResolvedContentPublicApiConfig,
  publication: boolean,
  localized: boolean,
): ResolvedContentSearchConfig => {
  if (!search?.enabled) return disabledSearch;

  if (!publication) {
    throw new ContentEngineError(
      "search needs `publication: { enabled: true }`. Only published records are indexed, and the publication lifecycle is what drives synchronization.",
      { contentTypeId: id },
    );
  }

  if (!publicApi.enabled) {
    throw new ContentEngineError(
      "search needs `publicApi: { enabled: true, path, fields }`. A search hit links to a public URL, and every indexed field has to be published already.",
      { contentTypeId: id },
    );
  }

  if (id.length > CONTENT_SEARCH_ITEM_TYPE_MAX_LENGTH) {
    throw new ContentEngineError(
      `Content type id "${id}" is longer than ${CONTENT_SEARCH_ITEM_TYPE_MAX_LENGTH} characters, which is the width of the search index's item type column. Shorten the id or turn search off.`,
      { contentTypeId: id },
    );
  }

  const exposed = new Set(publicApi.fields);

  const { titleField } = search;
  assertSearchField({
    exposed,
    fields,
    id,
    kinds: searchTitleKinds,
    label: "search.titleField",
    name: titleField,
  });

  // A `null` title can never be a result heading, and a record whose title is
  // missing is skipped by the mapper - which shows up as a collection that never
  // reaches full coverage. Rejecting the nullable field is the cheap half of
  // that; a blank value written straight into the database is still possible, so
  // the mapper keeps its own check.
  if (resolveFieldTarget(fields, titleField)?.descriptor.nullable) {
    throw new ContentEngineError(
      `search.titleField names the nullable field "${titleField}". A search result needs a heading, so the title field must not be nullable.`,
      { contentTypeId: id },
    );
  }

  const descriptionField = search.descriptionField ?? null;
  if (descriptionField !== null) {
    assertSearchField({
      exposed,
      fields,
      id,
      kinds: searchDescriptionKinds,
      label: "search.descriptionField",
      name: descriptionField,
    });
  }

  // `Array.isArray` rather than a cast: a JavaScript caller can put anything
  // here, and a `.map` on a bare string would be a TypeError instead of the
  // error message below.
  const contentFields = Array.isArray(search.contentFields)
    ? [...search.contentFields]
    : [];
  if (contentFields.length === 0) {
    throw new ContentEngineError(
      "search.contentFields is empty. List at least one field to index - a document with only a title matches almost nothing.",
      { contentTypeId: id },
    );
  }

  const duplicate = contentFields.find(
    (name, position) => contentFields.indexOf(name) !== position,
  );
  if (duplicate !== undefined) {
    throw new ContentEngineError(
      `search.contentFields lists "${duplicate}" twice.`,
      { contentTypeId: id },
    );
  }

  for (const name of contentFields) {
    assertSearchField({
      // The body is the one slot a repeatable leaf can fill: `faq.answer` is
      // many values, and many values concatenated in position order is exactly
      // what a searchable body is made of.
      allowRepeatable: true,
      exposed,
      fields,
      id,
      kinds: searchTextKinds,
      label: "search.contentFields",
      name,
    });
  }

  assertSearchPathTemplate(id, search.pathTemplate, localized);

  return {
    contentFields,
    descriptionField,
    enabled: true,
    pathTemplate: search.pathTemplate,
    titleField,
  };
};

const disabledEditorial: ResolvedContentEditorialConfig = {
  enabled: false,
  preview: {
    enabled: false,
    expiresInMinutes: CONTENT_PREVIEW_DEFAULT_TTL_MINUTES,
    pathTemplate: null,
  },
  revisions: { retention: CONTENT_REVISION_DEFAULT_RETENTION },
  scheduling: { enabled: false },
};

/**
 * The same rules as `search.pathTemplate`, with `{token}` in place of `{slug}`.
 *
 * Deliberately not shared with it: the two differ in their placeholder and in
 * the config key their messages name, and a parameterised version would say
 * less about what the author got wrong.
 */
const assertPreviewPathTemplate = (id: string, template: string): void => {
  if (!template.startsWith("/")) {
    throw new ContentEngineError(
      `editorial.preview.pathTemplate "${template}" must start with "/". A preview URL is relative to the site root.`,
      { contentTypeId: id },
    );
  }

  if (template.length > CONTENT_PREVIEW_PATH_MAX_LENGTH) {
    throw new ContentEngineError(
      `editorial.preview.pathTemplate "${template}" is longer than ${CONTENT_PREVIEW_PATH_MAX_LENGTH} characters.`,
      { contentTypeId: id },
    );
  }

  const occurrences =
    template.split(CONTENT_PREVIEW_TOKEN_PLACEHOLDER).length - 1;
  if (occurrences !== 1) {
    throw new ContentEngineError(
      `editorial.preview.pathTemplate "${template}" must contain exactly one "${CONTENT_PREVIEW_TOKEN_PLACEHOLDER}" placeholder, not ${occurrences}.`,
      { contentTypeId: id },
    );
  }

  const rest = template.replace(CONTENT_PREVIEW_TOKEN_PLACEHOLDER, "");
  if (rest.includes("{") || rest.includes("}")) {
    throw new ContentEngineError(
      `editorial.preview.pathTemplate "${template}" uses a placeholder other than "${CONTENT_PREVIEW_TOKEN_PLACEHOLDER}". No other placeholder is supported.`,
      { contentTypeId: id },
    );
  }

  if (rest.includes("//") || template.includes("..") || /\s/.test(template)) {
    throw new ContentEngineError(
      `editorial.preview.pathTemplate "${template}" must not contain an empty segment, "..", or whitespace.`,
      { contentTypeId: id },
    );
  }
};

const assertInRange = ({
  id,
  label,
  max,
  min,
  value,
}: {
  id: string;
  label: string;
  max: number;
  min: number;
  value: number;
}): void => {
  if (!Number.isInteger(value) || value < min || value > max) {
    throw new ContentEngineError(
      `${label} must be a whole number between ${min} and ${max}, got ${value}.`,
      { contentTypeId: id },
    );
  }
};

/**
 * Checks and fills in `editorial`.
 *
 * Runs last, because both sub-features are stated in terms of capabilities the
 * other resolvers have already settled. The two dependency checks repeat what
 * the types already say, for the same reason every other one does: a JavaScript
 * caller, or a value that widened somewhere upstream, can reach this with
 * anything at all.
 */
const resolveEditorial = (
  id: string,
  editorial: ContentEditorialConfig | undefined,
  publicApi: ResolvedContentPublicApiConfig,
  publication: boolean,
): ResolvedContentEditorialConfig => {
  if (!editorial?.enabled) return disabledEditorial;

  const retention =
    editorial.revisions?.retention ?? CONTENT_REVISION_DEFAULT_RETENTION;
  assertInRange({
    id,
    label: "editorial.revisions.retention",
    max: CONTENT_REVISION_MAX_RETENTION,
    min: CONTENT_REVISION_MIN_RETENTION,
    value: retention,
  });

  // A content type id is used verbatim as `core_content_revisions.contentTypeId`,
  // which is varchar(100) - the same limit `search` enforces, and worth
  // catching here rather than at the first insert.
  if (id.length > CONTENT_SEARCH_ITEM_TYPE_MAX_LENGTH) {
    throw new ContentEngineError(
      `Content type id "${id}" is longer than ${CONTENT_SEARCH_ITEM_TYPE_MAX_LENGTH} characters, which is the limit for a revision's stored content type.`,
      { contentTypeId: id },
    );
  }

  const preview =
    editorial.preview?.enabled === true ? editorial.preview : null;
  if (preview && !publicApi.enabled) {
    throw new ContentEngineError(
      "editorial.preview needs `publicApi: { enabled: true, path, fields }`. A preview returns the public projection of a draft, so without a public allowlist there is nothing it could safely show.",
      { contentTypeId: id },
    );
  }

  const expiresInMinutes =
    preview?.expiresInMinutes ?? CONTENT_PREVIEW_DEFAULT_TTL_MINUTES;
  if (preview) {
    assertInRange({
      id,
      label: "editorial.preview.expiresInMinutes",
      max: CONTENT_PREVIEW_MAX_TTL_MINUTES,
      min: CONTENT_PREVIEW_MIN_TTL_MINUTES,
      value: expiresInMinutes,
    });

    if (preview.pathTemplate !== undefined) {
      assertPreviewPathTemplate(id, preview.pathTemplate);
    }
  }

  const scheduling = editorial.scheduling?.enabled === true;
  if (scheduling && !publication) {
    throw new ContentEngineError(
      "editorial.scheduling needs `publication: { enabled: true }`. A schedule moves `status`, and without the lifecycle there is no status to move.",
      { contentTypeId: id },
    );
  }

  return {
    enabled: true,
    preview: {
      enabled: preview !== null,
      expiresInMinutes,
      pathTemplate: preview?.pathTemplate ?? null,
    },
    revisions: { retention },
    scheduling: { enabled: scheduling },
  };
};

/**
 * Declares a content type. The result is plain data - zod and objects only -
 * so the same definition can be imported by `buildPlugin` (client) and by
 * `createContentModel` in `src/database/*.ts` (server) without dragging Drizzle
 * into a client bundle.
 */
export const defineContentType = <
  TId extends string,
  TFields extends ContentFieldsConstraint<
    TPublication,
    ContentEditorialEnabled<TEditorial>
  >,
  TPublication extends boolean = false,
  TPublicField extends ContentPublicExposableField<TFields> = never,
  TPublicEnabled extends boolean = false,
  // Inferred from the `search` literal and checked against the public allowlist.
  // The constraint is verified once every other parameter is resolved, which is
  // what makes "an indexed field is a public field" a compile error.
  // The whole `search` argument, inferred as one type. Its *constraint* is what
  // enforces the field rules, and a constraint is checked once every other
  // parameter is resolved - spelling the same unions out inside the parameter
  // type instead lets `TPublicField` fall back to its own constraint while the
  // argument is still being checked, and a private field name slips through.
  //
  // Inferring the object rather than its parts is also what preserves the
  // `enabled` literal: an intersection member is not an inference site.
  TSearch extends
    | ContentSearchConfig<
        ContentSearchTitleField<TFields, TPublicField>,
        ContentSearchDescriptionField<TFields, TPublicField>,
        ContentSearchTextField<TFields, TPublicField>
      >
    | { enabled: false } = { enabled: false },
  // The whole `editorial` argument, inferred as one type, for the same two
  // reasons `TSearch` is: its constraint is checked once `TPublicEnabled` and
  // `TPublication` are resolved - which is what makes "preview needs a public
  // API" and "scheduling needs publication" compile errors - and an
  // intersection member is not an inference site, so inferring the object is
  // the only way the three `enabled` literals survive.
  TEditorial extends
    ContentEditorialConfig<TPublicEnabled, TPublication> | { enabled: false } =
    { enabled: false },
  // The whole `localization` argument, inferred as one type, for the same reason
  // `TSearch` and `TEditorial` are: an intersection member is not an inference
  // site, so this is the only way the `enabled` literal survives - and every
  // conditional that decides whether a translation table, translation schemas
  // and a translation service exist reads that literal.
  TLocalization extends ContentLocalizationConfig | { enabled: false } = {
    enabled: false;
  },
  // The whole `delivery` argument, inferred as one type, for the same two reasons
  // `TSearch` and `TEditorial` are. Its *constraint* is what enforces the field
  // rules - a constraint is checked once `TPublicField` and `TPublicEnabled` are
  // resolved, which is what makes "delivery needs a public API" and "an SEO field
  // has to be public" compile errors rather than boot-time ones.
  TDelivery extends
    | ContentDeliveryConfig<
        TPublicEnabled,
        ContentEditorialEnabled<TEditorial>,
        ContentDeliveryTitleField<TFields, TPublicField>,
        ContentDeliveryDescriptionField<TFields, TPublicField>,
        ContentDeliveryNoIndexField<TFields, TPublicField>
      >
    | { enabled: false } = { enabled: false },
>({
  admin,
  delivery,
  editorial,
  fields,
  id,
  indexes = [],
  localization,
  publicApi,
  publication,
  search,
  tableName,
}: {
  admin: ContentAdminConfig<
    TFields,
    TPublication,
    ContentEditorialEnabled<TEditorial>
  >;
  /**
   * Opts into the delivery layer: canonical URLs, slug history, automatic
   * redirects, localized alternates, `hreflang`, SEO projection and sitemap
   * entries. Needs `publicApi`, and every SEO field it names has to be in
   * `publicApi.fields`. Omit it and nothing about the content type changes.
   */
  delivery?: TDelivery;
  /**
   * Opts into the editorial workflow: a `version` column, optimistic locking
   * and revision history, plus optional preview and scheduling. Omit it and
   * nothing changes.
   */
  editorial?: TEditorial;
  fields: TFields;
  id: TId;
  indexes?: ContentIndexInput<
    TFields,
    TPublication,
    ContentEditorialEnabled<TEditorial>
  >[];
  /**
   * Opts into per-language content: every field marked `localized: true` moves
   * into a generated `<tableName>_translations` table, one row per language.
   * Omit it and nothing changes.
   */
  localization?: TLocalization;
  /**
   * Opts into a generated read-only public API. Needs `publication` and exactly
   * one exposed slug field. Omit it and nothing public is generated.
   */
  publicApi?:
    ContentPublicApiConfig<TPublicField> | { enabled: TPublicEnabled };
  /** Opts into the draft/published lifecycle. Omit to stay on Stage 1 behaviour. */
  publication?: ContentPublicationConfig | { enabled: TPublication };
  /**
   * Opts into automatic search synchronization. Needs `publication` and
   * `publicApi`, and every indexed field must be in `publicApi.fields`. Omit it
   * and nothing is indexed.
   */
  search?: TSearch;
  tableName: string;
}): ContentTypeDefinition<
  TId,
  TFields,
  TPublication,
  TPublicField,
  TPublicEnabled,
  ContentSearchEnabled<TSearch>,
  ContentEditorialEnabled<TEditorial>,
  ContentPreviewEnabled<TEditorial>,
  ContentSchedulingEnabled<TEditorial>,
  ContentLocalizationEnabled<TLocalization>,
  ContentDeliveryEnabled<TDelivery>
> => {
  if (!CONTENT_ID_PATTERN.test(id)) {
    throw new ContentEngineError(
      `Content type id "${id}" must look like "plugin.entity" (lowercase, dot separated).`,
    );
  }

  if (!CONTENT_TABLE_NAME_PATTERN.test(tableName)) {
    throw new ContentEngineError(
      `Table name "${tableName}" must be snake_case and start with a letter.`,
      { contentTypeId: id },
    );
  }

  if (tableName.length > CONTENT_IDENTIFIER_MAX_LENGTH) {
    throw new ContentEngineError(
      `Table name "${tableName}" is longer than the Postgres identifier limit of ${CONTENT_IDENTIFIER_MAX_LENGTH} characters.`,
      { contentTypeId: id },
    );
  }

  // `ContentFieldsConstraint` only pins `kind` (see its doc comment), so widen
  // to the real descriptor union here. This is the only unchecked widening in
  // the engine, and `assertFieldKind` below makes it true at runtime for
  // anything that skipped the `field.*` builders.
  // Before the rebind, which is the only moment a supplied `target` and the
  // self-relation placeholder are still distinguishable.
  assertContentRelationTargets(id, fields as unknown as ContentFieldMap);

  const fieldMap = bindSelfRelations(
    fields as unknown as ContentFieldMap,
    // Read lazily, so `definition` is fully assigned by the time a relation
    // resolves. The widening is the same one `AnyContentTypeDefinition` exists
    // for: a self-relation's target is read by code that cannot know which
    // concrete content type it was handed.
    () => definition as unknown as AnyContentTypeDefinition,
  );
  const fieldNames = Object.keys(fieldMap);
  if (fieldNames.length === 0) {
    throw new ContentEngineError("A content type needs at least one field.", {
      contentTypeId: id,
    });
  }

  const publicationEnabled = publication?.enabled === true;
  const editorialEnabled = editorial?.enabled === true;

  for (const name of fieldNames) {
    assertFieldName(id, name, publicationEnabled, editorialEnabled);
    assertFieldKind(id, name, fieldMap[name]);
    assertField(id, name, fieldMap[name]);
  }

  assertSlugSources(id, fieldMap);

  // First, because every resolver below is stated in terms of what it produces:
  // the generated table names, and above all the one leaf-path -> column mapping
  // the indexes, the schemas, the services, the revisions, the public projection
  // and the AdminCP all read. It throws on every advanced-field mistake, so
  // nothing downstream has to defend against a half-valid group.
  const resolvedAdvanced = resolveContentAdvanced({
    fields: fieldMap,
    id,
    tableName,
  });

  // The one partition every subsystem downstream of here reads. A localized
  // field is not a column on the base table, so it takes no part in the base
  // indexes, the admin surfaces or the base schemas.
  const { collectionFields, localizedFields, sharedFields } =
    partitionContentFields(fieldMap);
  // Groups flattened into the columns they generate, which is what an index and
  // a unique constraint actually address.
  const sharedColumns = contentStorageColumns(sharedFields);
  const leafColumnByPath = new Map(
    resolvedAdvanced.leaves.map(leaf => [leaf.path, leaf.columnName]),
  );

  const knownColumns = new Set([
    ...Object.keys(sharedColumns),
    ...resolvedAdvanced.leaves
      .filter(leaf => !leaf.localized)
      .map(leaf => leaf.path),
    ...systemFields,
    ...(publicationEnabled ? publicationFields : []),
    ...(editorialEnabled ? editorialFields : []),
  ]);
  const resolvedIndexes = resolveContentIndexes({
    contentTypeId: id,
    declared: indexes.map(index => {
      const on = index.on.map(String);
      assertIndexable(id, on, fieldMap, localizedFields);
      assertKnownColumns(id, "indexes", on, knownColumns);

      // Declared in canonical paths, materialised against real columns: the
      // author writes `["seo.title"]` and the migration gets `seo_title`.
      return {
        ...index,
        on: on.map(name => leafColumnByPath.get(name) ?? name),
      };
    }),
    // Shared only: a localized slug's unique index is scoped to a language and
    // belongs to the translation table, which `resolveContentTranslationIndexes`
    // builds.
    fields: sharedColumns,
    publication: publicationEnabled,
    tableName,
  });

  const resolvedAdmin = resolveAdmin(
    id,
    { ...sharedFields, ...collectionFields },
    localizedFields,
    admin,
    publicationEnabled,
    editorialEnabled,
  );
  const permissionModule =
    admin.permissionModule ?? slugifyModule(admin.label.plural);

  if (!CONTENT_TABLE_NAME_PATTERN.test(permissionModule)) {
    throw new ContentEngineError(
      `Could not derive a permission module name from label.plural "${admin.label.plural}". Set \`admin.permissionModule\` explicitly.`,
      { contentTypeId: id },
    );
  }

  const resolvedPublicApi = resolvePublicApi(
    id,
    fieldMap,
    // The `{ enabled: TPublicEnabled }` arm of the parameter exists only so an
    // `enabled: false` literal still typechecks; `resolvePublicApi` returns the
    // disabled config for anything that is not `enabled: true`.
    publicApi as ContentPublicApiConfig<TPublicField> | undefined,
    publicationEnabled,
    localizedFields,
  );

  const resolvedSearch = resolveSearch(
    id,
    fieldMap,
    // Same shape of widening as `publicApi` above: the `{ enabled: false }` arm
    // exists only so an explicit literal typechecks.
    search as ContentSearchConfig | undefined,
    resolvedPublicApi,
    publicationEnabled,
    Object.keys(localizedFields).length > 0,
  );

  const resolvedEditorial = resolveEditorial(
    id,
    // The `{ enabled: false }` arm of the parameter exists only so an explicit
    // literal typechecks - the same widening `publicApi` and `search` do.
    editorial as ContentEditorialConfig | undefined,
    resolvedPublicApi,
    publicationEnabled,
  );

  // Last, because it reads the field partition every other resolver has already
  // been checked against. There is no capability it refuses any more: every
  // subsystem reads the language it was asked for.
  const resolvedLocalization = resolveContentLocalization({
    fields: fieldMap,
    id,
    // The `{ enabled: false }` arm exists only so an explicit literal
    // typechecks - the same widening `publicApi`, `search` and `editorial` do.
    localization: localization as ContentLocalizationConfig | undefined,
    publication: publicationEnabled,
    tableName,
  });

  // After localization, because "which language owns a historical URL" is read
  // off the field partition, and after `publicApi`, because every canonical path
  // and every SEO field is stated in terms of the resolved public allowlist.
  const resolvedDelivery = resolveContentDelivery({
    // The `{ enabled: false }` arm exists only so an explicit literal typechecks -
    // the same widening `publicApi`, `search`, `editorial` and `localization` do.
    delivery: delivery as ContentDeliveryConfig | undefined,
    // Read off the *resolved* editorial config rather than the argument, so the
    // redirect check sees exactly what `resolveEditorial` decided.
    editorial: resolvedEditorial.enabled,
    fields: fieldMap,
    id,
    localization: {
      defaultLocale: resolvedLocalization.defaultLocale,
      enabled: resolvedLocalization.enabled,
    },
    localizedFields,
    publicApi: resolvedPublicApi,
    publication: publicationEnabled,
  });

  const definition: ContentTypeDefinition<
    TId,
    TFields,
    TPublication,
    TPublicField,
    TPublicEnabled,
    ContentSearchEnabled<TSearch>,
    ContentEditorialEnabled<TEditorial>,
    ContentPreviewEnabled<TEditorial>,
    ContentSchedulingEnabled<TEditorial>,
    ContentLocalizationEnabled<TLocalization>,
    ContentDeliveryEnabled<TDelivery>
  > = {
    admin: resolvedAdmin,
    advanced: resolvedAdvanced,
    delivery: resolvedDelivery as ResolvedContentDeliveryConfig<
      ContentDeliveryEnabled<TDelivery>
    >,
    editorial: resolvedEditorial as ResolvedContentEditorialConfig<
      ContentEditorialEnabled<TEditorial>,
      ContentPreviewEnabled<TEditorial>,
      ContentSchedulingEnabled<TEditorial>
    >,
    // The rebound copy, so a self-relation resolves rather than throwing.
    fields: fieldMap as unknown as TFields,
    id,
    indexes: resolvedIndexes,
    localization: resolvedLocalization as ResolvedContentLocalizationConfig<
      ContentLocalizationEnabled<TLocalization>
    >,
    permissionModule,
    publication: {
      enabled: publicationEnabled as TPublication,
    },
    publicApi: resolvedPublicApi as ResolvedContentPublicApiConfig<
      TPublicField,
      TPublicEnabled
    >,
    schemas: buildContentSchemas<
      ContentTypeDefinition<
        TId,
        TFields,
        TPublication,
        TPublicField,
        TPublicEnabled,
        ContentSearchEnabled<TSearch>,
        ContentEditorialEnabled<TEditorial>,
        ContentPreviewEnabled<TEditorial>,
        ContentSchedulingEnabled<TEditorial>,
        ContentLocalizationEnabled<TLocalization>,
        ContentDeliveryEnabled<TDelivery>
      >
    >({
      admin: resolvedAdmin,
      advanced: resolvedAdvanced,
      editorial: editorialEnabled,
      fields: fieldMap,
      localization: resolvedLocalization,
      publicApi: resolvedPublicApi,
      publication: publicationEnabled,
    }),
    search: resolvedSearch as ResolvedContentSearchConfig<
      ContentSearchEnabled<TSearch>
    >,
    tableName,
  };

  return definition;
};

/**
 * Rebinds every `self: true` relation to the definition being built.
 *
 * On a **copy** of the field map, never in place: a descriptor object can be a
 * shared `const` reused by several content types, and mutating it would point
 * one content type's relation at another's table. The copy is what the
 * definition carries, so `field.target()` resolves correctly everywhere
 * downstream - and the thunk is read lazily, so `definition` is fully assigned
 * by the time anybody calls it.
 */
const bindSelfRelations = (
  fields: ContentFieldMap,
  self: () => AnyContentTypeDefinition,
): ContentFieldMap => {
  const bound: ContentFieldMap = {};

  for (const [name, fieldValue] of Object.entries(fields)) {
    bound[name] =
      fieldValue.kind === "relation" && fieldValue.self
        ? { ...fieldValue, target: self }
        : fieldValue;
  }

  return bound;
};
