import type {
  AnyContentTypeDefinition,
  ContentFieldDescriptor,
  ContentFieldMap,
  ContentFileField,
} from "./types";

import {
  CONTENT_ENUM_DEFAULT_LENGTH,
  CONTENT_FIELD_NAME_PATTERN,
} from "./const";
import {
  editorialFields,
  publicationFields,
  systemFields,
} from "./define-shared";
import { ContentEngineError } from "./errors";
import {
  assertContentFileMaxBytes,
  normalizeContentFileExtensions,
  normalizeContentFileMimeTypes,
} from "./files";

/** A slug can only be derived from a field that holds a single line of text. */
const SLUG_SOURCE_KINDS = new Set<ContentFieldDescriptor["kind"]>(["text"]);

/** A field with no default that is neither required nor nullable is unwritable. */
const hasWritableFallback = (fieldValue: ContentFieldDescriptor): boolean => {
  if (fieldValue.kind === "dateTime") return fieldValue.defaultNow;
  // A group is writable because its leaves are - `resolveContentAdvanced`
  // proves each of them is nullable or defaulted when the group is optional.
  // A collection is writable because the empty set is its default.
  if (fieldValue.kind === "group" || fieldValue.kind === "repeatable") {
    return true;
  }
  // A to-many reference of either kind is writable for the same reason a
  // repeatable is: the empty set is its default.
  if (fieldValue.kind === "relation" || fieldValue.kind === "user") {
    return fieldValue.multiple;
  }
  // A sourced slug has no column default and is not required, but it is always
  // writable: the service derives it from the source field.
  if (fieldValue.kind === "slug") return fieldValue.source !== undefined;
  // A file has no default and cannot have one: a column default would be a
  // `core_files.id` written into the definition, pointing at a row that exists on
  // one installation and not on the next. `assertField` says so in words.
  if (fieldValue.kind === "file") return false;

  return fieldValue.defaultValue !== undefined;
};

export const assertFieldName = (
  id: string,
  name: string,
  publication: boolean,
  editorial: boolean,
): void => {
  if (systemFields.includes(name)) {
    throw new ContentEngineError(
      `"${name}" is a reserved system column and cannot be declared as a field.`,
      { contentTypeId: id },
    );
  }

  if (publication && publicationFields.includes(name)) {
    throw new ContentEngineError(
      `"${name}" is generated by \`publication\` and cannot also be declared as a field. Rename the field, or drop \`publication\` and manage the lifecycle yourself.`,
      { contentTypeId: id },
    );
  }

  if (editorial && editorialFields.includes(name)) {
    throw new ContentEngineError(
      `"${name}" is generated by \`editorial\` and cannot also be declared as a field. Rename the field, or drop \`editorial\` and manage versioning yourself.`,
      { contentTypeId: id },
    );
  }

  if (!CONTENT_FIELD_NAME_PATTERN.test(name)) {
    throw new ContentEngineError(
      `Field "${name}" must be camelCase and start with a lowercase letter.`,
      { contentTypeId: id },
    );
  }
};

const FIELD_KINDS = new Set<string>([
  "boolean",
  "dateTime",
  "enum",
  "file",
  "group",
  "number",
  "relation",
  "repeatable",
  "slug",
  "text",
  "textarea",
  "user",
]);

/** Guards the widening of `ContentFieldsConstraint` to `ContentFieldMap`. */
export const assertFieldKind = (
  id: string,
  name: string,
  fieldValue: ContentFieldDescriptor,
): void => {
  if (!FIELD_KINDS.has(fieldValue?.kind)) {
    throw new ContentEngineError(
      `Field "${name}" is not a field descriptor. Build it with \`field.text()\`, \`field.enum()\`, and so on.`,
      { contentTypeId: id },
    );
  }
};

/**
 * Everything a `field.file()` descriptor has to satisfy, re-checked here.
 *
 * `field.file` already normalises and validates - this is the same rules applied
 * to a descriptor that skipped the builder, and the only place the error carries
 * the content type id. The normalisers are idempotent, so running them twice
 * costs nothing and proves the stored arrays really are normalised: a hand-built
 * `{ kind: "file", allowedExtensions: ["GIF"] }` would otherwise be compared
 * against `.gif` and match nothing.
 */
const assertFileField = (
  id: string,
  name: string,
  fieldValue: ContentFileField,
): void => {
  const withField = (run: () => void): void => {
    try {
      run();
    } catch (error) {
      throw new ContentEngineError(
        `Field "${name}": ${error instanceof Error ? error.message.replace("[Content Engine] ", "") : String(error)}`,
        { contentTypeId: id },
      );
    }
  };

  withField(() => {
    assertContentFileMaxBytes(fieldValue.maxBytes);
  });

  if (fieldValue.allowedExtensions !== undefined) {
    withField(() => {
      const normalized = normalizeContentFileExtensions(
        fieldValue.allowedExtensions ?? [],
      );
      if (normalized.join(",") !== fieldValue.allowedExtensions?.join(",")) {
        throw new ContentEngineError(
          `allowedExtensions is not normalised (${fieldValue.allowedExtensions?.join(", ")}). Build the field with \`field.file()\`, which lowercases and dot-prefixes every entry.`,
        );
      }
    });
  }

  if (fieldValue.allowedMimeTypes !== undefined) {
    withField(() => {
      const normalized = normalizeContentFileMimeTypes(
        fieldValue.allowedMimeTypes ?? [],
      );
      if (normalized.join(",") !== fieldValue.allowedMimeTypes?.join(",")) {
        throw new ContentEngineError(
          `allowedMimeTypes is not normalised (${fieldValue.allowedMimeTypes?.join(", ")}). Build the field with \`field.file()\`, which lowercases every entry.`,
        );
      }
    });
  }

  // Refused here rather than only by `resolveContentLocalization`, so the message
  // names the reason instead of listing the kinds that may be localized: one file
  // per language would need a translation column holding a foreign key, a
  // per-locale upload route and a per-locale deletion rule - and a cover image is
  // one image whatever language the caption is in. Translate the *alt text*.
  if (fieldValue.localized === true) {
    throw new ContentEngineError(
      `File field "${name}" is \`localized: true\`, which is not supported. A file is one object with one storage key; pair it with a localized text field for the alt text or caption instead.`,
      { contentTypeId: id },
    );
  }

  if (!fieldValue.required && !fieldValue.nullable) {
    throw new ContentEngineError(
      `File field "${name}" is neither required nor nullable, and a file field can have no default - a \`core_files.id\` baked into a definition would point at a different row on every installation. Add \`nullable: true\` (the builder's default) or \`required: true\`.`,
      { contentTypeId: id },
    );
  }
};

export const assertField = (
  id: string,
  name: string,
  fieldValue: ContentFieldDescriptor,
): void => {
  // Before the generic writability check below, which would otherwise tell the
  // author to add a default value a file field structurally cannot have.
  if (fieldValue.kind === "file") {
    assertFileField(id, name, fieldValue);
  }

  if (!fieldValue.required && !fieldValue.nullable) {
    if (!hasWritableFallback(fieldValue)) {
      throw new ContentEngineError(
        `Field "${name}" is neither required nor nullable, so it needs a default value - otherwise a row could never be inserted.`,
        { contentTypeId: id },
      );
    }
  }

  // A to-many reference is checked by `resolveContentAdvanced` instead: it is
  // never nullable by construction, and `"set null"` means something different
  // for a junction row than for a column - so the message has to be different
  // too, and there is only one place it can be.
  if (
    (fieldValue.kind === "relation" || fieldValue.kind === "user") &&
    !fieldValue.multiple
  ) {
    // Postgres would accept the definition and then fail at delete time, when
    // it tries to write NULL into a NOT NULL column.
    if (fieldValue.onDelete === "set null" && !fieldValue.nullable) {
      throw new ContentEngineError(
        `Field "${name}" is \`onDelete: "set null"\` but not nullable, so deleting the referenced row would violate NOT NULL. Add \`nullable: true\`, or switch to \`onDelete: "restrict"\` or \`"cascade"\`.`,
        { contentTypeId: id },
      );
    }
  }

  if (fieldValue.kind === "text" || fieldValue.kind === "textarea") {
    const { maxLength, minLength } = fieldValue;
    if (maxLength !== undefined && maxLength <= 0) {
      throw new ContentEngineError(
        `Field "${name}" has a maxLength of ${maxLength}; it must be positive.`,
        { contentTypeId: id },
      );
    }
    if (
      minLength !== undefined &&
      maxLength !== undefined &&
      minLength > maxLength
    ) {
      throw new ContentEngineError(
        `Field "${name}" has minLength ${minLength} greater than maxLength ${maxLength}.`,
        { contentTypeId: id },
      );
    }
  }

  if (fieldValue.kind === "slug") {
    const { maxLength } = fieldValue;
    if (maxLength !== undefined && maxLength <= 0) {
      throw new ContentEngineError(
        `Field "${name}" has a maxLength of ${maxLength}; it must be positive.`,
        { contentTypeId: id },
      );
    }
  }

  if (fieldValue.kind === "number") {
    const { max, min } = fieldValue;
    if (min !== undefined && max !== undefined && min > max) {
      throw new ContentEngineError(
        `Field "${name}" has min ${min} greater than max ${max}.`,
        { contentTypeId: id },
      );
    }
  }

  if (fieldValue.kind === "enum") {
    const { defaultValue, length = CONTENT_ENUM_DEFAULT_LENGTH } = fieldValue;
    const values: readonly string[] = fieldValue.values;

    if (values.length === 0) {
      throw new ContentEngineError(
        `Field "${name}" needs at least one value.`,
        {
          contentTypeId: id,
        },
      );
    }
    if (new Set(values).size !== values.length) {
      throw new ContentEngineError(
        `Field "${name}" has duplicate enum values.`,
        { contentTypeId: id },
      );
    }
    const tooLong = values.find(value => value.length > length);
    if (tooLong !== undefined) {
      throw new ContentEngineError(
        `Field "${name}" value "${tooLong}" is longer than the column length ${length}. Raise \`length\` on the field.`,
        { contentTypeId: id },
      );
    }
    if (defaultValue !== undefined && !values.includes(defaultValue)) {
      throw new ContentEngineError(
        `Field "${name}" has default "${defaultValue}", which is not one of its values.`,
        { contentTypeId: id },
      );
    }
  }
};

/**
 * Checks every `field.slug({ source })` against the field map.
 *
 * Runs after the per-field pass, because a source is a reference to a *sibling*
 * field and nothing can see the whole map until then.
 */
export const assertSlugSources = (
  id: string,
  fields: ContentFieldMap,
): void => {
  for (const [name, fieldValue] of Object.entries(fields)) {
    if (fieldValue.kind !== "slug" || fieldValue.source === undefined) continue;

    const source = fields[fieldValue.source];
    if (!source) {
      throw new ContentEngineError(
        `Slug field "${name}" is sourced from "${fieldValue.source}", which is not a field on this content type.`,
        { contentTypeId: id },
      );
    }

    if (!SLUG_SOURCE_KINDS.has(source.kind)) {
      throw new ContentEngineError(
        `Slug field "${name}" is sourced from "${fieldValue.source}", which is a "${source.kind}" field. A slug can only be derived from a text field.`,
        { contentTypeId: id },
      );
    }
  }
};

/**
 * Rebinds every `self: true` relation to the definition being built.
 *
 * On a **copy** of the field map, never in place: a descriptor object can be a
 * shared `const` reused by several content types, and mutating it would point
 * one content type's relation at another's table. The copy is what the
 * definition carries, so `field.target()` resolves correctly everywhere
 * downstream - and the thunk is read lazily, so `definition` is fully assigned
 * by the time anybody calls it.
 */
export const bindSelfRelations = (
  fields: ContentFieldMap,
  self: () => AnyContentTypeDefinition,
): ContentFieldMap => {
  const bound: ContentFieldMap = {};

  for (const [name, fieldValue] of Object.entries(fields)) {
    bound[name] =
      fieldValue.kind === "relation" && fieldValue.self
        ? { ...fieldValue, target: self }
        : fieldValue;
  }

  return bound;
};
