import { assertType, describe, expectTypeOf, it } from "vitest";

import type { testCategoryContentType } from "@/tests/content-fixtures";

import {
  testArticleContentType,
  testPostContentType,
} from "@/tests/content-fixtures";

import type {
  AnyContentTypeDefinition,
  ContentCreateInput,
  ContentFilterInput,
  ContentOrderableFieldName,
  ContentPublicationStatus,
  ContentSelect,
  ContentUpdateInput,
} from "./types";

import { defineContentType } from "./define";
import { field } from "./fields";

type Post = typeof testPostContentType;
type Article = typeof testArticleContentType;
type Category = typeof testCategoryContentType;

describe("publication", () => {
  // The whole Stage 2 type design rests on this: adding type parameters to
  // `ContentTypeDefinition` must not break the erased form that every relation
  // thunk, registry and route builder is written against.
  describe("assignability to AnyContentTypeDefinition", () => {
    it("holds for a publication content type", () => {
      expectTypeOf<Post>().toExtend<AnyContentTypeDefinition>();
      assertType<AnyContentTypeDefinition>(testPostContentType);
    });

    it("still holds for a Stage 1 content type", () => {
      expectTypeOf<Article>().toExtend<AnyContentTypeDefinition>();
      assertType<AnyContentTypeDefinition>(testArticleContentType);
    });
  });

  describe("the enabled flag stays literal", () => {
    it("is `true` when opted in", () => {
      expectTypeOf(
        testPostContentType.publication.enabled,
      ).toEqualTypeOf<true>();
    });

    it("is `false` when omitted", () => {
      expectTypeOf(
        testArticleContentType.publication.enabled,
      ).toEqualTypeOf<false>();
    });
  });

  describe("select output", () => {
    it("gains the two generated columns", () => {
      expectTypeOf<
        ContentSelect<Post>["status"]
      >().toEqualTypeOf<ContentPublicationStatus>();
      // Spelled out as well as via the alias: the literal pair is the contract
      // the filter schema, the badge and the SQL default all depend on.
      expectTypeOf<ContentSelect<Post>["status"]>().toEqualTypeOf<
        "draft" | "published"
      >();
      expectTypeOf<
        ContentSelect<Post>["publishedAt"]
      >().toEqualTypeOf<Date | null>();
    });

    it("leaves a Stage 1 content type's own fields alone", () => {
      // Declared as an enum with three values, not the generated two.
      expectTypeOf<ContentSelect<Article>["status"]>().toEqualTypeOf<
        "archived" | "draft" | "published"
      >();
    });

    it("adds nothing to a content type without publication", () => {
      const plain = defineContentType({
        id: "test.plain",
        tableName: "test_plain",
        fields: { title: field.text({ required: true }) },
        admin: { label: { plural: "Plains", singular: "Plain" } },
      });

      expectTypeOf(plain.publication.enabled).toEqualTypeOf<false>();
      expectTypeOf<keyof ContentSelect<typeof plain>>().toEqualTypeOf<
        "createdAt" | "id" | "title" | "updatedAt"
      >();
    });
  });

  describe("write input", () => {
    it("never exposes the generated columns", () => {
      expectTypeOf<ContentCreateInput<Post>>().not.toHaveProperty("status");
      expectTypeOf<ContentCreateInput<Post>>().not.toHaveProperty(
        "publishedAt",
      );
      expectTypeOf<ContentUpdateInput<Post>>().not.toHaveProperty("status");
      expectTypeOf<ContentUpdateInput<Post>>().not.toHaveProperty(
        "publishedAt",
      );

      assertType<ContentCreateInput<Post>>({
        title: "Hello",
        category: 1,
        // @ts-expect-error - publishing is not a field update
        status: "published",
      });
    });
  });

  describe("reserved field names", () => {
    it("rejects `status` and `publishedAt` once publication is enabled", () => {
      defineContentType({
        id: "test.clash",
        tableName: "test_clash",
        fields: {
          title: field.text({ required: true }),
          // @ts-expect-error - generated by `publication`
          status: field.enum({ values: ["a", "b"], defaultValue: "a" }),
        },
        publication: { enabled: true },
        admin: { label: { plural: "Clashes", singular: "Clash" } },
      });
    });

    it("still allows them without publication", () => {
      defineContentType({
        id: "test.no-clash",
        tableName: "test_no_clash",
        fields: {
          title: field.text({ required: true }),
          status: field.enum({ values: ["a", "b"], defaultValue: "a" }),
          publishedAt: field.dateTime({ nullable: true }),
        },
        admin: { label: { plural: "Fine", singular: "Fine" } },
      });
    });
  });

  describe("admin config", () => {
    it("accepts the generated columns once enabled", () => {
      defineContentType({
        id: "test.columns",
        tableName: "test_columns",
        fields: { title: field.text({ required: true }) },
        publication: { enabled: true },
        admin: {
          label: { plural: "Columns", singular: "Column" },
          list: {
            columns: ["status", "title", "publishedAt"],
            defaultOrderBy: "publishedAt",
          },
        },
      });
    });

    it("rejects them when publication is off", () => {
      defineContentType({
        id: "test.no-columns",
        tableName: "test_no_columns",
        fields: { title: field.text({ required: true }) },
        admin: {
          label: { plural: "Columns", singular: "Column" },
          // @ts-expect-error - `status` is not a column of this content type
          list: { columns: ["status", "title"] },
        },
      });
    });
  });

  // The call-site versions of these live in `server/service.test-d.ts`; these
  // pin the type aliases themselves, which is what the generated routes and any
  // hand-written query build on.
  describe("derived type aliases", () => {
    it("adds the generated columns to the orderable union", () => {
      expectTypeOf<ContentOrderableFieldName<Post>>().toEqualTypeOf<
        | "author"
        | "category"
        | "createdAt"
        | "excerpt"
        | "id"
        | "publishedAt"
        | "status"
        | "title"
        | "updatedAt"
        | "views"
      >();
    });

    it("leaves the union alone without publication", () => {
      expectTypeOf<ContentOrderableFieldName<Category>>().toEqualTypeOf<
        "createdAt" | "id" | "title" | "updatedAt"
      >();
    });

    it("adds a status filter typed to the generated pair", () => {
      expectTypeOf<ContentFilterInput<Post>["status"]>().toEqualTypeOf<
        "draft" | "published" | undefined
      >();
    });

    it("adds no status filter without publication", () => {
      expectTypeOf<ContentFilterInput<Category>>().not.toHaveProperty("status");
    });

    it("keeps a Stage 1 content type's own status filter literal", () => {
      // Declared as a three-value enum, and untouched by publication.
      expectTypeOf<ContentFilterInput<Article>["status"]>().toEqualTypeOf<
        "archived" | "draft" | "published" | undefined
      >();
    });
  });
});
