// @vitest-environment node
import { describe, expect, it } from "vitest";

import {
  testArticleContentType,
  testPostContentType,
} from "@/tests/content-fixtures";

import type { AnyContentTypeDefinition } from "./types";

import { CONTENT_PERMISSIONS } from "./const";
import { defineContentType } from "./define";
import { ContentEngineError } from "./errors";
import { field } from "./fields";
import { contentPermissionEntries, orderableColumns } from "./registry";

// Building definitions through `Partial<Parameters<...>>` erases the inferred
// field map down to the bare constraint, so the result no longer satisfies
// `AnyContentTypeDefinition`. Real call sites keep their concrete map; this
// widening exists only for the test helper, exactly as in `registry.test.ts`.
const define = (
  overrides: Partial<Parameters<typeof defineContentType>[0]> = {},
): AnyContentTypeDefinition =>
  defineContentType({
    id: "test.thing",
    tableName: "test_things",
    fields: { title: field.text({ required: true }) },
    admin: { label: { plural: "Things", singular: "Thing" } },
    ...overrides,
  }) as AnyContentTypeDefinition;

describe("publication config", () => {
  it("is off unless asked for", () => {
    expect(define().publication.enabled).toBe(false);
    expect(testArticleContentType.publication.enabled).toBe(false);
  });

  it("is on when opted in", () => {
    expect(testPostContentType.publication.enabled).toBe(true);
  });

  describe("reserved field names", () => {
    it.each(["status", "publishedAt"])(
      "rejects a field called %s once publication is enabled",
      name => {
        expect(() =>
          define({
            fields: {
              title: field.text({ required: true }),
              [name]: field.text({ nullable: true }),
            },
            publication: { enabled: true },
          }),
        ).toThrow(ContentEngineError);
      },
    );

    it("names the fix in the error", () => {
      expect(() =>
        define({
          fields: {
            title: field.text({ required: true }),
            status: field.text({ nullable: true }),
          },
          publication: { enabled: true },
        }),
      ).toThrow(/generated by `publication`/);
    });

    // The whole reason reservation is conditional: plenty of Stage 1 content
    // types - the example plugin included, until this change - declare their
    // own `status`.
    it("leaves both names available without publication", () => {
      expect(() =>
        define({
          fields: {
            title: field.text({ required: true }),
            status: field.enum({ values: ["a", "b"], defaultValue: "a" }),
            publishedAt: field.dateTime({ nullable: true }),
          },
        }),
      ).not.toThrow();
    });
  });

  describe("admin config", () => {
    it("puts the status column first by default", () => {
      const definition = define({ publication: { enabled: true } });

      expect(definition.admin.list.columns).toEqual([
        "status",
        "title",
        "updatedAt",
      ]);
    });

    it("leaves the default columns alone without publication", () => {
      expect(define().admin.list.columns).toEqual(["title", "updatedAt"]);
    });

    it("accepts the generated columns in an explicit list", () => {
      const definition = define({
        admin: {
          label: { plural: "Things", singular: "Thing" },
          list: { columns: ["publishedAt", "title"] },
        },
        publication: { enabled: true },
      });

      expect(definition.admin.list.columns).toEqual(["publishedAt", "title"]);
    });

    it("rejects them when publication is off", () => {
      expect(() =>
        define({
          admin: {
            label: { plural: "Things", singular: "Thing" },
            list: { columns: ["status", "title"] },
          },
        }),
      ).toThrow(/unknown field "status"/);
    });

    it("allows ordering by a generated column without an allowlist entry", () => {
      const definition = define({
        admin: {
          label: { plural: "Things", singular: "Thing" },
          list: { defaultOrderBy: "publishedAt" },
        },
        publication: { enabled: true },
      });

      expect(definition.admin.list.defaultOrderBy).toBe("publishedAt");
    });

    it("still rejects an unlisted ordinary field as defaultOrderBy", () => {
      expect(() =>
        define({
          admin: {
            label: { plural: "Things", singular: "Thing" },
            list: { defaultOrderBy: "title" },
          },
          publication: { enabled: true },
        }),
      ).toThrow(/admin.list.orderableFields/);
    });
  });

  describe("generated indexes", () => {
    it("adds one composite index serving the published predicate", () => {
      const names = define({ publication: { enabled: true } }).indexes.map(
        index => index.name,
      );

      expect(names).toContain("test_things_status_published_at_idx");
    });

    it("adds nothing without publication", () => {
      expect(define().indexes.map(index => index.name)).not.toContain(
        "test_things_status_published_at_idx",
      );
    });

    it("collapses a declared index on the same columns", () => {
      const indexes = define({
        indexes: [{ name: "things_live", on: ["status", "publishedAt"] }],
        publication: { enabled: true },
      }).indexes.filter(index => index.on.join() === "status,publishedAt");

      expect(indexes).toEqual([
        { name: "things_live", on: ["status", "publishedAt"], unique: false },
      ]);
    });
  });

  describe("generated schemas", () => {
    const definition = define({ publication: { enabled: true } });

    it("returns the two columns in select", () => {
      const parsed = definition.schemas.selectObject.parse({
        createdAt: new Date(),
        id: 1,
        publishedAt: null,
        status: "draft",
        title: "Hello",
        updatedAt: new Date(),
      });

      expect(parsed).toMatchObject({ publishedAt: null, status: "draft" });
    });

    it("rejects a status outside the generated pair", () => {
      expect(() =>
        definition.schemas.selectObject.parse({
          createdAt: new Date(),
          id: 1,
          publishedAt: null,
          status: "archived",
          title: "Hello",
          updatedAt: new Date(),
        }),
      ).toThrow();
    });

    it.each(["create", "update"] as const)(
      "refuses to let %s touch them",
      key => {
        expect(() =>
          definition.schemas[key].parse({ status: "published", title: "Hi" }),
        ).toThrow();
      },
    );

    it("filters by status", () => {
      expect(definition.schemas.filters.parse({ status: "published" })).toEqual(
        { status: "published" },
      );
    });

    it("has no status filter without publication", () => {
      expect(define().schemas.filters.parse({ status: "published" })).toEqual(
        {},
      );
    });
  });

  describe("orderable columns", () => {
    it("always allows the generated columns", () => {
      expect(
        orderableColumns(define({ publication: { enabled: true } })),
      ).toEqual(["id", "createdAt", "updatedAt", "status", "publishedAt"]);
    });

    it("does not invent them otherwise", () => {
      expect(orderableColumns(define())).toEqual([
        "id",
        "createdAt",
        "updatedAt",
      ]);
    });
  });

  describe("permissions", () => {
    const permissions = (
      definition?: Parameters<typeof contentPermissionEntries>[0],
    ) =>
      contentPermissionEntries(definition).map(entry =>
        typeof entry === "string" ? entry : entry.permission,
      );

    it("adds can_publish for a publication content type", () => {
      expect(permissions(define({ publication: { enabled: true } }))).toEqual([
        "can_view",
        "can_create",
        "can_edit",
        "can_delete",
        "can_publish",
      ]);
    });

    it("leaves the Stage 1 set untouched otherwise", () => {
      expect(permissions(define())).toEqual([
        "can_view",
        "can_create",
        "can_edit",
        "can_delete",
      ]);
      expect(permissions()).toHaveLength(4);
    });

    it("depends on can_view, like every other generated permission", () => {
      const publish = contentPermissionEntries(
        define({ publication: { enabled: true } }),
      ).find(
        entry =>
          typeof entry !== "string" &&
          entry.permission === CONTENT_PERMISSIONS.publish,
      );

      expect(publish).toEqual({
        dependsOn: ["can_view"],
        permission: "can_publish",
      });
    });
  });
});
