import type { ResolvedAdminNavModule } from "./types.js";

import { toSingleQuotedLiteral } from "../plugin-routes/resolve.js";

/** Where the generated file imports its type from. */
const TYPES_SPECIFIER = "@vitnode/core/lib/plugin";

/**
 * The generated file's header.
 *
 * `eslint-disable` and the "do not format" line are not decoration: the file is
 * rewritten on every build, so anything a linter or a formatter changes in it is
 * lost.
 */
const HEADER = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
// \`vite dev\` and \`vite build\`, from one input: the plugins configured in
// \`src/vitnode.config.ts\`, and which of them export an \`admin/nav\` module.
//
// Same plugin configuration in, same bytes out: the entries are sorted by
// plugin id.

import type { AdminNavPluginSource } from '${TYPES_SPECIFIER}'
`;

/**
 * The doc comment on the export, written into the generated file.
 *
 * Long, and on purpose: this is the module somebody opens when the AdminCP
 * sidebar is missing a plugin, and the answer - "that plugin does not export
 * `admin/nav`" - is not guessable from an array of two entries.
 */
const BODY_DOC = `
/**
 * Every configured plugin's AdminCP navigation, as browser-safe data.
 *
 * A plugin appears here by exporting \`admin/nav\`, and a plugin that does not
 * contributes no sidebar entries. That is not an error - most plugins have
 * nothing to put in the AdminCP - and it is checked at build time rather than
 * discovered in a browser: the specifiers below are literal, so a bundler
 * resolves them and nothing is reached through a computed string.
 *
 * This is deliberately **not** the plugin's frontend registration.
 * \`blogPlugin()\` and friends register content types with their editing screens
 * attached - an editor field, a form layout, a table cell - the whole of core's
 * form stack. A sidebar needs ids, hrefs, permissions, icons and content type
 * definitions, all of which are plain data, so that is all this carries. See
 * \`AdminNavPluginSource\`.
 *
 * Navigation is not derived from the route manifest and never will be: a nav
 * entry may point at a plugin route, at a legacy screen, or at another origin,
 * and a plugin route may deliberately have no entry at all.
 */
export const pluginAdminNav`;

const importLines = (modules: ResolvedAdminNavModule[]): string =>
  modules
    .map(
      (module, index) =>
        `import { adminNav as adminNav${index} } from ${toSingleQuotedLiteral(module.specifier)}`,
    )
    .join("\n");

/**
 * The source of an app's AdminCP navigation projection.
 *
 * A string rather than a file, so the one part of this that has to be exactly
 * reproducible is a pure function of its input and can be asserted byte for
 * byte. Writing it - and deciding whether it changed - belongs to the build tool
 * that has a filesystem.
 *
 * Sorted by plugin id here rather than trusted to arrive that way, so "same
 * configuration, same bytes" is a property of this function rather than a
 * promise about how it is called. The aliases are positional for the same
 * reason: a plugin id is not an identifier, and deriving one would mean two
 * plugins whose ids differ only in punctuation colliding silently.
 */
export const generateAdminNavSource = (
  modules: readonly ResolvedAdminNavModule[],
): string => {
  const sorted = [...modules].sort((a, b) =>
    a.pluginId === b.pluginId ? 0 : a.pluginId < b.pluginId ? -1 : 1,
  );

  if (sorted.length === 0) {
    return `${HEADER}${BODY_DOC}: AdminNavPluginSource[] = []\n`;
  }

  const entries = sorted
    .map((module, index) => `  adminNav${index}, // ${module.pluginId}`)
    .join("\n");

  return `${HEADER}\n${importLines(sorted)}\n${BODY_DOC} = [\n${entries}\n] satisfies AdminNavPluginSource[]\n`;
};
