import { describe, expect, it } from "vitest";

import { generateAdminNavSource } from "./generate";

describe("generateAdminNavSource", () => {
  it("writes an empty projection when no plugin has navigation", () => {
    const source = generateAdminNavSource([]);

    expect(source).toContain(
      "export const pluginAdminNav: AdminNavPluginSource[] = []",
    );
    // Nothing to import, so nothing is imported: a stray alias would be an
    // unused binding in an app's own `src/`.
    expect(source).not.toContain("import { adminNav");
  });

  it("imports one module per plugin, by literal specifier", () => {
    const source = generateAdminNavSource([
      { pluginId: "@vitnode/example", specifier: "@vitnode/example/admin/nav" },
    ]);

    expect(source).toContain(
      "import { adminNav as adminNav0 } from '@vitnode/example/admin/nav'",
    );
    expect(source).toContain("satisfies AdminNavPluginSource[]");
  });

  /**
   * Sorted here rather than trusted to arrive sorted, so the ordering is a
   * property of the function instead of a promise about how it is called.
   */
  it("is the same bytes whichever order the plugins arrive in", () => {
    const modules = [
      { pluginId: "@vitnode/example", specifier: "@vitnode/example/admin/nav" },
      { pluginId: "@vitnode/blog", specifier: "@vitnode/blog/admin/nav" },
    ];

    expect(generateAdminNavSource(modules)).toBe(
      generateAdminNavSource([...modules].reverse()),
    );
    expect(
      generateAdminNavSource(modules).indexOf("@vitnode/blog"),
    ).toBeLessThan(generateAdminNavSource(modules).indexOf("@vitnode/example"));
  });

  it("gives each module its own alias", () => {
    const source = generateAdminNavSource([
      { pluginId: "@vitnode/blog", specifier: "@vitnode/blog/admin/nav" },
      { pluginId: "@vitnode/example", specifier: "@vitnode/example/admin/nav" },
    ]);

    expect(source).toContain("adminNav as adminNav0");
    expect(source).toContain("adminNav as adminNav1");
    expect(source).toContain("  adminNav0, // @vitnode/blog");
    expect(source).toContain("  adminNav1, // @vitnode/example");
  });

  it("tells whoever opens it not to edit it", () => {
    const source = generateAdminNavSource([]);

    expect(source.startsWith("/* eslint-disable */")).toBe(true);
    expect(source).toContain("generated by VitNode");
  });
});
