// @vitest-environment node
import { describe, expect, it } from "vitest";

import type { ResolvedPluginRoutesModule } from "./types.js";

import { generatePluginRoutesSource } from "./generate.js";

/**
 * The one file an application holds, asserted byte for byte.
 *
 * Byte for byte rather than "contains", for the two properties the file has to
 * have: the same plugin configuration produces the same bytes on any machine -
 * because the file lives in `src/` and a rewrite of identical bytes would trip
 * the dev server's watcher - and every specifier in it is a *literal*, because a
 * bundler cannot follow anything else.
 */
const modules = (...pluginIds: string[]): ResolvedPluginRoutesModule[] =>
  pluginIds.map(pluginId => ({ pluginId, specifier: `${pluginId}/routes` }));

const HEADER = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
// \`vite dev\` and \`vite build\`, from one input: the plugins configured in
// \`src/vitnode.config.ts\`. Each one that exports a \`routes\` module is imported
// below, statically, because a route tree is small browser-safe data - a path,
// a shell, a message list, and one \`lazy(() => import(...))\` per page.
//
// No page or layout module is named here. Each one is reached only through the
// literal \`import()\` inside its own plugin's \`lazy()\` call, which Vite follows
// at build time and Rollup gives a chunk of its own - so no plugin page is in
// the initial bundle and none is reached through a computed string.
//
// Same plugin configuration in, same bytes out: the plugins are sorted by id.

import type { PluginRouteDeclarationSource } from '@vitnode/core/routing'

`;

const body = (literal: string) => `/**
 * Every configured plugin's route tree.
 *
 * Handed to \`pluginRouteSpecs\` in the app's router, which flattens and validates
 * it with the same functions the build used - so the tree the router mounts is
 * provably the tree the build checked, and a plugin removed from the config
 * takes its routes with it in one step.
 *
 * \`satisfies\` rather than a type annotation, deliberately: it checks each
 * plugin's \`routes\` export really is a \`definePluginRoutes\` tree, naming the
 * plugin here rather than failing in a browser.
 */
export const pluginRouteSources = ${literal} as const satisfies readonly PluginRouteDeclarationSource[]
`;

describe("generatePluginRoutesSource", () => {
  it("emits one static import per plugin", () => {
    expect(generatePluginRoutesSource(modules("@vitnode/example"))).toBe(
      `${HEADER}import { routes as pluginRoutes0 } from '@vitnode/example/routes'

${body(`[
  {
    pluginId: '@vitnode/example',
    routes: pluginRoutes0,
  },
]`)}`,
    );
  });

  it("emits an empty literal and no imports for an app with no plugin routes", () => {
    expect(generatePluginRoutesSource([])).toBe(`${HEADER}${body("[]")}`);
  });

  it("is byte-for-byte stable across calls", () => {
    const once = generatePluginRoutesSource(modules("a", "b"));

    expect(generatePluginRoutesSource(modules("a", "b"))).toBe(once);
  });

  it("does not depend on the order the plugins were configured in", () => {
    expect(generatePluginRoutesSource(modules("@acme/blog", "z-plugin"))).toBe(
      generatePluginRoutesSource(modules("z-plugin", "@acme/blog")),
    );
  });

  it("numbers the imports by the sorted order", () => {
    const source = generatePluginRoutesSource(modules("z-plugin", "a-plugin"));

    expect(source).toContain(
      "import { routes as pluginRoutes0 } from 'a-plugin/routes'",
    );
    expect(source).toContain(
      "import { routes as pluginRoutes1 } from 'z-plugin/routes'",
    );
    expect(source.indexOf("pluginId: 'a-plugin'")).toBeLessThan(
      source.indexOf("pluginId: 'z-plugin'"),
    );
  });

  /**
   * The property the whole design rests on: a page module is never named by the
   * app. Only the plugin's small declaration module is imported, and every page
   * is reached through the `import()` inside that plugin's own `lazy()` call.
   */
  it("names no page module, and contains no dynamic import at all", () => {
    const source = generatePluginRoutesSource(modules("@vitnode/example"));
    const code = source
      .replace(/\/\*[\s\S]*?\*\//g, "")
      .replace(/^\/\/.*$/gm, "");

    expect(code).not.toContain("import(");
    expect(code).not.toContain("pages/");
    expect(code.match(/^import \{/gm)).toHaveLength(1);
  });

  it("rejects the same plugin twice, whichever caller assembled the list", () => {
    expect(() =>
      generatePluginRoutesSource(modules("@acme/blog", "@acme/blog")),
    ).toThrow(/Two plugins claim the same id/);
  });

  it("escapes a specifier that somehow reached it unvalidated", () => {
    expect(
      generatePluginRoutesSource([
        { pluginId: "odd", specifier: "od'd/routes" },
      ]),
    ).toContain("from 'od\\'d/routes'");
  });
});
