import type { ResolvedPluginRoutesModule } from "./types.js";

import {
  sortAndAssertUniquePlugins,
  toSingleQuotedLiteral,
} from "./resolve.js";

/** Where the generated file imports its type from. */
const TYPES_SPECIFIER = "@vitnode/core/routing";

/**
 * The generated file's header.
 *
 * `eslint-disable` and the "do not format" line are not decoration: the file is
 * rewritten on every build, so anything a linter or a formatter changes in it is
 * lost, and a formatter that reflows one entry would make the output depend on
 * how long a plugin's name happens to be. It is excluded from both in the app
 * that receives it, and this says so at the top for whoever opens it anyway.
 */
const HEADER = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
// \`vite dev\` and \`vite build\`, from one input: the plugins configured in
// \`src/vitnode.config.ts\`. Each one that exports a \`routes\` module is imported
// below, statically, because a route tree is small browser-safe data - a path,
// a shell, a message list, and one \`lazy(() => import(...))\` per page.
//
// No page or layout module is named here. Each one is reached only through the
// literal \`import()\` inside its own plugin's \`lazy()\` call, which Vite follows
// at build time and Rollup gives a chunk of its own - so no plugin page is in
// the initial bundle and none is reached through a computed string.
//
// Same plugin configuration in, same bytes out: the plugins are sorted by id.

import type { PluginRouteDeclarationSource } from '${TYPES_SPECIFIER}'

`;

const BODY = `/**
 * Every configured plugin's route tree.
 *
 * Handed to \`pluginRouteSpecs\` in the app's router, which flattens and validates
 * it with the same functions the build used - so the tree the router mounts is
 * provably the tree the build checked, and a plugin removed from the config
 * takes its routes with it in one step.
 *
 * \`satisfies\` rather than a type annotation, deliberately: it checks each
 * plugin's \`routes\` export really is a \`definePluginRoutes\` tree, naming the
 * plugin here rather than failing in a browser.
 */
export const pluginRouteSources = `;

const FOOTER = ` as const satisfies readonly PluginRouteDeclarationSource[]
`;

/**
 * The static imports of each plugin's route declarations.
 *
 * Numbered rather than named after the plugin, because a package name contains
 * characters an identifier may not - and a positional name that is only ever
 * used a few lines below is easier to check than an escaping rule.
 */
const importLines = (
  modules: readonly ResolvedPluginRoutesModule[],
): string => {
  if (modules.length === 0) return "";

  return `${modules
    .map(
      (module, index) =>
        `import { routes as pluginRoutes${String(index)} } from ${toSingleQuotedLiteral(module.specifier)}`,
    )
    .join("\n")}\n\n`;
};

const sourcesLiteral = (
  modules: readonly ResolvedPluginRoutesModule[],
): string => {
  if (modules.length === 0) return "[]";

  const entries = modules.map((module, index) =>
    [
      "  {",
      `    pluginId: ${toSingleQuotedLiteral(module.pluginId)},`,
      `    routes: pluginRoutes${String(index)},`,
      "  },",
    ].join("\n"),
  );

  return `[\n${entries.join("\n")}\n]`;
};

/**
 * The source of an app's plugin route registry.
 *
 * A string rather than a file, so the one part of this that has to be exactly
 * reproducible is a pure function of its input and can be asserted byte for
 * byte. Writing it - and deciding whether it changed - belongs to the build tool
 * that has a filesystem.
 *
 * Sorted and de-duplicated on the way in, so "same configuration, same bytes" is
 * a property of this function rather than a promise about how it is called.
 */
export const generatePluginRoutesSource = (
  modules: readonly ResolvedPluginRoutesModule[],
): string => {
  const sorted = sortAndAssertUniquePlugins(modules);

  return [
    HEADER,
    importLines(sorted),
    BODY,
    sourcesLiteral(sorted),
    FOOTER,
  ].join("");
};
