import { describe, expect, it } from "vitest";

import { generatePluginRouteRegistrySource } from "./generate.js";
import { resolvePluginRouteModules } from "./resolve.js";

const generate = (
  sources: { pluginId: string; routes: { entry: string; id: string }[] }[],
): string =>
  generatePluginRouteRegistrySource(resolvePluginRouteModules(sources));

const EXAMPLE = [
  {
    pluginId: "@vitnode/example",
    routes: [{ entry: "routes/example-page", id: "example-page" }],
  },
];

describe("generatePluginRouteRegistrySource", () => {
  it("emits the registry for one plugin route", () => {
    expect(generate(EXAMPLE)).toMatchInlineSnapshot(`
      "/* eslint-disable */

      // This file is generated by VitNode. Do not edit it, and do not format it.
      //
      // It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
      // \`vite dev\` and \`vite build\`, from two inputs and nothing else: the plugins
      // configured in \`src/vitnode.config.ts\`, and the route manifest each of those
      // plugins ships. Nothing here is discovered at runtime - the browser is handed
      // this module, never a filesystem.
      //
      // Same plugin configuration in, same bytes out: the entries are sorted by key.

      import type {
        PluginRouteModuleRegistry,
        ResolvedPluginRouteModule,
      } from '@vitnode/core/framework/plugin-routes'

      /**
       * Every configured plugin's route modules, keyed by \`<pluginId>:<routeId>\`.
       *
       * The specifiers below are literal, which is the whole point of generating this
       * file: Vite resolves them at build time and Rollup gives each module its own
       * chunk, fetched when a loader is first called. No route component is in the
       * initial bundle, and none of them is reached through a computed string - the
       * browser never asks what is installed.
       *
       * \`satisfies\` rather than a type annotation, deliberately: it checks the shape
       * while keeping both the literal keys and each module's real export types, so a
       * consumer's \`await load()\` is typed by the module it loaded.
       */
      export const pluginRouteModules = {
        '@vitnode/example:example-page': () => import('@vitnode/example/routes/example-page'),
      } satisfies PluginRouteModuleRegistry

      /** Every key in {@link pluginRouteModules}, as a union. */
      export type PluginRouteKey = keyof typeof pluginRouteModules

      /**
       * The same route modules as plain data, in the same order.
       *
       * An object literal carries nothing beyond its keys, so the plugin id, the route
       * id and the specifier are repeated here for whatever builds the router: it can
       * walk this array, join each entry to its plugin's own route manifest by
       * \`pluginId\` and \`routeId\`, and look the loader up by \`key\`.
       */
      export const pluginRouteEntries = [
        {
          entry: 'routes/example-page',
          key: '@vitnode/example:example-page',
          pluginId: '@vitnode/example',
          routeId: 'example-page',
          specifier: '@vitnode/example/routes/example-page',
        },
      ] as const satisfies readonly ResolvedPluginRouteModule[]
      "
    `);
  });

  it("emits empty literals for an app whose plugins ship no routes", () => {
    const source = generate([
      { pluginId: "@vitnode/blog", routes: [] },
      { pluginId: "@vitnode/example", routes: [] },
    ]);

    expect(source).toContain(
      "export const pluginRouteModules = {} satisfies PluginRouteModuleRegistry",
    );
    expect(source).toContain(
      "export const pluginRouteEntries = [] as const satisfies readonly ResolvedPluginRouteModule[]",
    );
  });

  it("is byte-for-byte stable across calls", () => {
    expect(generate(EXAMPLE)).toBe(generate(EXAMPLE));
  });

  it("does not depend on the order the plugins were configured in", () => {
    const a = {
      pluginId: "@vitnode/blog",
      routes: [{ entry: "routes/a", id: "a" }],
    };
    const b = {
      pluginId: "@vitnode/example",
      routes: [{ entry: "routes/b", id: "b" }],
    };

    expect(generate([a, b])).toBe(generate([b, a]));
  });

  it("does not depend on the order one plugin declared its routes in", () => {
    const routes = [
      { entry: "routes/alpha", id: "alpha" },
      { entry: "routes/zebra", id: "zebra" },
    ];

    expect(generate([{ pluginId: "@vitnode/example", routes }])).toBe(
      generate([
        { pluginId: "@vitnode/example", routes: [...routes].reverse() },
      ]),
    );
  });

  it("emits one lazy import per route and nothing eager", () => {
    const source = generate([
      {
        pluginId: "@vitnode/example",
        routes: [
          { entry: "routes/one", id: "one" },
          { entry: "routes/two", id: "two" },
        ],
      },
    ]);

    // Every route import is `() => import('...')`. The one static import in the
    // file is type-only, so it is erased and nothing is pulled in eagerly.
    expect(source.match(/=> import\('/g)).toHaveLength(2);
    expect(source.match(/^import.*$/gm)).toEqual(["import type {"]);
  });

  it("sorts and de-duplicates its own input, not just the resolver's output", () => {
    const modules = [
      {
        entry: "routes/b",
        key: "@vitnode/example:b",
        pluginId: "@vitnode/example",
        routeId: "b",
        specifier: "@vitnode/example/routes/b",
      },
      {
        entry: "routes/a",
        key: "@vitnode/example:a",
        pluginId: "@vitnode/example",
        routeId: "a",
        specifier: "@vitnode/example/routes/a",
      },
    ];

    expect(generatePluginRouteRegistrySource(modules)).toBe(
      generatePluginRouteRegistrySource([...modules].reverse()),
    );
    expect(() =>
      generatePluginRouteRegistrySource([modules[0], modules[0]]),
    ).toThrow(/same registry key/);
  });

  it("escapes a specifier that somehow reached it unvalidated", () => {
    expect(
      generatePluginRouteRegistrySource([
        {
          entry: "routes/x",
          key: "@vitnode/example:x",
          pluginId: "@vitnode/example",
          routeId: "x",
          specifier: "@vitnode/example/routes/x'); evil(('",
        },
      ]),
    ).toContain("import('@vitnode/example/routes/x\\'); evil((\\'')");
  });
});
