import type {
  ResolvedPluginRouteModule,
  ResolvedPluginRouteSearchModule,
} from "./types.js";

import { sortAndAssertUnique, toSingleQuotedLiteral } from "./resolve.js";

/** Where the generated file imports its types from. */
const TYPES_SPECIFIER = "@vitnode/core/framework/plugin-routes";

/**
 * The generated file's header.
 *
 * `eslint-disable` and the "do not format" line are not decoration: the file is
 * rewritten on every build, so anything a linter or a formatter changes in it is
 * lost, and a formatter that reflows one entry would make the output depend on
 * how long a plugin's name happens to be. It is excluded from both in the app
 * that receives it, and this says so at the top for whoever opens it anyway.
 */
const HEADER_TYPES = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
// \`vite dev\` and \`vite build\`, from two inputs and nothing else: the plugins
// configured in \`src/vitnode.config.ts\`, and the route manifest each of those
// plugins ships. Nothing here is discovered at runtime - the browser is handed
// this module, never a filesystem.
//
// Same plugin configuration in, same bytes out: the entries are sorted by key.

import type {
  PluginRouteModuleRegistry,
  PluginRouteSearchRegistry,
  ResolvedPluginRouteModule,
} from '${TYPES_SPECIFIER}'

`;

/**
 * Everything after the eager search imports.
 *
 * Split from {@link HEADER_TYPES} because a static import has to be at the top
 * of the file, above the first `export const` - so the one part of this
 * generated module that is *not* lazy goes between the types and the registry
 * that would otherwise follow them directly.
 */
const HEADER_REGISTRY = `/**
 * Every configured plugin's route modules, keyed by \`<pluginId>:<routeId>\`.
 *
 * The specifiers below are literal, which is the whole point of generating this
 * file: Vite resolves them at build time and Rollup gives each module its own
 * chunk, fetched when a loader is first called. No route component is in the
 * initial bundle, and none of them is reached through a computed string - the
 * browser never asks what is installed.
 *
 * \`satisfies\` rather than a type annotation, deliberately: it checks the shape
 * while keeping both the literal keys and each module's real export types, so a
 * consumer's \`await load()\` is typed by the module it loaded.
 */
export const pluginRouteModules = `;

const MIDDLE = ` satisfies PluginRouteModuleRegistry

/** Every key in {@link pluginRouteModules}, as a union. */
export type PluginRouteKey = keyof typeof pluginRouteModules

/**
 * The same route modules as plain data, in the same order.
 *
 * An object literal carries nothing beyond its keys, so the plugin id, the route
 * id and the specifier are repeated here for whatever builds the router: it can
 * walk this array, join each entry to its plugin's own route manifest by
 * \`pluginId\` and \`routeId\`, and look the loader up by \`key\`.
 */
export const pluginRouteEntries = `;

const FOOTER = ` as const satisfies readonly ResolvedPluginRouteModule[]
`;

const SEARCH_HEADER = `
/**
 * The route search schemas this app imports **eagerly**, keyed the same way.
 *
 * The one thing about a plugin route that may not be lazy. A router's
 * \`validateSearch\` runs during path matching, before any chunk is fetched, so a
 * route that needs a real one - a paginated table whose \`?page=999\` has to be
 * clamped, a filter whose links must be typed - names a second module and the
 * build imports it statically, above.
 *
 * Sparse by design: a route is here only if its manifest entry declares a
 * \`searchEntry\`, and most do not. A route with no key here gets no
 * \`validateSearch\` and normalises its query string in the loader instead, which
 * is what every plugin route did before this registry existed.
 *
 * These modules are in the initial bundle. That is the cost, it is why the
 * contract on them is "the schema, not the screen", and it is why this list is
 * worth reading in a diff.
 */
export const pluginRouteSearchSchemas = `;

const SEARCH_FOOTER = ` satisfies PluginRouteSearchRegistry
`;

/**
 * The static imports the search registry is built from.
 *
 * Numbered rather than named after the route, because a route id contains
 * characters an identifier may not - and a positional name that is only ever
 * used two lines below is easier to check than an escaping rule. The plugin and
 * route are named in a trailing comment, which is what a reader actually wants.
 */
const searchImportLines = (
  modules: ResolvedPluginRouteSearchModule[],
): string => {
  if (modules.length === 0) return "";

  return `${modules
    .map(
      (module, index) =>
        `import { validateSearch as pluginRouteSearch${String(index)} } from ${toSingleQuotedLiteral(module.specifier)}`,
    )
    .join("\n")}\n`;
};

const searchRegistryLiteral = (
  modules: ResolvedPluginRouteSearchModule[],
): string => {
  if (modules.length === 0) return "{}";

  const entries = modules.map(
    (module, index) =>
      `  ${toSingleQuotedLiteral(module.key)}: pluginRouteSearch${String(index)},`,
  );

  return `{\n${entries.join("\n")}\n}`;
};

/**
 * Sorts search modules by key and rejects duplicates.
 *
 * The same rule {@link sortAndAssertUnique} applies to route modules, and
 * separate only because the two carry different fields. A duplicate here is
 * unreachable through the manifest - two routes cannot share an id - so this is
 * a guard on a caller that built the list some other way.
 */
const sortSearchModules = (
  modules: ResolvedPluginRouteSearchModule[],
): ResolvedPluginRouteSearchModule[] => {
  const sorted = [...modules].sort((a, b) =>
    a.key === b.key ? 0 : a.key < b.key ? -1 : 1,
  );

  const duplicates = sorted
    .filter(
      (module, index) => index > 0 && module.key === sorted[index - 1].key,
    )
    .map(module => module.key);

  if (duplicates.length > 0) {
    throw new Error(
      `[VitNode plugin routes] Two routes claim the same search registry key: ${[
        ...new Set(duplicates),
      ]
        .map(key => JSON.stringify(key))
        .join(", ")}.`,
    );
  }

  return sorted;
};

const registryLiteral = (modules: ResolvedPluginRouteModule[]): string => {
  if (modules.length === 0) return "{}";

  const entries = modules.map(
    module =>
      `  ${toSingleQuotedLiteral(module.key)}: () => import(${toSingleQuotedLiteral(module.specifier)}),`,
  );

  return `{\n${entries.join("\n")}\n}`;
};

const entriesLiteral = (modules: ResolvedPluginRouteModule[]): string => {
  if (modules.length === 0) return "[]";

  const entries = modules.map(module =>
    [
      "  {",
      `    entry: ${toSingleQuotedLiteral(module.entry)},`,
      `    key: ${toSingleQuotedLiteral(module.key)},`,
      `    pluginId: ${toSingleQuotedLiteral(module.pluginId)},`,
      `    routeId: ${toSingleQuotedLiteral(module.routeId)},`,
      `    specifier: ${toSingleQuotedLiteral(module.specifier)},`,
      "  },",
    ].join("\n"),
  );

  return `[\n${entries.join("\n")}\n]`;
};

/**
 * The source of an app's plugin route registry.
 *
 * A string rather than a file, so the one part of this that has to be exactly
 * reproducible is a pure function of its input and can be asserted byte for
 * byte. Writing it - and deciding whether it changed - belongs to the build tool
 * that has a filesystem.
 *
 * Sorted and de-duplicated again on the way in: the resolver already does both,
 * and doing it here as well is what makes "same configuration, same bytes" a
 * property of this function rather than a promise about how it is called.
 */
export const generatePluginRouteRegistrySource = (
  modules: ResolvedPluginRouteModule[],
  searchModules: ResolvedPluginRouteSearchModule[] = [],
): string => {
  const sorted = sortAndAssertUnique(modules);
  const search = sortSearchModules(searchModules);

  return [
    HEADER_TYPES,
    searchImportLines(search),
    HEADER_REGISTRY,
    registryLiteral(sorted),
    MIDDLE,
    entriesLiteral(sorted),
    FOOTER,
    SEARCH_HEADER,
    searchRegistryLiteral(search),
    SEARCH_FOOTER,
  ].join("");
};
