import type { ResolvedPluginRouteModule } from "./types.js";

import { sortAndAssertUnique, toSingleQuotedLiteral } from "./resolve.js";

/** Where the generated file imports its types from. */
const TYPES_SPECIFIER = "@vitnode/core/framework/plugin-routes";

/**
 * The generated file's header.
 *
 * `eslint-disable` and the "do not format" line are not decoration: the file is
 * rewritten on every build, so anything a linter or a formatter changes in it is
 * lost, and a formatter that reflows one entry would make the output depend on
 * how long a plugin's name happens to be. It is excluded from both in the app
 * that receives it, and this says so at the top for whoever opens it anyway.
 */
const HEADER = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
// \`vite dev\` and \`vite build\`, from two inputs and nothing else: the plugins
// configured in \`src/vitnode.config.ts\`, and the route manifest each of those
// plugins ships. Nothing here is discovered at runtime - the browser is handed
// this module, never a filesystem.
//
// Same plugin configuration in, same bytes out: the entries are sorted by key.

import type {
  PluginRouteModuleRegistry,
  ResolvedPluginRouteModule,
} from '${TYPES_SPECIFIER}'

/**
 * Every configured plugin's route modules, keyed by \`<pluginId>:<routeId>\`.
 *
 * The specifiers below are literal, which is the whole point of generating this
 * file: Vite resolves them at build time and Rollup gives each module its own
 * chunk, fetched when a loader is first called. No route component is in the
 * initial bundle, and none of them is reached through a computed string - the
 * browser never asks what is installed.
 *
 * \`satisfies\` rather than a type annotation, deliberately: it checks the shape
 * while keeping both the literal keys and each module's real export types, so a
 * consumer's \`await load()\` is typed by the module it loaded.
 */
export const pluginRouteModules = `;

const MIDDLE = ` satisfies PluginRouteModuleRegistry

/** Every key in {@link pluginRouteModules}, as a union. */
export type PluginRouteKey = keyof typeof pluginRouteModules

/**
 * The same route modules as plain data, in the same order.
 *
 * An object literal carries nothing beyond its keys, so the plugin id, the route
 * id and the specifier are repeated here for whatever builds the router: it can
 * walk this array, join each entry to its plugin's own route manifest by
 * \`pluginId\` and \`routeId\`, and look the loader up by \`key\`.
 */
export const pluginRouteEntries = `;

const FOOTER = ` as const satisfies readonly ResolvedPluginRouteModule[]
`;

const registryLiteral = (modules: ResolvedPluginRouteModule[]): string => {
  if (modules.length === 0) return "{}";

  const entries = modules.map(
    module =>
      `  ${toSingleQuotedLiteral(module.key)}: () => import(${toSingleQuotedLiteral(module.specifier)}),`,
  );

  return `{\n${entries.join("\n")}\n}`;
};

const entriesLiteral = (modules: ResolvedPluginRouteModule[]): string => {
  if (modules.length === 0) return "[]";

  const entries = modules.map(module =>
    [
      "  {",
      `    entry: ${toSingleQuotedLiteral(module.entry)},`,
      `    key: ${toSingleQuotedLiteral(module.key)},`,
      `    pluginId: ${toSingleQuotedLiteral(module.pluginId)},`,
      `    routeId: ${toSingleQuotedLiteral(module.routeId)},`,
      `    specifier: ${toSingleQuotedLiteral(module.specifier)},`,
      "  },",
    ].join("\n"),
  );

  return `[\n${entries.join("\n")}\n]`;
};

/**
 * The source of an app's plugin route registry.
 *
 * A string rather than a file, so the one part of this that has to be exactly
 * reproducible is a pure function of its input and can be asserted byte for
 * byte. Writing it - and deciding whether it changed - belongs to the build tool
 * that has a filesystem.
 *
 * Sorted and de-duplicated again on the way in: the resolver already does both,
 * and doing it here as well is what makes "same configuration, same bytes" a
 * property of this function rather than a promise about how it is called.
 */
export const generatePluginRouteRegistrySource = (
  modules: ResolvedPluginRouteModule[],
): string => {
  const sorted = sortAndAssertUnique(modules);

  return `${HEADER}${registryLiteral(sorted)}${MIDDLE}${entriesLiteral(sorted)}${FOOTER}`;
};
