import type {
  PluginRoute,
  PluginRouteManifest,
  PluginRouteSegment,
} from "../../routing/types.js";

import { comparePluginRoutes } from "../../routing/order.js";
import { toSingleQuotedLiteral } from "./resolve.js";

/** Where the generated file imports its type from. */
const TYPES_SPECIFIER = "@vitnode/core/routing";

/**
 * The generated file's header.
 *
 * Same rules as its sibling registry: rewritten on every build, so anything a
 * linter or a formatter changes in it is lost, and a reflow would make the
 * output depend on how long a plugin's name happens to be.
 */
const HEADER = `/* eslint-disable */

// This file is generated by VitNode. Do not edit it, and do not format it.
//
// It is rewritten by the \`vitnode:plugin-routes\` Vite plugin on every
// \`vite dev\` and \`vite build\`, from the plugins configured in
// \`src/vitnode.config.ts\` and the route manifest each of those plugins ships.
//
// This is the *what*: which routes exist, and at which canonical VitNode path.
// Its sibling \`plugin-routes.gen.ts\` is the *how*: one lazy import per route
// module. Neither knows what a router is.
//
// Same plugin configuration in, same bytes out: the routes are sorted by path.

import type { PluginRoute } from '${TYPES_SPECIFIER}'

/**
 * Every route this app's configured plugins contribute, already validated.
 *
 * \`buildPluginRouteManifest\` produced this list while the app was being built,
 * which is the whole reason it is a literal here: a path that cannot be parsed,
 * an entry that cannot be imported and two plugins claiming one URL have all
 * already failed the build by the time this file exists. Nothing reads it to
 * find out whether the routes are valid - only to find out what they are.
 *
 * Deliberately not \`as const\`: a route's \`segments\` is a mutable array on
 * \`PluginRoute\`, and a frozen tuple would not satisfy it. \`satisfies\` alone
 * still checks every field and still narrows \`area\` and \`kind\` to their unions.
 */
export const pluginRouteManifest = `;

const FOOTER = ` satisfies readonly PluginRoute[]
`;

const segmentLiteral = (segment: PluginRouteSegment): string =>
  segment.kind === "param"
    ? `{ kind: 'param', name: ${toSingleQuotedLiteral(segment.name)} }`
    : `{ kind: 'static', value: ${toSingleQuotedLiteral(segment.value)} }`;

/**
 * A value that is either a string literal or `null`.
 *
 * `parentId` and `requires` are both "declared, or not" - and both are emitted
 * as `null` rather than left out. A missing field would still satisfy
 * `PluginRoute` if the type ever loosened, and the whole reason the built type
 * has no optional members is so that a generator which forgets one is a compile
 * error rather than a route that silently loses its parent.
 */
const optionalLiteral = (value: null | string): string =>
  value === null ? "null" : toSingleQuotedLiteral(value);

const routeLiteral = (route: PluginRoute): string =>
  [
    "  {",
    `    area: ${toSingleQuotedLiteral(route.area)},`,
    `    entry: ${toSingleQuotedLiteral(route.entry)},`,
    `    id: ${toSingleQuotedLiteral(route.id)},`,
    `    kind: ${toSingleQuotedLiteral(route.kind)},`,
    `    namespaces: [${route.namespaces.map(toSingleQuotedLiteral).join(", ")}],`,
    `    parentId: ${optionalLiteral(route.parentId)},`,
    `    path: ${toSingleQuotedLiteral(route.path)},`,
    `    pluginId: ${toSingleQuotedLiteral(route.pluginId)},`,
    `    requires: ${optionalLiteral(route.requires)},`,
    `    routeId: ${toSingleQuotedLiteral(route.routeId)},`,
    `    segments: [${route.segments.map(segmentLiteral).join(", ")}],`,
    "  },",
  ].join("\n");

const manifestLiteral = (manifest: PluginRouteManifest): string => {
  if (manifest.length === 0) return "[]";

  return `[\n${manifest.map(routeLiteral).join("\n")}\n]`;
};

/**
 * The source of an app's plugin route manifest.
 *
 * A string rather than a file, for the same reason as
 * {@link generatePluginRouteRegistrySource}: the part that has to be exactly
 * reproducible is a pure function of its input and can be asserted byte for
 * byte, and writing it belongs to the build tool that has a filesystem.
 *
 * Sorted again on the way in with the manifest layer's own comparator, so "same
 * configuration, same bytes" is a property of this function rather than a
 * promise about how it is called.
 */
export const generatePluginRouteManifestSource = (
  manifest: PluginRouteManifest,
): string =>
  `${HEADER}${manifestLiteral([...manifest].sort(comparePluginRoutes))}${FOOTER}`;
