name: Build, Lint & Test

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v6.0.9
        name: Install pnpm
        with:
          version: 11.9.0

      - name: Install Node.js
        uses: actions/setup-node@v6.4.0
        with:
          registry-url: "https://registry.npmjs.org/"
          node-version: 24

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Scripts
        run: pnpm build:scripts

      - name: Build Plugins
        run: pnpm build:plugins

      - name: Run build
        run: pnpm build

      - name: Check formatting
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Run type tests
        run: pnpm test:types
